; data_frontend_10 C3014-C39B3  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "x86enc.inc"
section s_C3014 progbits alloc noexec write align=1
global asc_C3014, asc_C301C, asc_C3023, asc_C3028, asc_C302D, asc_C3032, asc_C3037, asc_C303C
global asc_C3041, asc_C3046, asc_C304B, asc_C3050, asc_C3055, asc_C305A, asc_C305F, asc_C3064
global asc_C306C, asc_C3072, asc_C307B, asc_C3081, asc_C3086, asc_C308D, asc_C3092, asc_C309A
global asc_C30A3, asc_C30AD, asc_C30B6, asc_C30BB, asc_C30C3, asc_C30C8, asc_C30CC, asc_C30D0
global asc_C30D9, asc_C30DE, asc_C30E3, asc_C30EB, asc_C30F2, asc_C30F7, asc_C30FE, asc_C3107
global asc_C3111, asc_C3122, asc_C3127, asc_C312D, asc_C3134, asc_C313F, asc_C3146, asc_C314E
global asc_C3152, asc_C3156, asc_C315A, asc_C3160, asc_C3164, asc_C316C, asc_C3171, asc_C3180
global asc_C3184, asc_C3189, asc_C3190, asc_C3194, asc_C319D, asc_C31A2, asc_C31A7, asc_C31AF
global asc_C31B6, asc_C31BB, asc_C31C2, asc_C31CB, asc_C31D5, asc_C31F1, asc_C31F7, asc_C3200
global asc_C3205, asc_C320D, asc_C3214, asc_C321B, asc_C3222, asc_C3229, asc_C322F, asc_C3236
global asc_C323D, asc_C3245, asc_C324C, asc_C3253, asc_C325B, asc_C3267, asc_C326D, asc_C3277
global asc_C3288, asc_C328E, asc_C32A4, asc_C32AA, asc_C32AF, asc_C32B5, asc_C32BC, asc_C32C1
global asc_C32CA, asc_C32CF, asc_C32D5, asc_C32DB, asc_C32EC, asc_C32F5, asc_C3300, asc_C3305
global asc_C330E, asc_C3317, asc_C331C, asc_C3322, asc_C3328, asc_C3339, asc_C3344, asc_C3349
global asc_C335A, asc_C3360, asc_C3366, asc_C336F, asc_C3374, asc_C337C, asc_C3381, asc_C3388
global asc_C338D, asc_C3393, asc_C3399, asc_C33A3, asc_C33B0, asc_C33BD, asc_C33CA, asc_C33D4
global asc_C33DC, asc_C33E4, asc_C33EC, asc_C3411, asc_C3419, asc_C3421, asc_C3426, asc_C342E
global asc_C3436, asc_C3449, asc_C3450, asc_C3472, asc_C3477, asc_C347B, asc_C3480, asc_C3489
global asc_C348E, asc_C3493, asc_C3498, asc_C349D, asc_C34A2, asc_C34A7, asc_C34AC, asc_C34B1
global asc_C34B6, asc_C34BB, asc_C34C0, asc_C34C5, asc_C34CA, asc_C3594, asc_C359C, asc_C35A3
global asc_C35AF, asc_C35BA, asc_C35C3, asc_C35CC, asc_C35D1, asc_C35D6, asc_C35DD, asc_C35E2
global asc_C35EC, asc_C35F3, asc_C35FA, asc_C3604, asc_C3612, asc_C3622, asc_C3627, asc_C362E
global asc_C3638, asc_C363D, asc_C3644, asc_C364A, asc_C364F, asc_C365A, asc_C3668, asc_C366F
global asc_C3675, asc_C3680, asc_C3688, asc_C368D, asc_C3696, asc_C369F, asc_C36A8, asc_C36AF
global asc_C36C3, asc_C36C9, asc_C3782, asc_C378C, asc_C3795, asc_C37A4, asc_C37D8, asc_C37DC
global asc_C37E8, asc_C37F5, asc_C3802, asc_C380F, asc_C381C, asc_C3829, asc_C3836, asc_C3843
global asc_C3850, asc_C385D, asc_C386A, asc_C3877, asc_C3884, asc_C3891, asc_C389E, asc_C38A6
global asc_C38B2, asc_C38B6, asc_C38BA, asc_C38BE, asc_C38C2, asc_C38CA, asc_C38D2, asc_C38D6
global asc_C38DC, asc_C38E4, asc_C38E8, asc_C38EC, asc_C38F0, asc_C38F8, asc_C3904, asc_C3923
global asc_C3932, asc_C3947, asc_C3966, asc_C3972, asc_C3976, asc_C397E, asc_C3986, asc_C398F
global asc_C3994, asc_C399B, asc_C39A0, qword_C37B0, qword_C37B8, qword_C37C0, qword_C37C8, qword_C37D0
global unk_C311D, unk_C311F, unk_C3143, unk_C314B, unk_C3169, unk_C3177, unk_C317A, unk_C317D
global unk_C31D9, unk_C31DC, unk_C31DF, unk_C31E2, unk_C31E5, unk_C31E8, unk_C31EB, unk_C31EE
global unk_C3283, unk_C3285, unk_C3292, unk_C3295, unk_C3298, unk_C329B, unk_C329E, unk_C32A1
global unk_C33F8, unk_C3403, unk_C3444, unk_C3447, unk_C344D, unk_C3468, unk_C346B, unk_C3470
global unk_C34D0, unk_C34D4, unk_C34D8, unk_C34DC, unk_C34E0, unk_C34E4, unk_C34E8, unk_C34EC
global unk_C34F0, unk_C34F4, unk_C34F8, unk_C34FB, unk_C34FF, unk_C3502, unk_C3506, unk_C350A
global unk_C350E, unk_C3512, unk_C3516, unk_C351A, unk_C351E, unk_C3521, unk_C3524, unk_C3528
global unk_C352C, unk_C3530, unk_C3534, unk_C3538, unk_C353C, unk_C355E, unk_C3580, unk_C35E9
global unk_C36AC, unk_C36D4, unk_C36E1, unk_C36EE, unk_C36FB, unk_C3706, unk_C3712, unk_C371F
global unk_C372C, unk_C3738, unk_C3742, unk_C374F, unk_C375C, unk_C3769, unk_C3775, unk_C392C
global unk_C392F, unk_C393B, unk_C393E, unk_C3941, unk_C3944, unk_C396F, unk_C397B, unk_C39A8
asc_C3014:
db 044h,053h,042h,04Fh,058h,00h,00h,00h
asc_C301C:
db 064h,062h,05Fh,062h,075h,074h,00h
asc_C3023:
db 06Eh,06Fh,06Eh,065h,00h
asc_C3028:
db 064h,065h,06Ch,020h,00h
asc_C302D:
db 06Fh,070h,065h,06Eh,00h
asc_C3032:
db 063h,061h,06Eh,020h,00h
asc_C3037:
db 06Eh,06Fh,061h,072h,00h
asc_C303C:
db 075h,070h,020h,020h,00h
asc_C3041:
db 064h,06Fh,077h,06Eh,00h
asc_C3046:
db 061h,072h,072h,06Fh,00h
asc_C304B:
db 064h,062h,06Eh,06Fh,00h
asc_C3050:
db 064h,062h,063h,075h,00h
asc_C3055:
db 064h,062h,074h,06Dh,00h
asc_C305A:
db 064h,062h,06Fh,072h,00h
asc_C305F:
db 02Ah,02Eh,064h,062h,00h
asc_C3064:
db 043h,055h,052h,052h,045h,04Eh,054h,00h
asc_C306C:
db 02Ah,02Eh,06Fh,072h,067h,00h
asc_C3072:
db 04Fh,052h,049h,047h,049h,04Eh,041h,04Ch,00h
asc_C307B:
db 02Ah,02Eh,064h,062h,078h,00h
asc_C3081:
db 04Fh,070h,065h,06Eh,00h
asc_C3086:
db 044h,065h,06Ch,065h,074h,065h,00h
asc_C308D:
db 044h,06Fh,06Eh,065h,00h
asc_C3092:
db 043h,075h,072h,072h,065h,06Eh,074h,00h
asc_C309A:
db 04Fh,072h,069h,067h,069h,06Eh,061h,06Ch,00h
asc_C30A3:
db 054h,065h,06Dh,070h,06Fh,072h,061h,072h,079h,00h
asc_C30AD:
db 064h,062h,064h,069h,061h,06Ch,06Fh,067h,00h
asc_C30B6:
db 070h,064h,062h,078h,00h
asc_C30BB:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C30C3:
db 02Eh,044h,042h,058h,00h
asc_C30C8:
db 062h,075h,066h,00h
asc_C30CC:
db 050h,061h,06Ch,00h
asc_C30D0:
db 06Ch,069h,06Eh,065h,064h,069h,074h,070h,00h
asc_C30D9:
db 073h,068h,072h,074h,00h
asc_C30DE:
db 070h,06Eh,074h,072h,00h
asc_C30E3:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C30EB:
db 065h,06Dh,062h,070h,061h,06Ch,00h
asc_C30F2:
db 021h,070h,061h,06Ch,00h
asc_C30F7:
db 06Ch,065h,06Ch,06Fh,067h,06Fh,00h
asc_C30FE:
db 06Dh,065h,06Eh,075h,062h,075h,066h,066h,00h
asc_C3107:
db 025h,063h,020h,025h,032h,064h,020h,025h,073h,00h
asc_C3111:
db 025h,073h,020h,025h,032h,064h,020h,025h,073h,025h,073h,00h
unk_C311D:
db 02Eh,00h
unk_C311F:
db 073h,02Eh,00h
asc_C3122:
db 06Bh,065h,079h,073h,00h
asc_C3127:
db 070h,073h,074h,061h,074h,00h
asc_C312D:
db 067h,073h,074h,061h,074h,00h,00h
asc_C3134:
db 025h,073h,020h,052h,06Fh,073h,074h,065h,072h,03Ah,00h
asc_C313F:
db 050h,06Fh,073h,00h
unk_C3143:
db 04Eh,06Fh,00h
asc_C3146:
db 04Eh,061h,06Dh,065h,00h
unk_C314B:
db 047h,050h,00h
asc_C314E:
db 020h,020h,047h,00h
asc_C3152:
db 020h,020h,041h,00h
asc_C3156:
db 020h,050h,054h,00h
asc_C315A:
db 053h,068h,06Fh,074h,073h,00h
asc_C3160:
db 050h,049h,04Dh,00h
asc_C3164:
db 020h,02Bh,02Fh,02Dh,00h
unk_C3169:
db 025h,063h,00h
asc_C316C:
db 020h,04Dh,069h,06Eh,00h
asc_C3171:
db 020h,020h,047h,041h,041h,00h
unk_C3177:
db 020h,057h,00h
unk_C317A:
db 020h,04Ch,00h
unk_C317D:
db 020h,054h,00h
asc_C3180:
db 020h,047h,041h,00h
asc_C3184:
db 020h,020h,053h,041h,00h
asc_C3189:
db 020h,020h,050h,043h,054h,00h,00h
asc_C3190:
db 050h,061h,06Ch,00h
asc_C3194:
db 06Ch,069h,06Eh,065h,064h,069h,074h,070h,00h
asc_C319D:
db 073h,068h,072h,074h,00h
asc_C31A2:
db 070h,06Eh,074h,072h,00h
asc_C31A7:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C31AF:
db 065h,06Dh,062h,070h,061h,06Ch,00h
asc_C31B6:
db 021h,070h,061h,06Ch,00h
asc_C31BB:
db 06Ch,065h,06Ch,06Fh,067h,06Fh,00h
asc_C31C2:
db 06Dh,065h,06Eh,075h,062h,075h,066h,066h,00h
asc_C31CB:
db 025h,063h,020h,025h,032h,064h,020h,025h,073h,00h
asc_C31D5:
db 06Bh,065h,079h,00h
unk_C31D9:
db 041h,031h,00h
unk_C31DC:
db 041h,032h,00h
unk_C31DF:
db 041h,033h,00h
unk_C31E2:
db 041h,034h,00h
unk_C31E5:
db 041h,035h,00h
unk_C31E8:
db 041h,036h,00h
unk_C31EB:
db 041h,037h,00h
unk_C31EE:
db 041h,038h,00h
asc_C31F1:
db 065h,06Dh,062h,025h,073h,00h
asc_C31F7:
db 048h,04Fh,04Dh,045h,050h,041h,04Ch,053h,00h
asc_C3200:
db 062h,06Bh,067h,064h,00h
asc_C3205:
db 066h,06Fh,072h,077h,061h,072h,064h,00h
asc_C320D:
db 06Ch,069h,06Eh,065h,020h,031h,00h
asc_C3214:
db 06Ch,069h,06Eh,065h,020h,032h,00h
asc_C321B:
db 06Ch,069h,06Eh,065h,020h,033h,00h
asc_C3222:
db 06Ch,069h,06Eh,065h,020h,034h,00h
asc_C3229:
db 070h,06Fh,077h,065h,072h,00h
asc_C322F:
db 070h,06Ch,061h,079h,020h,031h,00h
asc_C3236:
db 070h,06Ch,061h,079h,020h,032h,00h
asc_C323D:
db 070h,065h,06Eh,061h,06Ch,074h,079h,00h
asc_C3245:
db 06Bh,069h,06Ch,06Ch,020h,031h,00h
asc_C324C:
db 06Bh,069h,06Ch,06Ch,020h,032h,00h
asc_C3253:
db 064h,065h,066h,065h,06Eh,073h,065h,00h
asc_C325B:
db 067h,06Fh,061h,06Ch,074h,065h,06Eh,064h,065h,072h,073h,00h
asc_C3267:
db 065h,078h,074h,072h,061h,00h
asc_C326D:
db 061h,074h,074h,061h,063h,06Bh,065h,072h,073h,00h
asc_C3277:
db 025h,073h,020h,025h,032h,064h,020h,025h,073h,025h,073h,00h
unk_C3283:
db 02Eh,00h
unk_C3285:
db 073h,02Eh,00h
asc_C3288:
db 074h,065h,061h,06Dh,073h,00h
asc_C328E:
db 062h,032h,03Ah,00h
unk_C3292:
db 042h,033h,00h
unk_C3295:
db 042h,034h,00h
unk_C3298:
db 042h,035h,00h
unk_C329B:
db 042h,036h,00h
unk_C329E:
db 042h,037h,00h
unk_C32A1:
db 042h,032h,00h
asc_C32A4:
db 074h,073h,074h,061h,074h,00h
asc_C32AA:
db 06Bh,065h,079h,073h,00h
asc_C32AF:
db 070h,073h,074h,061h,074h,00h
asc_C32B5:
db 067h,073h,074h,061h,074h,00h,00h
asc_C32BC:
db 042h,04Bh,047h,044h,00h
asc_C32C1:
db 073h,065h,074h,074h,069h,06Eh,067h,035h,00h
asc_C32CA:
db 064h,062h,06Fh,078h,00h
asc_C32CF:
db 04Dh,075h,073h,069h,063h,00h
asc_C32D5:
db 053h,06Fh,075h,06Eh,064h,00h
asc_C32DB:
db 044h,069h,067h,069h,074h,069h,07Ah,065h,064h,020h,053h,070h,065h,065h,063h,068h
db 00h
asc_C32EC:
db 073h,065h,074h,074h,069h,06Eh,067h,033h,00h
asc_C32F5:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h,00h,00h,00h
asc_C3300:
db 042h,04Bh,047h,044h,00h
asc_C3305:
db 073h,065h,074h,074h,069h,06Eh,067h,037h,00h
asc_C330E:
db 073h,065h,074h,074h,069h,06Eh,067h,034h,00h
asc_C3317:
db 064h,062h,06Fh,078h,00h
asc_C331C:
db 04Dh,075h,073h,069h,063h,00h
asc_C3322:
db 053h,06Fh,075h,06Eh,064h,00h
asc_C3328:
db 044h,069h,067h,069h,074h,069h,07Ah,065h,064h,020h,053h,070h,065h,065h,063h,068h
db 00h
asc_C3339:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h,00h,00h,00h
asc_C3344:
db 042h,04Bh,047h,044h,00h
asc_C3349:
db 044h,069h,067h,069h,074h,069h,07Ah,065h,064h,020h,053h,070h,065h,065h,063h,068h
db 00h
asc_C335A:
db 04Dh,075h,073h,069h,063h,00h
asc_C3360:
db 053h,06Fh,075h,06Eh,064h,00h
asc_C3366:
db 073h,065h,074h,074h,069h,06Eh,067h,036h,00h
asc_C336F:
db 064h,062h,06Fh,078h,00h
asc_C3374:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C337C:
db 042h,04Bh,047h,044h,00h
asc_C3381:
db 070h,06Ch,061h,079h,065h,072h,00h
asc_C3388:
db 064h,062h,06Fh,078h,00h
asc_C338D:
db 04Fh,06Eh,065h,027h,073h,00h
asc_C3393:
db 054h,077h,06Fh,027h,073h,00h
asc_C3399:
db 054h,068h,065h,020h,04Dh,06Fh,075h,073h,065h,00h
asc_C33A3:
db 04Ah,06Fh,079h,073h,074h,069h,063h,06Bh,020h,04Fh,06Eh,065h,00h
asc_C33B0:
db 04Ah,06Fh,079h,073h,074h,069h,063h,06Bh,020h,054h,077h,06Fh,00h
asc_C33BD:
db 054h,068h,065h,020h,04Bh,065h,079h,062h,06Fh,061h,072h,064h,00h
asc_C33CA:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h,00h,00h
asc_C33D4:
db 04Dh,054h,052h,04Fh,043h,04Bh,055h,00h
asc_C33DC:
db 053h,042h,052h,04Fh,043h,04Bh,055h,00h
asc_C33E4:
db 041h,044h,052h,04Fh,043h,04Bh,055h,00h
asc_C33EC:
db 052h,04Fh,043h,04Bh,044h,049h,054h,049h,00h,00h,00h,00h
unk_C33F8:
db 042h,06Fh,074h,068h,020h,054h,065h,061h,06Dh,073h,00h
unk_C3403:
db 04Eh,065h,069h,074h,068h,065h,072h,020h,054h,065h,061h,06Dh,073h,00h
asc_C3411:
db 067h,061h,064h,067h,065h,074h,036h,00h
asc_C3419:
db 067h,061h,064h,067h,065h,074h,035h,00h
asc_C3421:
db 067h,061h,064h,031h,00h
asc_C3426:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C342E:
db 053h,061h,076h,065h,020h,054h,06Fh,00h
asc_C3436:
db 048h,069h,06Ch,069h,067h,068h,074h,073h,020h,052h,065h,065h,06Ch,00h
unk_C3444:
db 06Bh,031h,00h
unk_C3447:
db 05Ch,00h
asc_C3449:
db 02Eh,048h,049h,00h
unk_C344D:
db 066h,031h,00h
asc_C3450:
db 043h,061h,06Eh,020h,06Eh,06Fh,074h,020h,06Fh,070h,065h,06Eh,020h,060h,025h,073h
db 027h,020h,066h,069h,06Ch,065h,0Ah,00h
unk_C3468:
db 066h,033h,00h
unk_C346B:
db 066h,034h,00h,00h,00h
unk_C3470:
db 02Eh,00h
asc_C3472:
db 048h,04Ch,054h,04Ch,00h
asc_C3477:
db 048h,04Ch,054h,00h
asc_C347B:
db 048h,04Ch,054h,053h,00h
asc_C3480:
db 073h,065h,074h,074h,069h,06Eh,067h,073h,00h
asc_C3489:
db 04Fh,06Eh,020h,020h,00h
asc_C348E:
db 04Fh,066h,066h,020h,00h
asc_C3493:
db 061h,063h,070h,074h,00h
asc_C3498:
db 063h,061h,06Eh,063h,00h
asc_C349D:
db 06Eh,061h,030h,031h,00h
asc_C34A2:
db 06Eh,061h,030h,033h,00h
asc_C34A7:
db 06Eh,061h,030h,035h,00h
asc_C34AC:
db 070h,067h,030h,031h,00h
asc_C34B1:
db 070h,067h,030h,033h,00h
asc_C34B6:
db 070h,067h,030h,035h,00h
asc_C34BB:
db 070h,067h,030h,037h,00h
asc_C34C0:
db 070h,06Ch,030h,035h,00h
asc_C34C5:
db 070h,06Ch,031h,030h,00h
asc_C34CA:
db 070h,06Ch,032h,030h,00h,00h
unk_C34D0:
db 041h,04Eh,041h,00h
unk_C34D4:
db 042h,04Fh,053h,00h
unk_C34D8:
db 042h,055h,046h,00h
unk_C34DC:
db 043h,047h,059h,00h
unk_C34E0:
db 043h,048h,049h,00h
unk_C34E4:
db 044h,041h,04Ch,00h
unk_C34E8:
db 044h,045h,054h,00h
unk_C34EC:
db 045h,044h,04Dh,00h
unk_C34F0:
db 046h,04Ch,041h,00h
unk_C34F4:
db 048h,046h,044h,00h
unk_C34F8:
db 04Ch,041h,00h
unk_C34FB:
db 04Dh,054h,04Ch,00h
unk_C34FF:
db 04Eh,04Ah,00h
unk_C3502:
db 04Eh,059h,049h,00h
unk_C3506:
db 04Eh,059h,052h,00h
unk_C350A:
db 04Fh,054h,054h,00h
unk_C350E:
db 050h,048h,049h,00h
unk_C3512:
db 050h,049h,054h,00h
unk_C3516:
db 051h,055h,045h,00h
unk_C351A:
db 053h,054h,04Ch,00h
unk_C351E:
db 053h,04Ah,00h
unk_C3521:
db 054h,042h,00h
unk_C3524:
db 054h,04Fh,052h,00h
unk_C3528:
db 056h,041h,04Eh,00h
unk_C352C:
db 057h,053h,048h,00h
unk_C3530:
db 057h,050h,047h,00h
unk_C3534:
db 041h,053h,057h,00h
unk_C3538:
db 041h,053h,045h,00h
unk_C353C:
db 057h,065h,073h,074h,065h,072h,06Eh,020h,043h,06Fh,06Eh,066h,065h,072h,065h,06Eh
db 063h,065h,020h,051h,075h,061h,072h,074h,065h,072h,02Dh,046h,069h,06Eh,061h,06Ch
db 073h,00h
unk_C355E:
db 045h,061h,073h,074h,065h,072h,06Eh,020h,043h,06Fh,06Eh,066h,065h,072h,065h,06Eh
db 063h,065h,020h,051h,075h,061h,072h,074h,065h,072h,02Dh,046h,069h,06Eh,061h,06Ch
db 073h,00h
unk_C3580:
db 053h,074h,061h,06Eh,06Ch,065h,079h,020h,043h,075h,070h,06h,020h,046h,069h,06Eh
db 061h,06Ch,073h,00h
asc_C3594:
db 048h,06Fh,06Dh,065h,042h,063h,06Bh,00h
asc_C359C:
db 056h,069h,073h,042h,063h,06Bh,00h
asc_C35A3:
db 048h,06Fh,06Dh,065h,04Eh,061h,06Dh,065h,042h,063h,06Bh,00h
asc_C35AF:
db 056h,069h,073h,04Eh,061h,06Dh,065h,042h,063h,06Bh,00h
asc_C35BA:
db 054h,069h,074h,06Ch,065h,042h,063h,06Bh,00h
asc_C35C3:
db 06Ch,06Fh,063h,06Bh,072h,06Fh,06Fh,06Dh,00h
asc_C35CC:
db 021h,070h,030h,031h,00h
asc_C35D1:
db 072h,06Fh,06Fh,06Dh,00h
asc_C35D6:
db 04Ah,045h,052h,025h,073h,048h,00h
asc_C35DD:
db 030h,030h,030h,030h,00h
asc_C35E2:
db 04Ah,045h,052h,025h,073h,056h,00h
unk_C35E9:
db 076h,073h,00h
asc_C35EC:
db 041h,063h,063h,065h,070h,074h,00h
asc_C35F3:
db 043h,061h,06Eh,063h,065h,06Ch,00h
asc_C35FA:
db 048h,06Fh,06Dh,065h,020h,054h,065h,061h,06Dh,00h
asc_C3604:
db 056h,069h,073h,069h,074h,069h,06Eh,067h,020h,054h,065h,061h,06Dh,00h
asc_C3612:
db 045h,078h,068h,069h,062h,069h,074h,069h,06Fh,06Eh,020h,047h,061h,06Dh,065h,00h
asc_C3622:
db 02Eh,069h,066h,066h,00h
asc_C3627:
db 06Ah,065h,072h,073h,065h,079h,00h
asc_C362E:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h,00h,00h
asc_C3638:
db 074h,065h,06Dh,070h,00h
asc_C363D:
db 062h,075h,066h,066h,065h,072h,00h
asc_C3644:
db 073h,06Fh,075h,06Eh,064h,00h
asc_C364A:
db 064h,062h,078h,032h,00h
asc_C364F:
db 050h,043h,020h,053h,070h,065h,061h,06Bh,065h,072h,00h
asc_C365A:
db 053h,06Fh,075h,06Eh,064h,020h,042h,06Ch,061h,073h,074h,065h,072h,00h
asc_C3668:
db 041h,044h,020h,04Ch,069h,062h,00h
asc_C366F:
db 04Dh,054h,02Dh,033h,032h,00h
asc_C3675:
db 055h,06Ch,074h,072h,061h,053h,06Fh,075h,06Eh,064h,00h
asc_C3680:
db 050h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C3688:
db 02Eh,069h,066h,066h,00h
asc_C368D:
db 06Dh,061h,069h,06Eh,064h,065h,073h,06Bh,00h
asc_C3696:
db 073h,06Ch,061h,070h,073h,068h,06Fh,074h,00h
asc_C369F:
db 04Dh,054h,033h,032h,048h,04Fh,043h,04Bh,00h
asc_C36A8:
db 04Eh,048h,04Ch,00h
unk_C36AC:
db 072h,02Bh,00h
asc_C36AF:
db 063h,061h,06Eh,06Eh,06Fh,074h,020h,06Fh,070h,065h,06Eh,020h,06Eh,068h,06Ch,02Eh
db 063h,066h,067h,00h
asc_C36C3:
db 025h,030h,034h,078h,0Ah,00h
asc_C36C9:
db 065h,06Dh,06Dh,063h,06Fh,070h,079h,062h,075h,066h,00h
unk_C36D4:
db 072h,06Fh,075h,067h,068h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C36E1:
db 063h,068h,061h,072h,067h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C36EE:
db 073h,06Ch,061h,073h,068h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C36FB:
db 078h,063h,068h,065h,063h,06Bh,02Eh,070h,065h,06Eh,00h
unk_C3706:
db 068h,06Fh,06Fh,06Bh,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C3712:
db 074h,072h,069h,070h,070h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C371F:
db 069h,06Eh,074h,065h,072h,066h,065h,072h,02Eh,070h,065h,06Eh,00h
unk_C372C:
db 068h,06Fh,06Ch,064h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C3738:
db 061h,062h,075h,073h,065h,02Eh,070h,065h,06Eh,00h
unk_C3742:
db 063h,068h,065h,063h,06Bh,062h,06Eh,064h,02Eh,070h,065h,06Eh,00h
unk_C374F:
db 062h,06Fh,061h,072h,064h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C375C:
db 065h,06Ch,062h,06Fh,077h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
unk_C3769:
db 068h,069h,073h,074h,069h,063h,06Bh,02Eh,070h,065h,06Eh,00h
unk_C3775:
db 073h,070h,065h,061h,072h,069h,06Eh,067h,02Eh,070h,065h,06Eh,00h
asc_C3782:
db 073h,070h,065h,065h,063h,068h,062h,075h,066h,00h
asc_C378C:
db 073h,065h,06Eh,074h,065h,06Eh,063h,065h,00h
asc_C3795:
db 073h,061h,06Dh,070h,06Ch,065h,020h,06Dh,065h,06Dh,020h,06Dh,061h,06Eh,00h
asc_C37A4:
db 073h,070h,065h,065h,063h,068h,020h,062h,061h,06Eh,06Bh,00h
qword_C37B0:
db 00h,00h,00h,00h,00h,00h,059h,040h
qword_C37B8:
db 00h,00h,00h,00h,00h,088h,0B5h,040h
qword_C37C0:
db 00h,00h,00h,00h,080h,088h,0C5h,040h
qword_C37C8:
db 00h,00h,00h,00h,00h,00h,059h,040h
qword_C37D0:
db 00h,00h,00h,00h,080h,088h,0C5h,040h
asc_C37D8:
db 063h,06Fh,072h,00h
asc_C37DC:
db 067h,061h,06Dh,065h,06Dh,069h,073h,063h,02Eh,025h,073h,00h
asc_C37E8:
db 065h,061h,073h,074h,071h,075h,061h,064h,02Eh,062h,061h,072h,00h
asc_C37F5:
db 065h,061h,073h,074h,073h,065h,06Dh,064h,02Eh,062h,061h,072h,00h
asc_C3802:
db 065h,061h,073h,074h,066h,069h,06Eh,064h,02Eh,062h,061h,072h,00h
asc_C380F:
db 077h,065h,073h,074h,071h,075h,061h,064h,02Eh,062h,061h,072h,00h
asc_C381C:
db 077h,065h,073h,074h,073h,065h,06Dh,064h,02Eh,062h,061h,072h,00h
asc_C3829:
db 077h,065h,073h,074h,066h,069h,06Eh,064h,02Eh,062h,061h,072h,00h
asc_C3836:
db 073h,074h,061h,06Eh,06Ch,065h,079h,064h,02Eh,062h,061h,072h,00h
asc_C3843:
db 065h,061h,073h,074h,071h,075h,061h,075h,02Eh,062h,061h,072h,00h
asc_C3850:
db 065h,061h,073h,074h,073h,065h,06Dh,075h,02Eh,062h,061h,072h,00h
asc_C385D:
db 065h,061h,073h,074h,066h,069h,06Eh,075h,02Eh,062h,061h,072h,00h
asc_C386A:
db 077h,065h,073h,074h,071h,075h,061h,075h,02Eh,062h,061h,072h,00h
asc_C3877:
db 077h,065h,073h,074h,073h,065h,06Dh,075h,02Eh,062h,061h,072h,00h
asc_C3884:
db 077h,065h,073h,074h,066h,069h,06Eh,075h,02Eh,062h,061h,072h,00h
asc_C3891:
db 073h,074h,061h,06Eh,06Ch,065h,079h,075h,02Eh,062h,061h,072h,00h
asc_C389E:
db 06Eh,068h,06Ch,02Eh,069h,06Eh,074h,00h
asc_C38A6:
db 065h,06Ch,073h,065h,06Eh,068h,06Ch,02Eh,069h,06Eh,074h,00h
asc_C38B2:
db 072h,06Eh,06Bh,00h
asc_C38B6:
db 061h,077h,061h,00h
asc_C38BA:
db 068h,06Fh,06Dh,00h
asc_C38BE:
db 062h,061h,072h,00h
asc_C38C2:
db 067h,061h,06Dh,065h,06Eh,075h,06Dh,00h
asc_C38CA:
db 025h,073h,025h,073h,02Eh,025h,073h,00h
asc_C38D2:
db 06Eh,075h,06Dh,00h
asc_C38D6:
db 025h,064h,02Eh,025h,073h,00h
asc_C38DC:
db 025h,030h,032h,064h,02Eh,025h,073h,00h
asc_C38E4:
db 074h,065h,061h,00h
asc_C38E8:
db 070h,065h,06Eh,00h
asc_C38EC:
db 066h,072h,06Dh,00h
asc_C38F0:
db 058h,042h,052h,055h,043h,045h,032h,00h
asc_C38F8:
db 067h,073h,075h,06Dh,06Dh,061h,072h,079h,02Eh,064h,062h,00h
asc_C3904:
db 061h,020h,067h,061h,06Dh,065h,02Ch,020h,079h,06Fh,075h,020h,072h,065h,071h,075h
db 069h,072h,065h,020h,025h,033h,064h,020h,04Bh,062h,079h,074h,065h,073h,00h
asc_C3923:
db 064h,065h,06Dh,06Fh,02Eh,06Eh,068h,06Ch,00h
unk_C392C:
db 068h,032h,00h
unk_C392F:
db 068h,033h,00h
asc_C3932:
db 067h,073h,075h,06Dh,06Dh,061h,072h,079h,00h
unk_C393B:
db 068h,034h,00h
unk_C393E:
db 068h,035h,00h
unk_C3941:
db 068h,036h,00h
unk_C3944:
db 068h,037h,00h
asc_C3947:
db 061h,020h,067h,061h,06Dh,065h,02Ch,020h,079h,06Fh,075h,020h,072h,065h,071h,075h
db 069h,072h,065h,020h,025h,033h,064h,020h,04Bh,062h,079h,074h,065h,073h,00h
asc_C3966:
db 067h,061h,06Dh,065h,02Eh,073h,061h,076h,00h
unk_C396F:
db 068h,031h,00h
asc_C3972:
db 02Eh,064h,062h,00h
asc_C3976:
db 02Eh,073h,061h,076h,00h
unk_C397B:
db 041h,033h,00h
asc_C397E:
db 070h,06Fh,069h,06Eh,074h,065h,072h,00h
asc_C3986:
db 073h,061h,076h,065h,067h,061h,06Dh,065h,00h
asc_C398F:
db 070h,072h,06Dh,074h,00h
asc_C3994:
db 064h,069h,061h,06Ch,06Fh,067h,00h
asc_C399B:
db 02Eh,06Eh,068h,06Ch,00h
asc_C39A0:
db 065h,072h,072h,031h,00h,00h,00h,00h
unk_C39A8:
db 025h,073h,020h,025h,064h,020h,02Dh,020h,025h,064h,00h
