; data_season95_23 C7BD1-C7C1D  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_C7BD1 progbits alloc noexec write align=1
extern unk_C7BBB
global dword_C7BD5, unk_C7BD1, unk_C7BD9, unk_C7BEA, unk_C7BEE, unk_C7C06
unk_C7BD1:
dd unk_C7BBB
dword_C7BD5:
db 00h,00h,00h,00h
unk_C7BD9:
db 043h,072h,065h,061h,074h,069h,06Eh,067h,020h,06Ch,065h,061h,067h,075h,065h,02Eh
db 00h
unk_C7BEA:
dd unk_C7BD9
unk_C7BEE:
db 054h,068h,061h,074h,020h,066h,06Ch,06Fh,070h,070h,079h,020h,064h,069h,073h,06Bh
db 020h,068h,061h,073h,020h,061h,06Eh,00h
unk_C7C06:
db 06Fh,06Ch,064h,020h,063h,06Fh,070h,079h,020h,06Fh,066h,020h,074h,068h,065h,020h
db 06Ch,065h,061h,067h,075h,065h,00h
