; data_frontend_24 C7C1D-C7DEA  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_C7C1D progbits alloc noexec write align=1
extern unk_C744C, unk_C7450, unk_C7BEE, unk_C7C06
global str_IsAlreadyMerged, str_HasNotBeenMerged, oldcopymsg, newfloppymsg, importtypemsg
global lgexistsmsg, unk_C7C29, unk_C7C42, newfloppybtns, unk_C7C99, unk_C7CB9, unk_C7CDB, unk_C7CE2
global importtypebtns, unk_C7D29, unk_C7D47, unk_C7D6A, mergestatemsg, unk_C7DA9, unk_C7DBE, unk_C7DD4
oldcopymsg:
dd unk_C7BEE
dd unk_C7C06
db 00h,00h,00h,00h
unk_C7C29:
db 041h,072h,065h,020h,079h,06Fh,075h,020h,073h,075h,072h,065h,020h,079h,06Fh,075h
db 020h,077h,061h,06Eh,074h,020h,074h,06Fh,00h
unk_C7C42:
db 075h,073h,065h,020h,061h,020h,06Eh,065h,077h,020h,066h,06Ch,06Fh,070h,070h,079h
db 020h,064h,069h,073h,06Bh,03Fh,00h
newfloppymsg:
dd unk_C7C29
dd unk_C7C42
newfloppybtns:
db 010h,00h,00h,00h,03Ch,00h,00h,00h,028h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,05h,00h,00h,00h
dd unk_C744C
db 0F0h,0FFh,0FFh,0FFh,03Ch,00h,00h,00h,028h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,06h,00h,00h,00h
dd unk_C7450
unk_C7C99:
db 049h,06Dh,070h,06Fh,072h,074h,020h,06Dh,061h,073h,074h,065h,072h,020h,063h,06Fh
db 070h,079h,020h,06Fh,066h,020h,06Ch,065h,061h,067h,075h,065h,020h,06Fh,072h,00h
unk_C7CB9:
db 069h,06Dh,070h,06Fh,072h,074h,020h,066h,06Fh,072h,020h,070h,06Ch,061h,079h,065h
db 072h,020h,06Fh,06Eh,020h,066h,06Ch,06Fh,070h,070h,079h,020h,064h,069h,073h,06Bh
db 03Fh,00h
unk_C7CDB:
db 04Dh,061h,073h,074h,065h,072h,00h
unk_C7CE2:
db 050h,06Ch,061h,079h,065h,072h,00h
importtypemsg:
dd unk_C7C99
dd unk_C7CB9
importtypebtns:
db 010h,00h,00h,00h,03Ch,00h,00h,00h,060h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,05h,00h,00h,00h
dd unk_C7CDB
db 0F0h,0FFh,0FFh,0FFh,03Ch,00h,00h,00h,060h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,06h,00h,00h,00h
dd unk_C7CE2
unk_C7D29:
db 043h,061h,06Eh,020h,06Eh,06Fh,074h,020h,069h,06Dh,070h,06Fh,072h,074h,020h,06Dh
db 061h,073h,074h,065h,072h,020h,06Ch,065h,061h,067h,075h,065h,021h,00h
unk_C7D47:
db 054h,068h,065h,020h,06Ch,065h,061h,067h,075h,065h,020h,061h,06Ch,072h,065h,061h
db 064h,079h,020h,065h,078h,069h,073h,074h,073h,021h,00h
lgexistsmsg:
dd unk_C7D29
dd unk_C7D47
unk_C7D6A:
db 054h,068h,065h,020h,06Ch,065h,061h,067h,075h,065h,00h
str_IsAlreadyMerged:
db 069h,073h,020h,061h,06Ch,072h,065h,061h,064h,079h,020h,06Dh,065h,072h,067h,065h
db 064h,02Eh,00h
str_HasNotBeenMerged:
db 068h,061h,073h,020h,06Eh,06Fh,074h,020h,062h,065h,065h,06Eh,020h,06Dh,065h,072h
db 067h,065h,064h,02Eh,00h
mergestatemsg:
dd unk_C7D6A
db 00h,00h,00h,00h
db 00h,00h,00h,00h
unk_C7DA9:
db 04Dh,061h,073h,074h,065h,072h,020h,064h,061h,074h,061h,062h,061h,073h,065h,073h
db 020h,066h,06Fh,072h,00h
unk_C7DBE:
db 06Dh,075h,073h,074h,020h,062h,065h,020h,06Dh,065h,072h,067h,065h,064h,020h,066h
db 069h,072h,073h,074h,021h,00h
unk_C7DD4:
db 044h,06Fh,020h,079h,06Fh,075h,020h,077h,061h,06Eh,074h,020h,074h,06Fh,020h,06Dh
db 065h,072h,067h,065h,03Fh,00h
