; data_engine_39 CD34C-CD9D0  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_CD34C progbits alloc noexec write align=1
extern asc_C223B, unk_C1B49, unk_C1BE3, unk_C1BEC, unk_C1BF5, unk_C1BFE, unk_C1C05, unk_C1C0D
extern unk_C1C16, unk_C1C1F, unk_C1C27, unk_C1C2F, unk_C1C38, unk_C1C41, unk_C1C47, unk_C1C50
extern unk_C1D64, unk_C1D72, unk_C1D7E, unk_C1D87, unk_C1D93, unk_C1D9B, unk_C1DA1, unk_C1DA9
extern unk_C1DDC, unk_C1DE3, unk_C1DEB, unk_C1DF3, unk_C1DFB, unk_C1E04, unk_C1E0C, unk_C1E14
extern unk_C1E1C, unk_C1E24, unk_C1E2A, unk_C1E31, unk_C1E38, unk_C1E3E, unk_C1E44, unk_C1E4C
extern unk_C1E52, unk_C1E58, unk_C1E5E, unk_C1E63, unk_C1E69, unk_C1E6F, unk_C1E75, unk_C1E7B
extern unk_C1E85, unk_C1E8F, unk_C1E98, unk_C1EA5, unk_C1EB2, unk_C1EBA, unk_C1EC2, unk_C1EC8
extern unk_C1ECD, unk_C1ED3, unk_C1ED9, unk_C1EE1, unk_C1EEA, unk_C1EF4, unk_C1EF9, unk_C1F03
extern unk_C1F0C, unk_C1F14, unk_C1F1D, unk_C1F23, unk_C1F2A, unk_C1F32, unk_C1F38, unk_C1F3D
extern unk_C1F43, unk_C1F4B, unk_C1F50, unk_C1F55, unk_C1F5D, unk_C1F66, unk_C1F6F, unk_C1F78
extern unk_C1F81, unk_C1F89, unk_C1F95, unk_C1FA0, unk_C1FAB, unk_C1FB6, unk_C1FC1, unk_C1FCB
extern unk_C1FD5, unk_C1FE1, unk_C1FE9, unk_C1FF3, unk_C1FFC, unk_C2006, unk_C200F, unk_C2019
extern unk_C2021, unk_C2029, unk_C2035, unk_C203D, unk_C2049, unk_C2053, unk_C205F, unk_C206A
extern unk_C2074, unk_C207C, unk_C2084, unk_C208C, unk_C2094, unk_C209C, unk_C20A2, unk_C20AD
extern unk_C20B8, unk_C20C1, unk_C20CA, unk_C20D1, unk_C20D7, unk_C20DD, unk_C20E2, unk_C20E9
extern unk_C20F4, unk_C20FE, unk_C2109, unk_C2114, unk_C211E, unk_C212A, unk_C2136, unk_C2141
extern unk_C214C, unk_C2157, unk_C2162, unk_C216D, unk_C2179, unk_C2185, unk_C218F, unk_C2199
extern unk_C21A6, unk_C21B3, unk_C21BD, unk_C21C8, unk_C21D3, unk_C21DD, unk_C21E6, unk_C21F1
extern unk_C21F7, unk_C21FC, unk_C2201, unk_C2206, unk_C220C, unk_C2212, unk_C2218, unk_C221E
extern unk_C2224, unk_C2229, unk_C222F, unk_C2235, unk_C223F, unk_C2245, unk_C224C, unk_C2256
extern unk_C225C, unk_C2264, unk_C226A, unk_C2272, unk_C2278, unk_C227F, unk_C2286, unk_C228C
extern unk_C2292, unk_C229B, unk_C22A1, unk_C22A8, unk_C22B3, unk_C22BC, unk_C22C2, unk_C22CB
extern unk_C22D3, unk_C22DB, unk_C22E6, unk_C22EE, unk_C22F3, unk_C22F9, unk_C2301, unk_C2309
extern unk_C2311, unk_C231A, unk_C2323, unk_C232B, unk_C2332, unk_C2338, unk_C233A, unk_C233D
extern unk_C2340, unk_C2343, unk_C2345, unk_C2348, unk_CDC47, unk_CDC60, unk_CDC79, unk_CDC97
extern unk_CDCB0, unk_CDCC9
global byte_CD418, byte_CD421, byte_CD473, dword_CD34C, dword_CD350, dword_CD41E, dword_CD4B0, dword_CD504
global dword_CD9A0, off_CD354, off_CD498, off_CD4A0, off_CD4DC, off_CD4FA, off_CD6E4, off_CD8C4
global off_CD984, word_CD39C, word_CD4FC, replaytick, replaysfx
dword_CD34C:
db 00h,00h,00h,00h
dword_CD350:
db 00h,00h,00h,00h
off_CD354:
dd unk_C1BE3
dd unk_C1B49
dd unk_C1BEC
dd unk_C1BF5
dd unk_C1BE3
dd unk_C1BFE
dd unk_C1C05
dd unk_C1C0D
dd unk_C1C16
dd unk_C1C1F
dd unk_C1C27
dd unk_C1C2F
dd unk_C1C38
dd unk_C1C41
dd unk_C1C47
dd unk_C1C2F
dd unk_C1C38
dd unk_C1C50
word_CD39C:
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,02h,00h,00h,00h
db 02h,00h,00h,00h,02h,00h,00h,00h,05h,00h,00h,00h,0FFh,0FFh,0FFh,0FFh
db 04h,00h,00h,00h,06h,00h,00h,00h,0FFh,0FFh,0FFh,0FFh,06h,00h,00h,00h
db 06h,00h,00h,00h,06h,00h,00h,00h,06h,00h,00h,00h,06h,00h,00h,00h
db 06h,00h,00h,00h,06h,00h,00h,00h,06h,00h,00h,00h,06h,00h,00h,00h
db 06h,00h,00h,00h,06h,00h,00h,00h,06h,00h,00h,00h,06h,00h,00h,00h
db 06h,00h,00h,00h,06h,00h,00h,00h,07h,00h,00h,00h,0FFh,0FFh,0FFh,0FFh
db 06h,00h,00h,00h,03h,00h,00h,00h,02h,00h,00h,00h
byte_CD418:
db 00h,00h,02h,01h,01h,00h
dword_CD41E:
db 00h,01h,00h
byte_CD421:
db 00h,03h,06h,09h,0FFh,01h,04h,07h,0Ah,0FFh,02h,05h,08h,0Bh,0FFh,0Ch
db 0Eh,010h,0FFh,0Dh,0Fh,011h,0FFh,012h,017h,00h,03h,06h,09h,0FFh,013h,018h
db 01h,04h,07h,0Ah,0FFh,014h,019h,02h,05h,08h,0Bh,0FFh,015h,01Ah,0Ch,0Eh
db 010h,0FFh,016h,01Bh,0Dh,0Fh,011h,0FFh,01Ch,020h,00h,03h,06h,09h,0FFh,01Dh
db 021h,01h,04h,07h,0Ah,0FFh,01Eh,022h,0Ch,0Eh,010h,0FFh,01Fh,023h,0Dh,0Fh
db 011h,0FFh
byte_CD473:
db 00h,05h,0Ah,00h,05h,0Ah,00h,05h,0Ah,00h,05h,0Ah,0Fh,013h,0Fh,013h
db 0Fh,013h,017h,01Eh,025h,02Ch,032h,017h,01Eh,025h,02Ch,032h,038h,03Fh,046h,04Ch
db 038h,03Fh,046h,04Ch,00h
off_CD498:
dd unk_CDC47
dd unk_CDC60
off_CD4A0:
dd unk_CDC79
dd unk_CDC97
dd unk_CDCB0
dd unk_CDCC9
dword_CD4B0:
db 0Dh,0ACh,00h,00h,0CDh,05Ch,00h,00h,0A5h,050h,00h,00h,0AAh,050h,00h,00h
db 023h,03Ch,00h,00h,07Bh,04Fh,00h,00h,084h,06Dh,00h,00h,0D1h,037h,01h,00h
db 0D5h,0D0h,01h,00h,075h,0C4h,00h,00h,0C5h,0C7h,01h,00h
off_CD4DC:
dd unk_C1D64
dd unk_C1D72
dd unk_C1D7E
dd unk_C1D87
dd unk_C1D93
dd unk_C1D9B
dd unk_C1DA1
off_CD4FA equ $+2
dd unk_C1DA9
word_CD4FC:
db 0FFh,0FFh
replaytick:
db 01h,00h
replaysfx:
db 0FFh,0FFh,00h,00h
dword_CD504:
db 01h,00h,00h,00h,099h,00h,00h,00h,0B1h,00h,00h,00h,0C9h,00h,00h,00h
db 0E1h,00h,00h,00h,01h,01h,00h,00h,019h,01h,00h,00h,031h,01h,00h,00h
db 059h,01h,00h,00h,081h,01h,00h,00h,0B9h,01h,00h,00h,0F1h,01h,00h,00h
db 039h,02h,00h,00h,089h,02h,00h,00h,0A1h,02h,00h,00h,0E9h,02h,00h,00h
db 031h,03h,00h,00h,049h,03h,00h,00h,061h,03h,00h,00h,089h,03h,00h,00h
db 0C1h,03h,00h,00h,0F9h,03h,00h,00h,091h,04h,00h,00h,029h,05h,00h,00h
db 041h,05h,00h,00h,089h,05h,00h,00h,0C1h,05h,00h,00h,0D9h,05h,00h,00h
db 0F1h,05h,00h,00h,09h,06h,00h,00h,021h,06h,00h,00h,039h,06h,00h,00h
db 051h,06h,00h,00h,069h,06h,00h,00h,081h,06h,00h,00h,0D9h,06h,00h,00h
db 031h,07h,00h,00h,069h,07h,00h,00h,0A1h,07h,00h,00h,0BFh,07h,00h,00h
db 0DDh,07h,00h,00h,0F1h,07h,00h,00h,0FDh,07h,00h,00h,021h,08h,00h,00h
db 033h,08h,00h,00h,04Bh,08h,00h,00h,073h,08h,00h,00h,08Bh,08h,00h,00h
db 0D3h,08h,00h,00h,02Bh,09h,00h,00h,093h,09h,00h,00h,0Bh,0Ah,00h,00h
db 05Bh,0Ah,00h,00h,073h,0Ah,00h,00h,0BBh,0Ah,00h,00h,0D3h,0Ah,00h,00h
db 0EBh,0Ah,00h,00h,013h,0Bh,00h,00h,04Bh,0Bh,00h,00h,063h,0Bh,00h,00h
db 0ABh,0Bh,00h,00h,0C3h,0Bh,00h,00h,0DBh,0Bh,00h,00h,03h,0Ch,00h,00h
db 01Bh,0Ch,00h,00h,043h,0Ch,00h,00h,057h,0Ch,00h,00h,063h,0Ch,00h,00h
db 073h,0Ch,00h,00h,08Bh,0Ch,00h,00h,09Bh,0Ch,00h,00h,0ABh,0Ch,00h,00h
db 0BBh,0Ch,00h,00h,0CBh,0Ch,00h,00h,0D9h,0Ch,00h,00h,0E7h,0Ch,00h,00h
db 0F5h,0Ch,00h,00h,05h,0Dh,00h,00h,015h,0Dh,00h,00h,02Dh,0Dh,00h,00h
db 045h,0Dh,00h,00h,057h,0Dh,00h,00h,067h,0Dh,00h,00h,07Bh,0Dh,00h,00h
db 089h,0Dh,00h,00h,097h,0Dh,00h,00h,0ABh,0Dh,00h,00h,0C3h,0Dh,00h,00h
db 0D3h,0Dh,00h,00h,02Bh,0Eh,00h,00h,083h,0Eh,00h,00h,097h,0Eh,00h,00h
db 0A9h,0Eh,00h,00h,0B5h,0Eh,00h,00h,0CBh,0Eh,00h,00h,0D7h,0Eh,00h,00h
db 0Fh,0Fh,00h,00h,055h,0Fh,00h,00h,09Bh,0Fh,00h,00h,0E1h,0Fh,00h,00h
db 027h,010h,00h,00h,055h,010h,00h,00h,083h,010h,00h,00h,095h,010h,00h,00h
db 0CDh,010h,00h,00h,035h,011h,00h,00h,09Dh,011h,00h,00h,0D5h,011h,00h,00h
db 01Dh,012h,00h,00h,065h,012h,00h,00h,0DDh,012h,00h,00h,055h,013h,00h,00h
db 08Dh,013h,00h,00h,0C5h,013h,00h,00h,01Dh,014h,00h,00h,075h,014h,00h,00h
db 0ADh,014h,00h,00h,0E5h,014h,00h,00h,0F9h,014h,00h,00h,0Dh,015h,00h,00h
off_CD6E4:
dd unk_C1DDC
dd unk_C1DE3
dd unk_C1DEB
dd unk_C1DF3
dd unk_C1DFB
dd unk_C1E04
dd unk_C1E0C
dd unk_C1E14
dd unk_C1E1C
dd unk_C1E24
dd unk_C1E2A
dd unk_C1E31
dd unk_C1E38
dd unk_C1E3E
dd unk_C1E44
dd unk_C1E4C
dd unk_C1E52
dd unk_C1E58
dd unk_C1E5E
dd unk_C1E63
dd unk_C1E69
dd unk_C1E6F
dd unk_C1E75
dd unk_C1E7B
dd unk_C1E85
dd unk_C1E8F
dd unk_C1E98
dd unk_C1EA5
dd unk_C1EB2
dd unk_C1EBA
dd unk_C1EC2
dd unk_C1EC8
dd unk_C1ECD
dd unk_C1ED3
dd unk_C1ED9
dd unk_C1EE1
dd unk_C1EEA
dd unk_C1EF4
dd unk_C1EF9
dd unk_C1F03
dd unk_C1F0C
dd unk_C1F14
dd unk_C1F1D
dd unk_C1F23
dd unk_C1F2A
dd unk_C1F32
dd unk_C1F38
dd unk_C1F3D
dd unk_C1F43
dd unk_C1F4B
dd unk_C1F50
dd unk_C1F55
dd unk_C1F5D
dd unk_C1F66
dd unk_C1F6F
dd unk_C1F78
dd unk_C1F81
dd unk_C1F89
dd unk_C1F95
dd unk_C1FA0
dd unk_C1FAB
dd unk_C1FB6
dd unk_C1FC1
dd unk_C1FCB
dd unk_C1FD5
dd unk_C1FE1
dd unk_C1FE9
dd unk_C1FF3
dd unk_C1FFC
dd unk_C2006
dd unk_C200F
dd unk_C2019
dd unk_C2021
dd unk_C2029
dd unk_C2035
dd unk_C203D
dd unk_C2049
dd unk_C2053
dd unk_C205F
dd unk_C206A
dd unk_C2074
dd unk_C207C
dd unk_C2084
dd unk_C208C
dd unk_C2094
dd unk_C209C
dd unk_C20A2
dd unk_C20AD
dd unk_C20B8
dd unk_C20C1
dd unk_C20CA
dd unk_C20D1
dd unk_C20D7
dd unk_C20DD
dd unk_C20E2
dd unk_C20E9
dd unk_C20F4
dd unk_C20FE
dd unk_C2109
dd unk_C2114
dd unk_C211E
dd unk_C212A
dd unk_C2136
dd unk_C2141
dd unk_C214C
dd unk_C2157
dd unk_C2162
dd unk_C216D
dd unk_C2179
dd unk_C2185
dd unk_C218F
dd unk_C2199
dd unk_C21A6
dd unk_C21B3
dd unk_C21BD
dd unk_C21C8
dd unk_C21D3
dd unk_C21DD
dd unk_C21E6
dd unk_C21F1
off_CD8C4:
dd unk_C21F7
dd unk_C21FC
dd unk_C2201
dd unk_C2206
dd unk_C220C
dd unk_C2212
dd unk_C2218
dd unk_C221E
dd unk_C2224
dd unk_C2229
dd unk_C222F
dd unk_C2235
dd asc_C223B
dd unk_C223F
dd unk_C2245
dd unk_C224C
dd unk_C2256
dd unk_C225C
dd unk_C2264
dd unk_C226A
dd unk_C2272
dd unk_C2278
dd unk_C227F
dd unk_C1F0C
dd unk_C2286
dd unk_C228C
dd unk_C2292
dd unk_C229B
dd unk_C22A1
dd unk_C22A8
dd unk_C22B3
dd unk_C22BC
dd unk_C22C2
dd unk_C22CB
dd unk_C22D3
dd unk_C22DB
dd unk_C22E6
dd unk_C22EE
dd unk_C22F3
dd unk_C22F9
dd unk_C2301
dd unk_C2309
dd unk_C20CA
dd unk_C2311
dd unk_C231A
dd unk_C2323
dd unk_C232B
dd unk_C2332
off_CD984:
dd unk_C2338
dd unk_C233A
dd unk_C233D
dd unk_C2340
dd unk_C2343
dd unk_C2345
dd unk_C2348
dword_CD9A0:
db 00h,00h,024h,0FFh,0B0h,0FFh,079h,0FFh,019h,00h,09Ch,0FFh,092h,0FFh,0C9h,0FFh
db 01Eh,00h,0DCh,0FFh,050h,00h,0B8h,0FFh,00h,00h,0DCh,00h,028h,00h,052h,00h
db 0C2h,0FFh,048h,00h,06Eh,00h,024h,00h,0F1h,0FFh,09h,00h,0C9h,0FFh,00h,00h
