; data_frontend_50 D075E-D0819  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "x86enc.inc"
section s_D075E progbits alloc noexec write align=1
extern unk_D068A, unk_D0720, unk_D0740, unk_D0752
global asc_D07B6, byte_D079E, byte_D079F, byte_D07A8, byte_D07A9, dword_D07AA, dword_D07AE, dword_D07B2
global dword_D07BB, dword_D07BF, dword_D07C3, dword_D07C7, dword_D07CB, dword_D07CF, dword_D07D3, dword_D07D7
global dword_D07DB, dword_D07DF, dword_D07E3, dword_D07E7, unk_D075E, unk_D07EB
unk_D075E:
db 00h,00h,00h,00h,00h,00h,00h,00h,075h,00h,00h,00h,012h,00h,00h,00h
dd unk_D0740
db 00h,00h,00h,00h
dd unk_D0720
db 01h,00h,00h,00h,076h,00h,00h,00h,00h,00h,00h,00h,0BEh,00h,00h,00h
db 012h,00h,00h,00h
dd unk_D0752
db 00h,00h,00h,00h
dd unk_D068A
db 02h,00h,00h,00h
byte_D079E:
db 0Ch
byte_D079F:
db 015h,07Dh,00h,00h,00h,0B7h,01h,00h,00h
byte_D07A8:
db 00h
byte_D07A9:
db 00h
dword_D07AA:
db 00h,00h,00h,00h
dword_D07AE:
db 00h,00h,00h,00h
dword_D07B2:
db 00h,00h,00h,00h
asc_D07B6:
db 02Eh,054h,04Dh,050h,00h
dword_D07BB:
db 00h,00h,00h,00h
dword_D07BF:
db 00h,00h,00h,00h
dword_D07C3:
db 00h,00h,00h,00h
dword_D07C7:
db 00h,00h,00h,00h
dword_D07CB:
db 00h,00h,00h,00h
dword_D07CF:
db 00h,00h,00h,00h
dword_D07D3:
db 00h,00h,00h,00h
dword_D07D7:
db 00h,00h,00h,00h
dword_D07DB:
db 00h,00h,00h,00h
dword_D07DF:
db 00h,00h,00h,00h
dword_D07E3:
db 00h,00h,00h,00h
dword_D07E7:
db 00h,00h,00h,00h
unk_D07EB:
db 025h,063h,00h,04Eh,061h,06Dh,065h,03Ah,020h,025h,073h,020h,025h,073h,00h,025h
db 073h,020h,025h,073h,00h,025h,073h,020h,041h,06Ch,06Ch,020h,053h,074h,061h,072h
db 020h,054h,065h,061h,06Dh,00h,043h,061h,072h,065h,065h,072h,03Ah,00h
