; data_frontend_52 D0B16-D0C5C  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_D0B16 progbits alloc noexec write align=1
extern unk_C744C, unk_C7450
global dword_D0B16, dword_D0B1A, dword_D0B1E, dword_D0B22, dword_D0B26, dword_D0B2A, dword_D0BFC, dword_D0C04
global dword_D0C10, dword_D0C18, dword_D0C20, unk_D0B76, unk_D0B79, unk_D0B80, unk_D0BB8, unk_D0BF0
global savedbbtns
dword_D0B16:
db 041h,00h,00h,00h
dword_D0B1A:
db 040h,00h,00h,00h
dword_D0B1E:
db 042h,00h,00h,00h
dword_D0B22:
db 041h,00h,00h,00h
dword_D0B26:
db 040h,00h,00h,00h
dword_D0B2A:
db 042h,00h,00h,00h,0A9h,01h,00h,00h,0B0h,00h,00h,00h,0A9h,01h,00h,00h
db 0BDh,00h,00h,00h,0A9h,01h,00h,00h,0CAh,00h,00h,00h,0A9h,01h,00h,00h
db 0D7h,00h,00h,00h,0A9h,01h,00h,00h,0E4h,00h,00h,00h,0A9h,01h,00h,00h
db 0F1h,00h,00h,00h,0A9h,01h,00h,00h,0FEh,00h,00h,00h,0A9h,01h,00h,00h
db 0Bh,01h,00h,00h,09Ch,0FFh,0FFh,0FFh,09Ch,0FFh,0FFh,0FFh
unk_D0B76:
db 04Fh,04Bh,00h
unk_D0B79:
db 043h,061h,06Eh,063h,065h,06Ch,00h
unk_D0B80:
db 0D2h,00h,00h,00h,036h,01h,00h,00h,048h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,05h,00h,00h,00h
dd unk_D0B76
db 06Bh,01h,00h,00h,036h,01h,00h,00h,048h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,05h,00h,00h,00h
dd unk_D0B79
unk_D0BB8:
db 03Ah,01h,00h,00h,024h,00h,00h,00h,0Ch,00h,00h,00h,0Ah,00h,00h,00h
db 00h,00h,00h,00h,05h,00h,00h,00h,00h,00h,00h,00h,03Ah,01h,00h,00h
db 0D2h,01h,00h,00h,0Ch,00h,00h,00h,0Ah,00h,00h,00h,00h,00h,00h,00h
db 05h,00h,00h,00h,00h,00h,00h,00h
unk_D0BF0:
db 03Ah,01h,00h,00h,02Eh,00h,00h,00h,0Ch,00h,00h,00h
dword_D0BFC:
db 0A4h,01h,00h,00h,00h,00h,00h,00h
dword_D0C04:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D0C10:
db 00h,00h,00h,00h,00h,00h,00h,00h
dword_D0C18:
db 00h,00h,00h,00h,00h,00h,00h,00h
dword_D0C20:
db 00h,00h,00h,00h
savedbbtns:
db 08h,00h,00h,00h,01Ch,00h,00h,00h,028h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,05h,00h,00h,00h
dd unk_C7450
db 0F8h,0FFh,0FFh,0FFh,01Ch,00h,00h,00h,028h,00h,00h,00h,014h,00h,00h,00h
db 00h,00h,00h,00h,06h,00h,00h,00h
dd unk_C744C
