; data_sounddrv_69 D71F0-D89E4  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_D71F0 progbits alloc noexec write align=1
extern byte_D6CE0, byte_D6E24, byte_D6F68, byte_D70AC, unk_C4B50
global byte_D7618, byte_D7619, byte_D781C, byte_D7A2C, byte_D7A3C, byte_D7AEC, byte_D7B18, byte_D7B58
global byte_D7B5C, byte_D7D70, byte_D7DB0, byte_D7DB4, byte_D7FC8, byte_D8008, byte_D800C, byte_D8220
global byte_D8260, byte_D8264, byte_D849C, byte_D84A0, byte_D86C8, byte_D877A, byte_D87D8, byte_D89E0
global dword_D7200, dword_D7204, dword_D7208, dword_D720C, dword_D7614, dword_D7A1E, dword_D7A22, dword_D7A28
global dword_D7ABC, dword_D7AF0, dword_D7AF4, dword_D7AF8, dword_D7AFC, dword_D7B00, dword_D7B04, dword_D7B08
global dword_D7B0C, dword_D7B1C, dword_D7B30, dword_D7B34, dword_D7B38, dword_D7B44, dword_D7B48, dword_D7B4C
global dword_D7B50, dword_D7B60, dword_D7D64, dword_D7D74, dword_D7D88, dword_D7D8C, dword_D7D90, dword_D7D9C
global dword_D7DA0, dword_D7DA4, dword_D7DA8, dword_D7DB8, dword_D7FBC, dword_D7FCC, dword_D7FE0, dword_D7FE4
global dword_D7FE8, dword_D7FF4, dword_D7FF8, dword_D7FFC, dword_D8000, dword_D8010, dword_D8214, dword_D8224
global dword_D8238, dword_D823C, dword_D8240, dword_D824C, dword_D8250, dword_D8254, dword_D8258, dword_D8268
global dword_D847C, dword_D8480, dword_D8484, dword_D8488, dword_D848C, dword_D8490, dword_D8494, dword_D8498
global dword_D84A8, dword_D84AC, dword_D84B0, dword_D84B4, dword_D84B8, dword_D84C0, dword_D84C4, dword_D84CC
global dword_D84D0, dword_D8510, dword_D8550, dword_D8590, dword_D85D0, dword_D8610, dword_D8690, dword_D8696
global dword_D869C, dword_D86A2, dword_D86A8, dword_D86AC, dword_D86B0, dword_D86B8, dword_D86BC, dword_D86C0
global dword_D86DC, dword_D8784, dword_D87A0, dword_D87A8, dword_D87AC, dword_D87B0, dword_D87B4, dword_D87B8
global dword_D87BC, dword_D87C0, dword_D87C4, dword_D87C8, dword_D87CC, dword_D87D0, dword_D87D4, dword_D87DC
global dword_D87E0, dword_D89D8, dword_D89DC, off_D71F0, off_D846C, word_D7214, word_D7216, word_D7218
global word_D721A, word_D721C, word_D721E, word_D7220, word_D7222, word_D7224, word_D7226, word_D7228
global word_D722A, word_D722C, word_D722E, word_D7230, word_D7232, word_D7234, word_D7236, word_D7238
global word_D723A, word_D723C, word_D723E, word_D7240, word_D7242, word_D7244, word_D7246, word_D7248
global word_D724A, word_D724C, word_D724E, word_D7250, word_D7252, word_D7254, word_D7256, word_D7258
global word_D725A, word_D725C, word_D725E, word_D7260, word_D7262, word_D7264, word_D7266, word_D7268
global word_D726A, word_D726C, word_D726E, word_D7270, word_D7272, word_D7274, word_D7276, word_D7278
global word_D727A, word_D727C, word_D727E, word_D7280, word_D7282, word_D7284, word_D7286, word_D7288
global word_D728A, word_D728C, word_D728E, word_D7290, word_D7292, word_D7294, word_D7296, word_D7298
global word_D729A, word_D729C, word_D729E, word_D72A0, word_D72A2, word_D72A4, word_D72A6, word_D72A8
global word_D72AA, word_D72AC, word_D72AE, word_D72B0, word_D72B2, word_D72B4, word_D72B6, word_D72B8
global word_D72BA, word_D72BC, word_D72BE, word_D72C0, word_D72C2, word_D72C4, word_D72C6, word_D72C8
global word_D72CA, word_D72CC, word_D72CE, word_D72D0, word_D72D2, word_D72D4, word_D72D6, word_D72D8
global word_D72DA, word_D72DC, word_D72DE, word_D72E0, word_D72E2, word_D72E4, word_D72E6, word_D72E8
global word_D72EA, word_D72EC, word_D72EE, word_D72F0, word_D72F2, word_D72F4, word_D72F6, word_D72F8
global word_D72FA, word_D72FC, word_D72FE, word_D7300, word_D7302, word_D7304, word_D7306, word_D7308
global word_D730A, word_D730C, word_D730E, word_D7310, word_D7312, word_D7314, word_D7316, word_D7318
global word_D731A, word_D731C, word_D731E, word_D7320, word_D7322, word_D7324, word_D7326, word_D7328
global word_D732A, word_D732C, word_D732E, word_D7330, word_D7332, word_D7334, word_D7336, word_D7338
global word_D733A, word_D733C, word_D733E, word_D7340, word_D7342, word_D7344, word_D7346, word_D7348
global word_D734A, word_D734C, word_D734E, word_D7350, word_D7352, word_D7354, word_D7356, word_D7358
global word_D735A, word_D735C, word_D735E, word_D7360, word_D7362, word_D7364, word_D7366, word_D7368
global word_D736A, word_D736C, word_D736E, word_D7370, word_D7372, word_D7374, word_D7376, word_D7378
global word_D737A, word_D737C, word_D737E, word_D7380, word_D7382, word_D7384, word_D7386, word_D7388
global word_D738A, word_D738C, word_D738E, word_D7390, word_D7392, word_D7394, word_D7396, word_D7398
global word_D739A, word_D739C, word_D739E, word_D73A0, word_D73A2, word_D73A4, word_D73A6, word_D73A8
global word_D73AA, word_D73AC, word_D73AE, word_D73B0, word_D73B2, word_D73B4, word_D73B6, word_D73B8
global word_D73BA, word_D73BC, word_D73BE, word_D73C0, word_D73C2, word_D73C4, word_D73C6, word_D73C8
global word_D73CA, word_D73CC, word_D73CE, word_D73D0, word_D73D2, word_D73D4, word_D73D6, word_D73D8
global word_D73DA, word_D73DC, word_D73DE, word_D73E0, word_D73E2, word_D73E4, word_D73E6, word_D73E8
global word_D73EA, word_D73EC, word_D73EE, word_D73F0, word_D73F2, word_D73F4, word_D73F6, word_D73F8
global word_D73FA, word_D73FC, word_D73FE, word_D7400, word_D7402, word_D7404, word_D7406, word_D7408
global word_D740A, word_D740C, word_D740E, word_D7410, word_D7412, word_D7414, word_D7B64, word_D7DBC
global word_D8014, word_D826C, word_D84BC, word_D84BE, word_D84C2, word_D84C6, word_D8694, word_D869A
global word_D86A0, word_D86A6, word_D86B4, word_D86B6, word_D86DA, word_D86E0, word_D8760, word_D8762
global word_D8764, word_D8766, word_D8768, word_D876A, word_D876C, word_D876E, word_D8770, word_D8772
global word_D8774, word_D8776, word_D8778, word_D8788
off_D71F0:
dd byte_D6CE0
dd byte_D6E24
dd byte_D6F68
dd byte_D70AC
dword_D7200:
db 00h,00h,00h,00h
dword_D7204:
db 00h,00h,00h,00h
dword_D7208:
db 00h,00h,00h,00h
dword_D720C:
db 00h,00h,00h,00h,014h,00h,00h,00h
word_D7214:
db 00h,00h
word_D7216:
db 00h,00h
word_D7218:
db 00h,00h
word_D721A:
db 00h,00h
word_D721C:
db 00h,00h
word_D721E:
db 00h,00h
word_D7220:
db 00h,00h
word_D7222:
db 00h,00h
word_D7224:
db 00h,00h
word_D7226:
db 00h,00h
word_D7228:
db 00h,00h
word_D722A:
db 00h,00h
word_D722C:
db 00h,00h
word_D722E:
db 00h,00h
word_D7230:
db 00h,00h
word_D7232:
db 00h,00h
word_D7234:
db 00h,00h
word_D7236:
db 00h,00h
word_D7238:
db 00h,00h
word_D723A:
db 00h,00h
word_D723C:
db 00h,00h
word_D723E:
db 00h,00h
word_D7240:
db 00h,00h
word_D7242:
db 00h,00h
word_D7244:
db 00h,00h
word_D7246:
db 00h,00h
word_D7248:
db 00h,00h
word_D724A:
db 00h,00h
word_D724C:
db 00h,00h
word_D724E:
db 00h,00h
word_D7250:
db 00h,00h
word_D7252:
db 00h,00h
word_D7254:
db 00h,00h
word_D7256:
db 00h,00h
word_D7258:
db 00h,00h
word_D725A:
db 00h,00h
word_D725C:
db 00h,00h
word_D725E:
db 00h,00h
word_D7260:
db 00h,00h
word_D7262:
db 00h,00h
word_D7264:
db 00h,00h
word_D7266:
db 00h,00h
word_D7268:
db 00h,00h
word_D726A:
db 00h,00h
word_D726C:
db 00h,00h
word_D726E:
db 00h,00h
word_D7270:
db 00h,00h
word_D7272:
db 00h,00h
word_D7274:
db 00h,00h
word_D7276:
db 00h,00h
word_D7278:
db 00h,00h
word_D727A:
db 00h,00h
word_D727C:
db 00h,00h
word_D727E:
db 00h,00h
word_D7280:
db 00h,00h
word_D7282:
db 00h,00h
word_D7284:
db 00h,00h
word_D7286:
db 00h,00h
word_D7288:
db 00h,00h
word_D728A:
db 00h,00h
word_D728C:
db 00h,00h
word_D728E:
db 00h,00h
word_D7290:
db 00h,00h
word_D7292:
db 00h,00h
word_D7294:
db 00h,00h
word_D7296:
db 00h,00h
word_D7298:
db 00h,00h
word_D729A:
db 00h,00h
word_D729C:
db 00h,00h
word_D729E:
db 00h,00h
word_D72A0:
db 00h,00h
word_D72A2:
db 00h,00h
word_D72A4:
db 00h,00h
word_D72A6:
db 00h,00h
word_D72A8:
db 00h,00h
word_D72AA:
db 00h,00h
word_D72AC:
db 00h,00h
word_D72AE:
db 00h,00h
word_D72B0:
db 00h,00h
word_D72B2:
db 00h,00h
word_D72B4:
db 00h,00h
word_D72B6:
db 00h,00h
word_D72B8:
db 00h,00h
word_D72BA:
db 00h,00h
word_D72BC:
db 00h,00h
word_D72BE:
db 00h,00h
word_D72C0:
db 00h,00h
word_D72C2:
db 00h,00h
word_D72C4:
db 00h,00h
word_D72C6:
db 00h,00h
word_D72C8:
db 00h,00h
word_D72CA:
db 00h,00h
word_D72CC:
db 00h,00h
word_D72CE:
db 00h,00h
word_D72D0:
db 00h,00h
word_D72D2:
db 00h,00h
word_D72D4:
db 00h,00h
word_D72D6:
db 00h,00h
word_D72D8:
db 00h,00h
word_D72DA:
db 00h,00h
word_D72DC:
db 00h,00h
word_D72DE:
db 00h,00h
word_D72E0:
db 00h,00h
word_D72E2:
db 00h,00h
word_D72E4:
db 00h,00h
word_D72E6:
db 00h,00h
word_D72E8:
db 00h,00h
word_D72EA:
db 00h,00h
word_D72EC:
db 00h,00h
word_D72EE:
db 00h,00h
word_D72F0:
db 00h,00h
word_D72F2:
db 00h,00h
word_D72F4:
db 00h,00h
word_D72F6:
db 00h,00h
word_D72F8:
db 00h,00h
word_D72FA:
db 00h,00h
word_D72FC:
db 00h,00h
word_D72FE:
db 00h,00h
word_D7300:
db 00h,00h
word_D7302:
db 00h,00h
word_D7304:
db 00h,00h
word_D7306:
db 00h,00h
word_D7308:
db 00h,00h
word_D730A:
db 00h,00h
word_D730C:
db 00h,00h
word_D730E:
db 00h,00h
word_D7310:
db 00h,00h
word_D7312:
db 00h,00h
word_D7314:
db 00h,00h
word_D7316:
db 00h,00h
word_D7318:
db 00h,00h
word_D731A:
db 00h,00h
word_D731C:
db 00h,00h
word_D731E:
db 00h,00h
word_D7320:
db 00h,00h
word_D7322:
db 00h,00h
word_D7324:
db 00h,00h
word_D7326:
db 00h,00h
word_D7328:
db 00h,00h
word_D732A:
db 00h,00h
word_D732C:
db 00h,00h
word_D732E:
db 00h,00h
word_D7330:
db 00h,00h
word_D7332:
db 00h,00h
word_D7334:
db 00h,00h
word_D7336:
db 00h,00h
word_D7338:
db 00h,00h
word_D733A:
db 00h,00h
word_D733C:
db 00h,00h
word_D733E:
db 00h,00h
word_D7340:
db 00h,00h
word_D7342:
db 00h,00h
word_D7344:
db 00h,00h
word_D7346:
db 00h,00h
word_D7348:
db 00h,00h
word_D734A:
db 00h,00h
word_D734C:
db 00h,00h
word_D734E:
db 00h,00h
word_D7350:
db 00h,00h
word_D7352:
db 00h,00h
word_D7354:
db 00h,00h
word_D7356:
db 00h,00h
word_D7358:
db 00h,00h
word_D735A:
db 00h,00h
word_D735C:
db 00h,00h
word_D735E:
db 00h,00h
word_D7360:
db 00h,00h
word_D7362:
db 00h,00h
word_D7364:
db 00h,00h
word_D7366:
db 00h,00h
word_D7368:
db 00h,00h
word_D736A:
db 00h,00h
word_D736C:
db 00h,00h
word_D736E:
db 00h,00h
word_D7370:
db 00h,00h
word_D7372:
db 00h,00h
word_D7374:
db 00h,00h
word_D7376:
db 00h,00h
word_D7378:
db 00h,00h
word_D737A:
db 00h,00h
word_D737C:
db 00h,00h
word_D737E:
db 00h,00h
word_D7380:
db 00h,00h
word_D7382:
db 00h,00h
word_D7384:
db 00h,00h
word_D7386:
db 00h,00h
word_D7388:
db 00h,00h
word_D738A:
db 00h,00h
word_D738C:
db 00h,00h
word_D738E:
db 00h,00h
word_D7390:
db 00h,00h
word_D7392:
db 00h,00h
word_D7394:
db 00h,00h
word_D7396:
db 00h,00h
word_D7398:
db 00h,00h
word_D739A:
db 00h,00h
word_D739C:
db 00h,00h
word_D739E:
db 00h,00h
word_D73A0:
db 00h,00h
word_D73A2:
db 00h,00h
word_D73A4:
db 00h,00h
word_D73A6:
db 00h,00h
word_D73A8:
db 00h,00h
word_D73AA:
db 00h,00h
word_D73AC:
db 00h,00h
word_D73AE:
db 00h,00h
word_D73B0:
db 00h,00h
word_D73B2:
db 00h,00h
word_D73B4:
db 00h,00h
word_D73B6:
db 00h,00h
word_D73B8:
db 00h,00h
word_D73BA:
db 00h,00h
word_D73BC:
db 00h,00h
word_D73BE:
db 00h,00h
word_D73C0:
db 00h,00h
word_D73C2:
db 00h,00h
word_D73C4:
db 00h,00h
word_D73C6:
db 00h,00h
word_D73C8:
db 00h,00h
word_D73CA:
db 00h,00h
word_D73CC:
db 00h,00h
word_D73CE:
db 00h,00h
word_D73D0:
db 00h,00h
word_D73D2:
db 00h,00h
word_D73D4:
db 00h,00h
word_D73D6:
db 00h,00h
word_D73D8:
db 00h,00h
word_D73DA:
db 00h,00h
word_D73DC:
db 00h,00h
word_D73DE:
db 00h,00h
word_D73E0:
db 00h,00h
word_D73E2:
db 00h,00h
word_D73E4:
db 00h,00h
word_D73E6:
db 00h,00h
word_D73E8:
db 00h,00h
word_D73EA:
db 00h,00h
word_D73EC:
db 00h,00h
word_D73EE:
db 00h,00h
word_D73F0:
db 00h,00h
word_D73F2:
db 00h,00h
word_D73F4:
db 00h,00h
word_D73F6:
db 00h,00h
word_D73F8:
db 00h,00h
word_D73FA:
db 00h,00h
word_D73FC:
db 00h,00h
word_D73FE:
db 00h,00h
word_D7400:
db 00h,00h
word_D7402:
db 00h,00h
word_D7404:
db 00h,00h
word_D7406:
db 00h,00h
word_D7408:
db 00h,00h
word_D740A:
db 00h,00h
word_D740C:
db 00h,00h
word_D740E:
db 00h,00h
word_D7410:
db 00h,00h
word_D7412:
db 00h,00h
word_D7414:
db 0DEh,0DEh,0EBh,0DEh,0F3h,0DEh,0F8h,0DEh,0FBh,0DEh,0FDh,0DEh,0FEh,0DEh,0FFh,0DEh
db 01h,0DEh,02h,0DEh,03h,0DEh,05h,0DEh,08h,0DEh,0Dh,0DEh,015h,0DEh,022h,0DEh
db 0DEh,0EBh,0EBh,0EBh,0F3h,0EBh,0F8h,0EBh,0FBh,0EBh,0FDh,0EBh,0FEh,0EBh,0FFh,0EBh
db 01h,0EBh,02h,0EBh,03h,0EBh,05h,0EBh,08h,0EBh,0Dh,0EBh,015h,0EBh,022h,0EBh
db 0DEh,0F3h,0EBh,0F3h,0F3h,0F3h,0F8h,0F3h,0FBh,0F3h,0FDh,0F3h,0FEh,0F3h,0FFh,0F3h
db 01h,0F3h,02h,0F3h,03h,0F3h,05h,0F3h,08h,0F3h,0Dh,0F3h,015h,0F3h,022h,0F3h
db 0DEh,0F8h,0EBh,0F8h,0F3h,0F8h,0F8h,0F8h,0FBh,0F8h,0FDh,0F8h,0FEh,0F8h,0FFh,0F8h
db 01h,0F8h,02h,0F8h,03h,0F8h,05h,0F8h,08h,0F8h,0Dh,0F8h,015h,0F8h,022h,0F8h
db 0DEh,0FBh,0EBh,0FBh,0F3h,0FBh,0F8h,0FBh,0FBh,0FBh,0FDh,0FBh,0FEh,0FBh,0FFh,0FBh
db 01h,0FBh,02h,0FBh,03h,0FBh,05h,0FBh,08h,0FBh,0Dh,0FBh,015h,0FBh,022h,0FBh
db 0DEh,0FDh,0EBh,0FDh,0F3h,0FDh,0F8h,0FDh,0FBh,0FDh,0FDh,0FDh,0FEh,0FDh,0FFh,0FDh
db 01h,0FDh,02h,0FDh,03h,0FDh,05h,0FDh,08h,0FDh,0Dh,0FDh,015h,0FDh,022h,0FDh
db 0DEh,0FEh,0EBh,0FEh,0F3h,0FEh,0F8h,0FEh,0FBh,0FEh,0FDh,0FEh,0FEh,0FEh,0FFh,0FEh
db 01h,0FEh,02h,0FEh,03h,0FEh,05h,0FEh,08h,0FEh,0Dh,0FEh,015h,0FEh,022h,0FEh
db 0DEh,0FFh,0EBh,0FFh,0F3h,0FFh,0F8h,0FFh,0FBh,0FFh,0FDh,0FFh,0FEh,0FFh,0FFh,0FFh
db 01h,0FFh,02h,0FFh,03h,0FFh,05h,0FFh,08h,0FFh,0Dh,0FFh,015h,0FFh,022h,0FFh
db 0DEh,01h,0EBh,01h,0F3h,01h,0F8h,01h,0FBh,01h,0FDh,01h,0FEh,01h,0FFh,01h
db 01h,01h,02h,01h,03h,01h,05h,01h,08h,01h,0Dh,01h,015h,01h,022h,01h
db 0DEh,02h,0EBh,02h,0F3h,02h,0F8h,02h,0FBh,02h,0FDh,02h,0FEh,02h,0FFh,02h
db 01h,02h,02h,02h,03h,02h,05h,02h,08h,02h,0Dh,02h,015h,02h,022h,02h
db 0DEh,03h,0EBh,03h,0F3h,03h,0F8h,03h,0FBh,03h,0FDh,03h,0FEh,03h,0FFh,03h
db 01h,03h,02h,03h,03h,03h,05h,03h,08h,03h,0Dh,03h,015h,03h,022h,03h
db 0DEh,05h,0EBh,05h,0F3h,05h,0F8h,05h,0FBh,05h,0FDh,05h,0FEh,05h,0FFh,05h
db 01h,05h,02h,05h,03h,05h,05h,05h,08h,05h,0Dh,05h,015h,05h,022h,05h
db 0DEh,08h,0EBh,08h,0F3h,08h,0F8h,08h,0FBh,08h,0FDh,08h,0FEh,08h,0FFh,08h
db 01h,08h,02h,08h,03h,08h,05h,08h,08h,08h,0Dh,08h,015h,08h,022h,08h
db 0DEh,0Dh,0EBh,0Dh,0F3h,0Dh,0F8h,0Dh,0FBh,0Dh,0FDh,0Dh,0FEh,0Dh,0FFh,0Dh
db 01h,0Dh,02h,0Dh,03h,0Dh,05h,0Dh,08h,0Dh,0Dh,0Dh,015h,0Dh,022h,0Dh
db 0DEh,015h,0EBh,015h,0F3h,015h,0F8h,015h,0FBh,015h,0FDh,015h,0FEh,015h,0FFh,015h
db 01h,015h,02h,015h,03h,015h,05h,015h,08h,015h,0Dh,015h,015h,015h,022h,015h
db 0DEh,022h,0EBh,022h,0F3h,022h,0F8h,022h,0FBh,022h,0FDh,022h,0FEh,022h,0FFh,022h
db 01h,022h,02h,022h,03h,022h,05h,022h,08h,022h,0Dh,022h,015h,022h,022h,022h
dword_D7614:
db 00h,00h,00h,00h
byte_D7618:
db 00h
byte_D7619:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,01h,02h,03h,04h,05h,06h,07h,08h,09h,0Ah,0Bh,0Ch
db 0Dh,0Eh,0Fh,010h,011h,012h,013h,014h,015h,016h,017h,018h,019h,01Ah,01Bh,01Ch
db 01Dh,01Eh,01Fh,020h,021h,022h,023h,024h,025h,026h,027h,028h,029h,02Ah,02Bh,02Ch
db 02Dh,02Eh,02Fh,030h,031h,032h,033h,034h,035h,036h,037h,038h,039h,03Ah,03Bh,03Ch
db 03Dh,03Eh,03Fh,040h,041h,042h,043h,044h,045h,046h,047h,048h,049h,04Ah,04Bh,04Ch
db 04Dh,04Eh,04Fh,050h,051h,052h,053h,054h,055h,056h,057h,058h,059h,05Ah,05Bh,05Ch
db 05Dh,05Eh,05Fh,060h,061h,062h,063h,064h,065h,066h,067h,068h,069h,06Ah,06Bh,06Ch
db 06Dh,06Eh,06Fh,070h,071h,072h,073h,074h,075h,076h,077h,078h,079h,07Ah,07Bh,07Ch
db 07Dh,07Eh,07Fh
byte_D781C:
db 080h,081h,082h,083h,084h,085h,086h,087h,088h,089h,08Ah,08Bh,08Ch,08Dh,08Eh,08Fh
db 090h,091h,092h,093h,094h,095h,096h,097h,098h,099h,09Ah,09Bh,09Ch,09Dh,09Eh,09Fh
db 0A0h,0A1h,0A2h,0A3h,0A4h,0A5h,0A6h,0A7h,0A8h,0A9h,0AAh,0ABh,0ACh,0ADh,0AEh,0AFh
db 0B0h,0B1h,0B2h,0B3h,0B4h,0B5h,0B6h,0B7h,0B8h,0B9h,0BAh,0BBh,0BCh,0BDh,0BEh,0BFh
db 0C0h,0C1h,0C2h,0C3h,0C4h,0C5h,0C6h,0C7h,0C8h,0C9h,0CAh,0CBh,0CCh,0CDh,0CEh,0CFh
db 0D0h,0D1h,0D2h,0D3h,0D4h,0D5h,0D6h,0D7h,0D8h,0D9h,0DAh,0DBh,0DCh,0DDh,0DEh,0DFh
db 0E0h,0E1h,0E2h,0E3h,0E4h,0E5h,0E6h,0E7h,0E8h,0E9h,0EAh,0EBh,0ECh,0EDh,0EEh,0EFh
db 0F0h,0F1h,0F2h,0F3h,0F4h,0F5h,0F6h,0F7h,0F8h,0F9h,0FAh,0FBh,0FCh,0FDh,0FEh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
db 00h,00h
dword_D7A1E:
db 00h,00h,00h,00h
dword_D7A22:
db 00h,00h,00h,00h,00h,00h
dword_D7A28:
db 00h,00h,00h,00h
byte_D7A2C:
db 00h,00h,01h,03h,00h,02h,00h,04h,00h,00h,00h,05h,06h,00h,00h,07h
byte_D7A3C:
db 00h,081h,091h,09Bh,0A1h,0A6h,0ABh,0AEh,0B1h,0B4h,0B6h,0B9h,0BBh,0BCh,0BEh,0C0h
db 0C1h,0C3h,0C4h,0C5h,0C6h,0C7h,0C9h,0CAh,0CBh,0CBh,0CCh,0CDh,0CEh,0CFh,0D0h,0D0h
db 0D1h,0D2h,0D3h,0D3h,0D4h,0D5h,0D5h,0D6h,0D6h,0D7h,0D7h,0D8h,0D9h,0D9h,0DAh,0DAh
db 0DBh,0DBh,0DBh,0DCh,0DCh,0DDh,0DDh,0DEh,0DEh,0DEh,0DFh,0DFh,0E0h,0E0h,0E0h,0E1h
db 0E1h,0E2h,0E3h,0E4h,0E5h,0E6h,0E7h,0E7h,0E8h,0E9h,0EAh,0EAh,0EBh,0ECh,0ECh,0EDh
db 0EEh,0EEh,0EFh,0EFh,0F0h,0F1h,0F1h,0F2h,0F2h,0F3h,0F3h,0F4h,0F4h,0F4h,0F5h,0F5h
db 0F6h,0F6h,0F7h,0F7h,0F7h,0F8h,0F8h,0F9h,0F9h,0F9h,0FAh,0FAh,0FAh,0FBh,0FBh,0FBh
db 0FCh,0FCh,0FCh,0FDh,0FDh,0FDh,0FEh,0FEh,0FEh,0FEh,0FFh,0FFh,0FFh,0FFh,0FFh,0FFh
dword_D7ABC:
db 00h,04h,00h,00h,03Dh,04h,00h,00h,07Dh,04h,00h,00h,0C2h,04h,00h,00h
db 0Ah,05h,00h,00h,057h,05h,00h,00h,0A8h,05h,00h,00h,0FEh,05h,00h,00h
db 059h,06h,00h,00h,0BAh,06h,00h,00h,021h,07h,00h,00h,08Dh,07h,00h,00h
byte_D7AEC:
db 01h,00h,00h,00h
dword_D7AF0:
db 00h,00h,00h,00h
dword_D7AF4:
db 00h,00h,00h,00h
dword_D7AF8:
db 00h,00h,00h,00h
dword_D7AFC:
db 00h,00h,00h,00h
dword_D7B00:
db 00h,00h,00h,00h
dword_D7B04:
db 00h,00h,00h,00h
dword_D7B08:
db 00h,00h,00h,00h
dword_D7B0C:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
byte_D7B18:
db 00h,00h,00h,00h
dword_D7B1C:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h
dword_D7B30:
db 00h,00h,00h,00h
dword_D7B34:
db 00h,00h,00h,00h
dword_D7B38:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D7B44:
db 00h,00h,00h,00h
dword_D7B48:
db 00h,00h,00h,00h
dword_D7B4C:
db 00h,00h,00h,00h
dword_D7B50:
db 00h,00h,00h,00h,00h,00h,00h,00h
byte_D7B58:
db 00h,00h,00h,00h
byte_D7B5C:
db 00h,00h,00h,00h
dword_D7B60:
db 00h,00h,00h,00h
word_D7B64:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D7D64:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
byte_D7D70:
db 00h,00h,00h,00h
dword_D7D74:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h
dword_D7D88:
db 00h,00h,00h,00h
dword_D7D8C:
db 00h,00h,00h,00h
dword_D7D90:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D7D9C:
db 00h,00h,00h,00h
dword_D7DA0:
db 00h,00h,00h,00h
dword_D7DA4:
db 00h,00h,00h,00h
dword_D7DA8:
db 00h,00h,00h,00h,00h,00h,00h,00h
byte_D7DB0:
db 00h,00h,00h,00h
byte_D7DB4:
db 00h,00h,00h,00h
dword_D7DB8:
db 00h,00h,00h,00h
word_D7DBC:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D7FBC:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
byte_D7FC8:
db 00h,00h,00h,00h
dword_D7FCC:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h
dword_D7FE0:
db 00h,00h,00h,00h
dword_D7FE4:
db 00h,00h,00h,00h
dword_D7FE8:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D7FF4:
db 00h,00h,00h,00h
dword_D7FF8:
db 00h,00h,00h,00h
dword_D7FFC:
db 00h,00h,00h,00h
dword_D8000:
db 00h,00h,00h,00h,00h,00h,00h,00h
byte_D8008:
db 00h,00h,00h,00h
byte_D800C:
db 00h,00h,00h,00h
dword_D8010:
db 00h,00h,00h,00h
word_D8014:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D8214:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
byte_D8220:
db 00h,00h,00h,00h
dword_D8224:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h
dword_D8238:
db 00h,00h,00h,00h
dword_D823C:
db 00h,00h,00h,00h
dword_D8240:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D824C:
db 00h,00h,00h,00h
dword_D8250:
db 00h,00h,00h,00h
dword_D8254:
db 00h,00h,00h,00h
dword_D8258:
db 00h,00h,00h,00h,00h,00h,00h,00h
byte_D8260:
db 00h,00h,00h,00h
byte_D8264:
db 00h,00h,00h,00h
dword_D8268:
db 00h,00h,00h,00h
word_D826C:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
off_D846C:
dd dword_D7B0C
dd dword_D7D64
dd dword_D7FBC
dd dword_D8214
dword_D847C:
db 00h,00h,00h,00h
dword_D8480:
db 00h,00h,00h,00h
dword_D8484:
db 00h,00h,00h,00h
dword_D8488:
db 00h,00h,00h,00h
dword_D848C:
db 00h,00h,00h,00h
dword_D8490:
db 00h,00h,00h,00h
dword_D8494:
db 00h,00h,00h,00h
dword_D8498:
db 00h,00h,00h,00h
byte_D849C:
db 00h,00h,00h,00h
byte_D84A0:
db 00h,00h,00h,00h,022h,056h,00h,00h
dword_D84A8:
db 00h,00h,00h,00h
dword_D84AC:
db 00h,00h,00h,00h
dword_D84B0:
db 00h,00h,00h,00h
dword_D84B4:
db 00h,00h,00h,00h
dword_D84B8:
db 00h,00h,00h,00h
word_D84BC:
db 00h,00h
word_D84BE:
db 00h,00h
dword_D84C0:
db 00h,00h
word_D84C2:
db 00h,00h
dword_D84C4:
db 00h,00h
word_D84C6:
db 00h,00h,00h,080h,0Bh,00h
dword_D84CC:
dd unk_C4B50
dword_D84D0:
db 02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h
db 02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h
db 02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h
db 02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h,02h,00h,00h,00h
dword_D8510:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D8550:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D8590:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
dword_D85D0:
db 064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h
db 064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h
db 064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h
db 064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h,064h,00h,00h,00h
dword_D8610:
db 07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h
db 07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h
db 07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h
db 07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h,07Fh,00h,00h,00h
db 010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h
db 010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h
db 010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h
db 010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h,010h,00h,00h,00h
dword_D8690:
db 00h,00h,00h,00h
word_D8694:
db 00h,00h
dword_D8696:
db 00h,00h,00h,00h
word_D869A:
db 00h,00h
dword_D869C:
db 00h,00h,00h,00h
word_D86A0:
db 00h,00h
dword_D86A2:
db 00h,00h,00h,00h
word_D86A6:
db 00h,00h
dword_D86A8:
db 00h,00h,00h,00h
dword_D86AC:
db 00h,00h,00h,00h
dword_D86B0:
db 00h,00h,00h,00h
word_D86B4:
db 00h,00h
word_D86B6:
db 00h,00h
dword_D86B8:
db 00h,00h,00h,00h
dword_D86BC:
db 00h,00h,00h,00h
dword_D86C0:
db 011h,00h,00h,00h,00h,00h,00h,00h
byte_D86C8:
db 087h,00h,083h,00h,081h,00h,082h,00h,08Fh,00h,08Bh,00h,089h,00h,08Ah,00h
db 00h,00h
word_D86DA:
db 08h,00h
dword_D86DC:
db 00h,00h,00h,00h
word_D86E0:
db 00h,00h,09h,00h,00h,00h,00h,00h,00h,00h,0Ah,00h,00h,00h,00h,00h
db 00h,00h,0Bh,00h,00h,00h,00h,00h,00h,00h,0Ch,00h,00h,00h,00h,00h
db 00h,00h,0Dh,00h,00h,00h,00h,00h,00h,00h,0Eh,00h,00h,00h,00h,00h
db 00h,00h,0Fh,00h,00h,00h,00h,00h,00h,00h,070h,00h,00h,00h,00h,00h
db 00h,00h,071h,00h,00h,00h,00h,00h,00h,00h,072h,00h,00h,00h,00h,00h
db 00h,00h,073h,00h,00h,00h,00h,00h,00h,00h,074h,00h,00h,00h,00h,00h
db 00h,00h,075h,00h,00h,00h,00h,00h,00h,00h,076h,00h,00h,00h,00h,00h
db 00h,00h,077h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
word_D8760:
db 020h,02h
word_D8762:
db 026h,02h
word_D8764:
db 028h,02h
word_D8766:
db 029h,02h
word_D8768:
db 02Bh,02h
word_D876A:
db 02Fh,02h
word_D876C:
db 020h,03h
word_D876E:
db 021h,03h
word_D8770:
db 022h,03h
word_D8772:
db 023h,03h
word_D8774:
db 024h,03h
word_D8776:
db 025h,03h
word_D8778:
db 027h,03h
byte_D877A:
db 00h,01h,00h,02h,00h,03h,04h,05h,00h,00h
dword_D8784:
db 01h,00h,00h,00h
word_D8788:
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
db 00h,00h,00h,00h,00h,00h,00h,00h
dword_D87A0:
db 00h,00h,00h,00h,00h,00h,00h,00h
dword_D87A8:
db 00h,00h,00h,00h
dword_D87AC:
db 00h,00h,00h,00h
dword_D87B0:
db 00h,00h,00h,00h
dword_D87B4:
db 00h,00h,00h,00h
dword_D87B8:
db 00h,00h,00h,00h
dword_D87BC:
db 00h,00h,00h,00h
dword_D87C0:
db 00h,00h,00h,00h
dword_D87C4:
db 00h,00h,00h,00h
dword_D87C8:
db 00h,00h,00h,00h
dword_D87CC:
db 00h,00h,00h,00h
dword_D87D0:
db 00h,00h,00h,00h
dword_D87D4:
db 00h,00h,00h,00h
byte_D87D8:
db 00h,00h,00h,00h
dword_D87DC:
db 0EFh,01Fh,00h,00h
dword_D87E0:
db 0D5h,021h,00h,00h,0D9h,023h,00h,00h,0FAh,025h,00h,00h,03Ch,028h,00h,00h
db 0A1h,02Ah,00h,00h,02Ah,02Dh,00h,00h,0D9h,02Fh,00h,00h,0B2h,032h,00h,00h
db 0B6h,035h,00h,00h,0E7h,038h,00h,00h,049h,03Ch,00h,00h,0DFh,03Fh,00h,00h
db 0ABh,043h,00h,00h,0B2h,047h,00h,00h,0F5h,04Bh,00h,00h,079h,050h,00h,00h
db 042h,055h,00h,00h,054h,05Ah,00h,00h,0B3h,05Fh,00h,00h,064h,065h,00h,00h
db 06Ch,06Bh,00h,00h,0CFh,071h,00h,00h,093h,078h,00h,00h,0BFh,07Fh,00h,00h
db 057h,087h,00h,00h,064h,08Fh,00h,00h,0EAh,097h,00h,00h,0F3h,0A0h,00h,00h
db 085h,0AAh,00h,00h,0A9h,0B4h,00h,00h,067h,0BFh,00h,00h,0C9h,0CAh,00h,00h
db 0D8h,0D6h,00h,00h,09Eh,0E3h,00h,00h,027h,0F1h,00h,00h,07Eh,0FFh,00h,00h
db 0AFh,0Eh,01h,00h,0C8h,01Eh,01h,00h,0D5h,02Fh,01h,00h,0E6h,041h,01h,00h
db 0Bh,055h,01h,00h,052h,069h,01h,00h,0CEh,07Eh,01h,00h,092h,095h,01h,00h
db 0B0h,0ADh,01h,00h,03Ch,0C7h,01h,00h,04Eh,0E2h,01h,00h,0FCh,0FEh,01h,00h
db 05Fh,01Dh,02h,00h,090h,03Dh,02h,00h,0ABh,05Fh,02h,00h,0CDh,083h,02h,00h
db 016h,0AAh,02h,00h,0A5h,0D2h,02h,00h,09Dh,0FDh,02h,00h,024h,02Bh,03h,00h
db 060h,05Bh,03h,00h,079h,08Eh,03h,00h,09Dh,0C4h,03h,00h,0F9h,0FDh,03h,00h
db 0BEh,03Ah,04h,00h,020h,07Bh,04h,00h,056h,0BFh,04h,00h,09Bh,07h,05h,00h
db 02Ch,054h,05h,00h,04Ah,0A5h,05h,00h,03Bh,0FBh,05h,00h,048h,056h,06h,00h
db 0C0h,0B6h,06h,00h,0F3h,01Ch,07h,00h,03Bh,089h,07h,00h,0F3h,0FBh,07h,00h
db 07Dh,075h,08h,00h,041h,0F6h,08h,00h,0ADh,07Eh,09h,00h,037h,0Fh,0Ah,00h
db 058h,0A8h,0Ah,00h,094h,04Ah,0Bh,00h,076h,0F6h,0Bh,00h,091h,0ACh,0Ch,00h
db 080h,06Dh,0Dh,00h,0E7h,039h,0Eh,00h,076h,012h,0Fh,00h,0E6h,0F7h,0Fh,00h
db 0FAh,0EAh,010h,00h,083h,0ECh,011h,00h,05Bh,0FDh,012h,00h,06Eh,01Eh,014h,00h
db 0B0h,050h,015h,00h,029h,095h,016h,00h,0EDh,0ECh,017h,00h,022h,059h,019h,00h
db 00h,0DBh,01Ah,00h,0CFh,073h,01Ch,00h,0EDh,024h,01Eh,00h,0CCh,0EFh,01Fh,00h
db 0F5h,0D5h,021h,00h,06h,0D9h,023h,00h,0B7h,0FAh,025h,00h,0DCh,03Ch,028h,00h
db 061h,0A1h,02Ah,00h,053h,02Ah,02Dh,00h,0DBh,0D9h,02Fh,00h,045h,0B2h,032h,00h
db 00h,0B6h,035h,00h,09Eh,0E7h,038h,00h,0DAh,049h,03Ch,00h,099h,0DFh,03Fh,00h
db 0EAh,0ABh,043h,00h,0Ch,0B2h,047h,00h,06Fh,0F5h,04Bh,00h,0B8h,079h,050h,00h
db 0C3h,042h,055h,00h,0A6h,054h,05Ah,00h,0B6h,0B3h,05Fh,00h,08Bh,064h,065h,00h
db 00h,06Ch,06Bh,00h,03Ch,0CFh,071h,00h,0B4h,093h,078h,00h,032h,0BFh,07Fh,00h
db 0D4h,057h,087h,00h,018h,064h,08Fh,00h,0DFh,0EAh,097h,00h,071h,0F3h,0A0h,00h
db 087h,085h,0AAh,00h,04Dh,0A9h,0B4h,00h
dword_D89D8:
db 00h,00h,00h,00h
dword_D89DC:
db 01h,00h,00h,00h
byte_D89E0:
db 00h,00h,00h,00h
