; data_season95_79 DC7BC-DC834  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "x86enc.inc"
section s_DC7BC nobits alloc noexec write align=1
global dword_DC7BC, dword_DC830
dword_DC7BC:
resb 116
dword_DC830:
resb 4
