; data_engine_81 DEB78-DF00C  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_DEB78 nobits alloc noexec write align=1
global byte_DEE97, dword_DEB78, dword_DEB7C, dword_DEB80, dword_DEF8C, dword_DEFE0, dword_DF004, word_DEE94
global word_DEE96, word_DEF84, word_DEF88
dword_DEB78:
resb 4
dword_DEB7C:
resb 4
dword_DEB80:
resb 788
word_DEE94:
resb 2
word_DEE96:
resb 1
byte_DEE97:
resb 237
word_DEF84:
resb 4
word_DEF88:
resb 4
dword_DEF8C:
resb 84
dword_DEFE0:
resb 36
dword_DF004:
resb 8
