; data_frontend_82 DF00C-DF63E  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_DF00C nobits alloc noexec write align=1
global dword_DF00C, dword_DF010, hmtmstruct, dword_DF61A
global dword_DF626, dword_DF62A, dword_DF636
global unk_DF014, unk_DF314, word_DF618, hmscore
dword_DF00C:
resb 4
dword_DF010:
resb 4
unk_DF014:
resb 768
unk_DF314:
resb 766
resb 2
hmtmstruct:
resb 2
resb 2
word_DF618:
resb 2
dword_DF61A:
resb 2
resb 2
resb 2
resb 2
resb 2
hmscore:
resb 2
dword_DF626:
resb 4
dword_DF62A:
resb 12
dword_DF636:
resb 2
resb 2
resb 2
resb 2
