; data_frontend_89 EA0DC-EA994  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_EA0DC nobits alloc noexec write align=1
global byte_EA0F4, byte_EA0FC, byte_EA0FD, byte_EA2A4, byte_EA2A5, byte_EA990, byte_EA991, byte_EA992
global byte_EA993, dword_EA0DC, dword_EA0F8, dword_EA101, dword_EA298, dword_EA29C, dword_EA2A0, dword_EA2A9
global dword_EA2B0, dword_EA2B4, dword_EA988, unk_EA968
dword_EA0DC:
resb 24
byte_EA0F4:
resb 4
dword_EA0F8:
resb 4
byte_EA0FC:
resb 1
byte_EA0FD:
resb 4
dword_EA101:
resb 407
dword_EA298:
resb 4
dword_EA29C:
resb 4
dword_EA2A0:
resb 4
byte_EA2A4:
resb 1
byte_EA2A5:
resb 4
dword_EA2A9:
resb 7
dword_EA2B0:
resb 4
dword_EA2B4:
resb 1716
unk_EA968:
resb 32
dword_EA988:
resb 8
byte_EA990:
resb 1
byte_EA991:
resb 1
byte_EA992:
resb 1
byte_EA993:
resb 1
