; data_ealib_103 F6138-F7978  NHL 95 PC HOCKEY.EXE dseg02; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_F6138 nobits alloc noexec write align=1
global dword_F6138
dword_F6138:
resb 6208
