#!/usr/bin/env python3
"""gen_cheaders.py - generate the C headers for matching decompilation from the asm tree.

  python3 tools/gen_cheaders.py          (after `make`: reads build/obj/**.o for label addresses)

Writes (all generated, do not edit; put hand-written declarations in the manual headers listed below):
  src/c/include/structs.h   struct Player / struct Team from src/inc/structs.inc (field names = the asm equates;
                            gaps become pad bytes). C type per field: 'size'/'tsize' tag (b/w/d) + CTYPE overrides.
  src/c/include/globals.h   extern declaration for every data label in dseg02 not declared in a manual header.
                            Type from how the asm accesses it (byte/word/dword operands, movsx/movzx, the -5r
                            short loads dword [x-2]/sar 10h and dword [x-3]/sar 18h); '[]' if it is ever indexed or
                            accessed at an offset. Unknown -> 'unsigned char x[]'.
  src/c/include/asmfuncs.h  'extern void Name();' (unprototyped; Watcom still passes register arguments) for every
                            code label in cseg01 not prototyped in a manual header.
Manual headers (scanned for names so the generated ones skip them): protos.h (function prototypes: every matched C
function and any known signature), vars.h (typed globals, overriding the inferred type).
The asm label is the C name: wcc386 decorates functions as Name_ and data as _Name, tools/cobj.py undoes that."""
import os, re, sys, glob
from collections import defaultdict, Counter
HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
from link_src import read_elf
INC = os.path.join(ROOT, 'src/c/include')
CKEYWORDS = set('auto break case char const continue default do double else enum extern float for goto if int long '
                'register return short signed sizeof static struct switch typedef union unsigned void volatile while '
                'main near far huge interrupt cdecl pascal fortran syscall'.split())
# C type overrides for struct fields (name -> type); default from the size tag
CTYPE = {'legstr': 'unsigned char',   # StopNA: xor ebx,ebx / mov bl,[eax+legstr]
         'tmptr': 'struct Team *', 'optmptr': 'struct Team *', 'tmsort': 'struct Player *',
         'tmroster': 'unsigned char *', 'tmlines': 'unsigned char *', 'tmplstats': 'short *', 'tmglstats': 'short *'}
TYPES = {'b': 'signed char', 'w': 'short', 'd': 'int'}
SIZES = {'b': 1, 'w': 2, 'd': 4}
STRUCTS = (('Player', 'size', 0x80, 'player structure (93G SortCords player block), 80h bytes; pointer usually in eax/ecx/esi/edi'),
           ('Team', 'tsize', 0x100, 'team structure (93G hmtmstruct/awtmstruct; home DF614, away DF714), 100h bytes'))

def labels():
    """{name: (addr, 'cseg01'|'dseg02', is_global)} from the assembled objects"""
    out = {}
    for p in glob.glob(os.path.join(ROOT, 'build/obj/*/*.o')):
        d, secs, syms, rels = read_elf(p)
        kind = p.split('/')[-2]
        for i, s in enumerate(secs):
            if s['name'].startswith('s_'): base = int(s['name'][2:], 16); si = i
        for sy in syms:
            if sy['shndx'] == si and sy['type'] in (0, 1, 2) and sy['name'] and not sy['name'].startswith('s_'):
                out[sy['name']] = (base + sy['value'], kind, sy['bind'] == 1)
    return out

def manual_names():
    names = set()
    for f in ('protos.h', 'vars.h'):
        p = os.path.join(INC, f)
        if not os.path.exists(p): continue
        t = re.sub(r'/\*.*?\*/', '', open(p).read(), flags=re.S); t = re.sub(r'//.*', '', t)
        for m in re.finditer(r'\b([A-Za-z_]\w*)\s*(?:\[[^\]]*\]\s*)*(?:;|\(|,|=)', t): names.add(m.group(1))
    return names

def gen_structs():
    fields = defaultdict(list)
    for ln in open(os.path.join(ROOT, 'src/inc/structs.inc')):
        m = re.match(r'^(\w+)\s+equ\s+([0-9A-Fa-f]+)h\s*;\s*(t?size) (b|w|d)( array)?;?\s*(.*)', ln)
        if not m: continue
        name, off, tag, sz, arr, cmt = m.groups()
        arr = arr or cmt.startswith('93G') and ' byte array' in cmt[:60]
        fields[tag].append((int(off, 16), name, sz, bool(arr), cmt.strip()))
    out = ['/* NHL 95 PC structures for the C sources. GENERATED by tools/gen_cheaders.py from src/inc/structs.inc:',
           '   edit structs.inc (and tools/struct_fieldmap.csv), then re-run the tool. Field names are the asm equates.',
           '   Packed (-zp1 is the wcc386 10.0 default), so the offsets are exact. */',
           '#ifndef STRUCTS_H', '#define STRUCTS_H', '']
    for sname, tag, size, doc in STRUCTS:
        fl = sorted(fields[tag]); pos = 0; body = []
        for i, (off, name, sz, arr, cmt) in enumerate(fl):
            if off < pos: body.append('    /* %-10s %03Xh overlaps the previous field: use the offset macro */' % (name, off)); continue
            if off > pos: body.append('    unsigned char pad_%02X[0x%X];' % (pos, off - pos))
            ty = CTYPE.get(name, TYPES[sz]); n = SIZES[sz]
            if arr:
                nxt = next((o for o, *_ in fl[i + 1:] if o > off), size); cnt = (nxt - off) // n
                decl = '%s %s[%d];' % (ty, name, cnt); n *= cnt
            else: decl = '%s %s;' % (ty, name)
            c = cmt.replace('*/', '* /')
            body.append('    %-28s /* %03Xh %s */' % (decl, off, c[:150]))
            pos = off + n
        if pos < size: body.append('    unsigned char pad_%02X[0x%X];' % (pos, size - pos))
        out += ['/* %s */' % doc, 'typedef struct %s {' % sname] + body + ['} %s;' % sname, '']
        for off, name, sz, arr, cmt in fl: out.append('#define OFS_%s_%s 0x%02X' % (sname, name, off))
        out.append('')
    out.append('#endif')
    open(os.path.join(INC, 'structs.h'), 'w').write('\n'.join(out) + '\n')

def access_stats(lab):
    """per label: Counter of (width, signed?) for exact accesses, and whether indexed/offset"""
    st = defaultdict(Counter); arr = set()
    tok = re.compile(r'\b([A-Za-z_][\w$?@]*)\b')
    for f in glob.glob(os.path.join(ROOT, 'src/cseg01/*.asm')):
        prev = None
        for ln in open(f):
            s = ln.split(';')[0].strip()
            if not s or s.endswith(':'): continue
            for m in re.finditer(r'(byte|word|dword) \[([^\]]+)\]', s):
                w, inner = m.groups(); inner = inner.replace('nosplit ', '').replace('dword ', '').replace('byte ', '')
                names = [t for t in tok.findall(inner) if t in lab and lab[t][1] == 'dseg02']
                if len(names) != 1: continue
                nm = names[0]
                regs = re.search(r'\b(e?[abcd]x|e?[sd]i|e?bp|esp)\b', inner)
                offm = re.search(re.escape(nm) + r'\s*([+-]\s*(?:0[0-9A-F]*h|\d+))', inner)
                off = int(offm.group(1).replace(' ', '').rstrip('h'), 16) if offm else 0
                if regs: arr.add(nm)
                op = s.split()[0]
                sgn = 's' if op == 'movsx' else 'u' if op == 'movzx' else '?'
                if w == 'dword' and off in (-2, -3) and not regs:
                    st[nm][('w' if off == -2 else 'b', 's')] += 3; continue
                if off: arr.add(nm); continue
                st[nm][(w[0] if w != 'dword' else 'd', sgn)] += 1
    return st, arr

def gen_globals(lab, skip):
    st, arr = access_stats(lab)
    out = ['/* extern declarations for the NHL 95 PC data labels. GENERATED by tools/gen_cheaders.py (do not edit):',
           '   the type is inferred from the asm accesses. To give a variable a better type, declare it in vars.h and',
           '   re-run the tool (names declared there are skipped here). Sorted by address. */',
           '#ifndef GLOBALS_H', '#define GLOBALS_H', '']
    for nm, (a, kind, g) in sorted(lab.items(), key=lambda x: x[1][0]):
        if kind != 'dseg02' or nm in skip or nm in CKEYWORDS or not re.match(r'^[A-Za-z_]\w*$', nm) or '.' in nm: continue
        c = st.get(nm)
        if c:
            ws = Counter()
            for (w, s), n in c.items(): ws[w] += n
            w = ws.most_common(1)[0][0]
            ss = Counter({s: n for (ww, s), n in c.items() if ww == w and s != '?'})
            sg = ss.most_common(1)[0][0] if ss else ('u' if w == 'b' else 's')
            ty = {('b', 's'): 'signed char', ('b', 'u'): 'unsigned char', ('w', 's'): 'short', ('w', 'u'): 'unsigned short',
                  ('d', 's'): 'int', ('d', 'u'): 'int'}[(w, sg)]
            dim = '[]' if nm in arr else ''
        else:
            pre = nm.split('_')[0]
            ty = {'byte': 'unsigned char', 'word': 'short', 'dword': 'int'}.get(pre, 'unsigned char')
            dim = '[]'
        out.append('extern %s %s%s; /* %05X */' % (ty, nm, dim, a))
    out += ['', '#endif']
    open(os.path.join(INC, 'globals.h'), 'w').write('\n'.join(out) + '\n')

def gen_funcs(lab, skip):
    out = ['/* Declarations for the NHL 95 PC code labels. GENERATED by tools/gen_cheaders.py (do not edit).',
           '   Unprototyped on purpose (wcc386 still passes register arguments: eax, edx, ebx, ecx); a function whose',
           '   signature is known belongs in protos.h, which this file skips. Sorted by address. */',
           '#ifndef ASMFUNCS_H', '#define ASMFUNCS_H', '']
    for nm, (a, kind, g) in sorted(lab.items(), key=lambda x: x[1][0]):
        if kind != 'cseg01' or nm in skip or nm in CKEYWORDS or '.' in nm or not re.match(r'^[A-Za-z]\w*$', nm): continue
        if nm.endswith('_'): continue      # Watcom library entry points (strcpy_ ...): declare the C name in protos.h
        out.append('extern void %s(); /* %05X */' % (nm, a))
    out += ['', '#endif']
    open(os.path.join(INC, 'asmfuncs.h'), 'w').write('\n'.join(out) + '\n')

if __name__ == '__main__':
    os.makedirs(INC, exist_ok=True)
    lab = labels()
    if not lab: sys.exit('no build/obj: run make first')
    skip = manual_names()
    gen_structs(); gen_globals(lab, skip); gen_funcs(lab, skip)
    print('wrote structs.h, globals.h, asmfuncs.h (%d labels, %d manual names skipped)' % (len(lab), len(skip)))
