"""Curated segment definitions for HOCKEY.EXE (NHL 95 PC).
CSEG: (start, module, group, description, confidence, nhl94_counterpart)
Starts must be function/item starts in the listing. Ends are implied by the next start.
Inside LIBZONE, runs of Watcom clib functions (FLIRT-collapsed + clib-only helpers) are
split out automatically by build_segmap.py as 'watcom_clib' segments."""
CSEG = [
 (0x10000, 'watcom_begtext', 'watcom', 'Watcom ___begtext: int3/jmp trap + 0Dh NOP pad (start of code)', 'high', ''),
 (0x10010, 'main_startup', 'frontend', 'main_ (disk/memory checks, DPMI DOS-mem probe via int386 31h), keyboard/joystick input mapping, screen helpers', 'high', 'hockey94 Begin (role only)'),
 (0x1167B, 'gamesave_io', 'frontend', 'save-game / .PPV / game.sav / .DB file handling', 'medium', ''),
 (0x12849, 'team_stats_screen', 'frontend', 'team stats tables (GP/Min/GAA/SO/Shots/Pct; ANA Mighty Ducks)', 'medium', 'stats94 (role only)'),
 (0x13320, 'asset_loading', 'frontend', 'palette / screen / HILIGHT / numshp / rink-end overlay (.PPV/.VFN) loaders', 'medium', ''),
 (0x1431E, 'file_utils', 'frontend', 'path building, disk-space checks, gsummary.db', 'medium', ''),
 (0x150C6, 'scoreboard_gfx', 'frontend', 'scoreboard / crest graphics (scrbrd2, srb3, crests4), Stanley Cup text', 'medium', ''),
 (0x1609F, 'title_intro', 'frontend', 'EA / Pioneer / title screens, MVI movie hooks (MVIh/MVIe/MVIf)', 'medium', 'title94 (role only)'),
 (0x17816, 'output_files', 'frontend', 'output file (.OUT) writing, free-space prompts', 'low', ''),
 (0x17DFC, 'palette_fx', 'frontend', '17 near-identical SfPal1/SfPal2 palette fade/cycle routines', 'medium', ''),
 (0x18D7F, 'frontend_desk', 'frontend', 'output file name prompt, EA desk (eadesk), return/exit confirmation dialogs', 'medium', ''),
 (0x1AC25, 'cmv_player', 'eagfx', 'CMV movie playback (cmv mem block / cmv palette)', 'medium', ''),
 (0x1B0F3, 'cdstream', 'eagfx', 'CDSTREAM / SECCDSTREAM chunked stream reader (Illegal chunk size)', 'medium', ''),
 (0x1BBCC, 'key_team_db', 'frontend', 'teams / key.db handling, gsummary', 'low', ''),
 (0x1CC3D, 'frontend_labels', 'frontend', 'scoreboard tiles, season titles, Sports Central menu labels', 'medium', ''),
 (0x1D6E8, 'menu_system', 'frontend', 'menu framework (Pointer / menubuff), season title strings', 'medium', 'menu94 (role only)'),
 (0x20016, 'easn_stats', 'frontend', 'EASN stats screens (embpal, tstat, keys, pstat, gstat)', 'medium', 'stats94 (role only)'),
 (0x21CDE, 'player_stats', 'frontend', 'player stats / portraits / sort (PORTR, pstatbar, addsort, trad)', 'medium', 'stats94 (role only)'),
 (0x27080, 'standings_playoffs', 'frontend', 'standings, conferences, playoff seeding screens', 'medium', ''),
 (0x2970A, 'league_schedule', 'frontend', 'LSSCHED schedule loading/drawing', 'medium', ''),
 (0x29F28, 'arena_logos', 'frontend', 'arena / rink / team logo screens', 'medium', ''),
 (0x2B7B7, 'file_dialogs', 'frontend', 'Open/Delete/Done file dialogs (*.nhl, *.po, *.lp), dialog boxes', 'medium', ''),
 (0x2D35A, 'game_setup', 'frontend', 'pre-game setup / matchup screen (indus030, ctlogo, No Penalties, game.set)', 'medium', ''),
 (0x2FDD1, 'misc_dialogs', 'frontend', 'misc dialog/menu helpers (.DB/.ORG, DBOX)', 'low', ''),
 (0x31AB5, 'main_desk', 'frontend', 'main desk / tonight screen (maindesk, tonights, easndesk), game.set', 'medium', ''),
 (0x32DA9, 'temp_files', 'frontend', 'temp file / palette save/restore', 'low', ''),
 (0x3377C, 'rink_tiles', 'frontend', 'rink .til / TILES loader, CRESTS3', 'medium', ''),
 (0x33FFD, 'calendar', 'frontend', 'league calendar screens (calendar, callogo)', 'medium', ''),
 (0x35FB9, 'import_export', 'frontend', 'import/export, GSUMMARY game summaries', 'medium', ''),
 (0x380E9, 'league_setup', 'frontend', 'league creation, master controller passwords', 'medium', ''),
 (0x3A9AA, 'database_merge', 'frontend', 'player database merge/import/export (PINFO, PLAYER, GAME, SAV)', 'medium', ''),
 (0x3DB41, 'config_cfg', 'frontend', 'nhl.cfg reader', 'medium', ''),
 (0x3DC2C, 'roster_jersey', 'frontend', 'roster / jersey number editing (HOMEPALS)', 'medium', ''),
 (0x40183, 'trades', 'season95', 'trades / human team selection / free agents (Select two teams for trading)', 'medium', 'NEW in 95 (Genesis trade95)'),
 (0x41B80, 'schedule', 'season95', 'season schedule (sche/Sch), human team selection', 'medium', 'NEW in 95 (Genesis trade95 schedule half)'),
 (0x45282, 'options_settings', 'frontend', 'option set screens (pset), load', 'low', 'optsetup94 (role only)'),
 (0x47C31, 'engine_init', 'engine', 'in-game initialisation helpers (large data users)', 'low', 'hockey94/setup94 (role only)'),
 (0x4842A, 'engine_player_logic', 'engine', 'player assignment logic: targets of the asstab-like table at C9161 (36 of 47 entries follow the 93G asstab order (29) + 94G additions (7))', 'medium', 'assign94 / checks94 / onetimer94'),
 (0x4FCE8, 'engine_input', 'engine', 'controller input: input ring buffer (g_inputBufferOffset1/2/3, 50-entry table D8B80), per-frame pad latch from pollMenuInputAndDispatch (50A05/50A84), doinput_ispc (504DA) and its line-change/pass/shot helpers (4FD8E-50434), mouse hook 50ADE', 'medium', '94G input94 doinput_ispc / 93G logic93_1 doinput (role)'),
 (0x50AFE, 'engine_assign_faceoff', 'engine', 'second block of assignment code: assonetimer (50B55), asspassrec, puckfaceoff/puckfaceoff2 + faceoff helpers, asstab slots 39-41/44/45, check4bench', 'medium', 'onetimer94 / logic93_4 puckfaceoff / logic93_1 check4bench'),
 (0x53294, 'engine_physics_ai', 'engine', 'checking / passing / shooting / puck & wall collision physics (burst 532BD, check4check, checkcheck, dopass, passtoa0, FallDown, puckstick/puckglue/puckgoalie, doshot, checkcoll..checkcx), faceoff goalie helpers CPgoalie..593F5', 'medium', 'checks94 / collide94'),
 (0x59493, 'engine_sound_iface', 'engine', 'sound / music / speech trigger wrappers: EACSNDF callbacks 59493/594B2 (called from ea_sound_hl), music start/stop 594CD-59863, sfx 59884, speech/announcer wrappers 59981-59D71', 'medium', 'sound94 sfx/song (role)'),
 (0x59D9A, 'engine_core', 'engine', 'engine core: SetSPA (59D9A), GetHot, setpersonel, DoGameFrame, per-player update (5C40F updateplayers, updateanim), bench/line resets, forcepldata', 'medium', 'hockey94 / checks94 / collide94'),
 (0x5E16D, 'engine_skating', 'engine', 'skating / player movement: doplayeracc 5E16D, skateto 5E93B, skatetopuck 5EB17, playeracc 5EDAD, turn/heading helper 5F151 (shares chunk 5E7F7 with skateto), dostop 5F745, StopNA 5F82A, goalieacc 5F8B2, noturn0 5F98A', 'high', '93G logic93_5 doplayeracc/goalieacc/noturn0/playeracc/dostop/StopNA, skateto/skatetopuck'),
 (0x5FB03, 'game_state_saveload', 'engine', 'in-game state save/load (Error Saving/Loading Game: 5FB03, 60612)', 'high', ''),
 (0x614C2, 'scoring_penalty_text', 'engine', 'goal / assist / penalty summary strings (Penalty shot, served by #%d), AddPenalty/AddPenalty2, Stop4Pen + penalty manager chain 637B5-63BF8, game-event/stat hooks 63D69-64439', 'medium', 'penalty94 / stats94 (role only)'),
 (0x644A8, 'engine_display', 'engine', 'in-game display / overlays: ticker/message 64614-65B48, setInjuryType, checkwindow, .PPV/rink palettes (HOMEPALS), updatereplay + replay helpers', 'low', 'display94 (role only)'),
 (0x688A4, 'debug_dump', 'engine', 'debug state dump to stats.log (puckc, gmclock, gmpen, tmstructs, sortcords)', 'high', ''),
 (0x69336, 'game_frame', 'engine', 'large in-game driver (single 0xCFD-byte function, 56 callees; named StartHL2 by role)', 'low', ''),
 (0x6A033, 'zonemgr', 'eagfx', 'ZONEMGR hidden/background window manager (incl. zone flag/bitmap accessors 6A033-6A0F6 on EA058/EA09C/EA074/EA0AC)', 'medium', ''),
 (0x6B093, 'joystick_calibration', 'frontend', 'joystick calibration screens (LEFT/RIGHT JOYSTICK)', 'high', ''),
 (0x6C2F9, 'database_save', 'frontend', 'save databases, free disk space, Free Agents list', 'medium', ''),
 (0x6D2F8, 'create_player', 'season95', 'player editor: ratings, shoots/glove hand, jersey, free-agent creation', 'medium', 'NEW in 95 (Genesis create95)'),
 (0x71F0C, 'database_dialogs', 'frontend', 'database open/delete dialogs (*.db/*.org/*.dbx)', 'medium', ''),
 (0x737AA, 'line_editor_rosters', 'frontend', 'line editor / rosters (scratch, dress, roster printout)', 'medium', 'stats94 line editor (role only)'),
 (0x78366, 'team_select', 'frontend', 'team selection / lineups / logos', 'low', ''),
 (0x7A13A, 'settings_dialogs', 'frontend', 'settings dialogs: Music/Sound/Digitized Speech, controllers', 'medium', ''),
 (0x7DC8B, 'gadgets_replay', 'frontend', 'rock music cues, gadget UI (instant replay controls)', 'low', 'replay94 (role only)'),
 (0x7F724, 'highlights', 'frontend', 'highlight reel save/load (.HI)', 'medium', ''),
 (0x8034B, 'settings_lockerroom', 'frontend', 'game settings summary, locker room / jerseys', 'medium', ''),
 (0x8291E, 'sound_config', 'frontend', 'sound card selection and nhl.cfg (MT32HOCK)', 'medium', ''),
 (0x83459, 'speech', 'frontend', 'speech buffers / sample memory', 'medium', ''),
 (0x842BA, 'announcer', 'frontend', 'play-by-play / PA announcer sentence builder (.cor/.bar/.int)', 'high', ''),
 (0x85924, 'demo_savegame', 'frontend', 'demo game, save game dialogs', 'medium', ''),
 (0x86696, 'season_playoffs', 'season95', 'season / playoff tree, schedule.db, Stanley Cup screens', 'medium', 'NEW in 95 (Genesis season95) / data94 playoff tree (role)'),
 (0x8BAAF, 'allfiles_coach', 'frontend', 'ALLFILES.TXT check, coach screen', 'low', ''),
 (0x8BEDB, 'asm_helpers', 'engine', 'hand-written asm helpers: MVI player, VGA mode setup (8C290), randomd0, vtoa', 'high', 'video94 randomd0, checks94 vtoa'),
 (0x8C94C, 'LIBZONE', None, None, None, None),
]
# Named EA / third-party library ranges inside the library zone (non-Watcom runs get these names)
LIBNAMES = [
 (0x8C94C, 'ea_memman', 'ealib', 'EA memory manager (reservemem/resizemem/findmemblock/getmemblock, LOW/HIGH MEM)', 'high'),
 (0x8DCF8, 'ea_memman_init', 'ealib', 'initmemman (DPMI allocation via int386 31h)', 'high'),
 (0x8DF70, 'ea_vesa_init', 'ealib', 'EA VESA graphics init (EAVESA.COM, initgraphics)', 'high'),
 (0x8E3DC, 'ea_timer', 'ealib', 'EA timer list (addtimer), PIC/PIT programming', 'high'),
 (0x8E7A0, 'ea_window', 'ealib', 'EA window / subwindow / locate shape helpers', 'medium'),
 (0x8EB5B, 'ea_sound_hl', 'eacsndf', 'EACSNDF high level: sound config, patch/timbre (%sFF%03d.PAT/.TIM), KMS music, IFF/8SVX sample loader (FORM/RIFF/VHDR), palette DAC write', 'medium'),
 (0x903F0, 'ea_gfx', 'ealib', 'EA graphics primitives: text/fonts (FNTM), rect fills, blits', 'low'),
 (0x93308, 'ea_fileblock', 'ealib', 'savefileblock etc.', 'medium'),
 (0x93938, 'ea_debug', 'ealib', 'EA debug utilities: DBUG??.TXT log, memory map dump, shape-file dump, SCREEN?? snapshot', 'high'),
 (0x96440, 'ea_mvi', 'ealib', 'MVI movie palette / DATABUFFER', 'medium'),
 (0x96A60, 'eacsndf_core', 'eacsndf', 'EACSNDF.LIB (Jul 28 1994) core + null driver stubs (dispatch table D4BA0)', 'high'),
 (0x97300, 'ea_unpack', 'ealib', 'EA unpack (QFS/RefPack-style decompressor, INVALID PACK CODE)', 'high'),
 (0x981AD, 'ea_kbd_exit', 'ealib', 'EXIT TO DOS / PAUSE prompts, int 21h vector helpers', 'medium'),
 (0x98B30, 'ea_shapes', 'ealib', 'shape files (.fsh/.vsh/.qfs/.qvs), removewindow', 'high'),
 (0x9A7A0, 'ea_mcga_window', 'ealib', 'MCGA window definitions', 'high'),
 (0x9B498, 'ea_misc', 'ealib', 'misc EA lib routines', 'low'),
 (0x9C594, 'ea_unpackf_blit', 'ealib', 'unpackf (file unpack) + unrolled blit stubs', 'medium'),
 (0x9D090, 'ea_snap', 'ealib', 'SHAPE snapshot', 'medium'),
 (0x9D68E, 'snd_pcspeaker', 'sounddrv', 'EACSNDF driver: PC speaker (dispatch table D4BCC; PIT 43h/61h via A65E8)', 'medium'),
 (0x9DE9C, 'snd_adlib', 'sounddrv', 'EACSNDF driver: AdLib/OPL2 FM (dispatch table D4BF8; OPL reg writer A6858)', 'high'),
 (0x9F226, 'snd_soundblaster', 'sounddrv', 'EACSNDF driver: Sound Blaster digital (dispatch D4C24; BLASTER env, DOS mem via DPMI)', 'high'),
 (0x9FD94, 'snd_mt32_mpu401', 'sounddrv', 'EACSNDF driver: Roland MT-32 via MPU-401 (dispatch D4C50; status bit 40h polling)', 'high'),
 (0x9FFCA, 'snd_gus', 'sounddrv', 'EACSNDF driver: Gravis UltraSound (dispatch D4C7C/D4CA8; ULTRASND/ULTRADIR, .PAT)', 'high'),
 (0xA1948, 'dos4gw_intr', 'dos4gw', 'int386x/_DoINTR int-stub table (DOS/4GW flat-mode interrupt glue)', 'medium'),
 (0xA1CA2, 'clib_spawn_system', 'watcom', 'Watcom system()/spawn helpers (COMSPEC, .bat/.com/.exe)', 'high'),
 (0xA2000, 'ea_shpi', 'ealib', 'EA SHPI shape-file loader (SHPI / SHPM)', 'high'),
 (0xA2F40, 'ea_unpack_helpers', 'ealib', 'unpack helpers', 'low'),
 (0xA3274, 'watcom_emu387', 'watcom', 'Watcom 80387 emulator/FPU support (opcode dispatch tables funcs_A36CA.., __hook387)', 'medium'),
 (0xA65E8, 'snd_hw_pcspk_opl', 'sounddrv', 'low-level PC speaker (PIT) and OPL2 register I/O for drivers above', 'high'),
 (0xA6BE1, 'snd_hw_sb', 'sounddrv', 'Sound Blaster DSP/DMA + 4 KB unrolled mixers (A715C/A815D)', 'medium'),
 (0xA9C9C, 'snd_hw_irq_dma', 'sounddrv', 'IRQ (PIC 20h/A0h) hook + 8237 DMA programming', 'high'),
 (0xAA210, 'snd_gus_sdk', 'sounddrv', 'Gravis UltraSound low-level / patch loader (GF1PATCH110) and MIDI', 'high'),
 (0xB28C9, 'input_keyboard', 'ealib', 'keyboard ISR (port 60h), int 16h', 'high'),
 (0xB2D38, 'input_mouse', 'ealib', 'mouse (int 33h)', 'high'),
 (0xB300C, 'input_joystick_misc', 'ealib', 'joystick (port 201h) + misc helpers', 'high'),
 (0xB3B00, 'ea_fileio', 'ealib', 'EA file I/O (openhandle, int 21h read/close/findfirst)', 'high'),
 (0xB3E4A, 'video_bios_vga', 'ealib', 'video BIOS (int 10h), VGA DAC (3C8h) / vsync (3DAh)', 'high'),
 (0xB4CD8, 'vga_blitters', 'ealib', 'VGA blit/draw routines (dispatch table C66D8)', 'medium'),
 (0xB5D80, 'vesa_banked_blit', 'ealib', 'VESA bank switching (int 10h/4F05, port 1CEh) and banked blit stubs', 'medium'),
]
# File-level regions outside the LE objects
FILE_REGIONS = [
 (0x0, 'dos16m_loader_stub', 'dos4gw', 'MZ stub: Rational Systems DOS/16M loader (DOS/4G Copyright 1987-1993)', 'high'),
 (0xF474, 'dos4gw_kernel_4gwpro', 'dos4gw', "'BW' bound DOS/16M image: DOS/4GW Professional 4GWPRO.EXP (May 19 1994), LINEXE loader", 'high'),
 (0x26654, 'watcom_wstub', 'dos4gw', 'bound MZ stub (Watcom wstub: exec dos4gw.exe) whose e_lfanew -> LE', 'high'),
 (0x28FEC, 'le_header_tables', 'le', 'LE header, object table, page map, resident names, entry table, fixup page/record tables, import tables', 'high'),
 (None, 'pad', 'le', 'padding up to data pages', 'high'),
]
