#!/usr/bin/env python3
"""Write EXE_SEGMAP95PC.md from segmap95pc.json + tools/matcher_stats.json + name_map_94.csv (run last)."""
import os, json, csv, collections
os.chdir(os.path.join(os.path.dirname(os.path.abspath(__file__)), '..'))
J = json.load(open('segmap95pc.json')); ST = json.load(open('tools/matcher_stats.json'))
rows = list(csv.DictReader(open('name_map_94.csv')))
G93 = {'engine_init': '93G hockey93_01 Begin/init (role)', 'engine_player_logic': '93G logic93_2..5 assignments (asstab slots) + 94G onetimer/breakaway/goalie additions',
       'engine_physics_ai': '93G hockey93_05 puck collisions / logic93 (role)', 'engine_sound_iface': '93G sound93 / middle93_1 sfx triggers (role)',
       'engine_core': '93G hockey93_02 updateplayers (asstab dispatch); logic93_5 SetSPA/GetHot',
       'engine_input': '94G input94 doinput_ispc / 93G logic93_1 doinput (role)', 'engine_assign_faceoff': '93G logic93_4 puckfaceoff/puckfaceoff2/asspassrec, logic93_1 check4bench; 94G onetimer94 assonetimer',
       'engine_skating': '93G logic93_5 movement block (doplayeracc, goalieacc, noturn0, playeracc, dostop, StopNA, skateto, skatetopuck)', 'scoring_penalty_text': '93G penalty93 / stats93 (role)',
       'engine_display': '93G video93 (role)', 'asm_helpers': '93G middle93_1 randomd0, logic93_5 vtoa', 'main_startup': '93G hockey93_01 Begin (role only)',
       'game_state_saveload': '', 'game_frame': '93G hockey93_02 main loop (role, unverified)', 'debug_dump': ''}
for s in J['cseg01']:
    if s['module'] in G93: s['genesis'] = G93[s['module']] + ((' ; 94G: ' + s['nhl94']) if s['nhl94'] else '')
    else: s['genesis'] = (s.get('nhl95g_role') or s['nhl94'] or ('-' if s['group'] in ('frontend',) else ''))
# ---- per-segment Genesis identity from the deep semantic matches
SEMJ = json.load(open('tools/sem_matches.json'))
SM = {int(k, 16): v for k, v in SEMJ['matches'].items()}
import pickle as _pk, bisect as _bs
_FEAT = _pk.load(open('tools/sem_feat.pkl', 'rb'))
GFILE = {}
for g in _FEAT['gen']:
    if g['kind'] == 'code' and (g['name'] not in GFILE or g['game'] == '93G'): GFILE[g['name']] = '%s %s' % (g['game'], g['file'])
for s_ in J['cseg01']:
    hits = [v for a, v in SM.items() if s_['start'] <= a < s_['end'] and v['src'] != 'PC-new']
    s_['genesis_matches'] = len(hits)
    if hits:
        fc = collections.Counter(GFILE.get(v['name'].replace('_body', ''), '?') for v in hits)
        s_['genesis'] = ('%d routines matched (%s)' % (len(hits), ', '.join('%s x%d' % kv for kv in fc.most_common(4)))) + ((' ; ' + s_['genesis']) if s_.get('genesis') and s_['genesis'] != '-' else '')
json.dump(J, open('segmap95pc.json', 'w'), indent=1)
h = lambda v: '%X' % v if v is not None else '-'
L = []; P = L.append
P('# NHL 95 PC (HOCKEY.EXE) segment map\n')
P('Working document. Groundwork for a bit-perfect disassembly. Generated by `tools/write_md.py`; every number below is reproducible from the scripts.\n')
P('Run order: `le_parse.py` → `lst_parse.py` → `build_funcs.py` → `features.py` → `ref94_index.py` / `ref93_index.py` → `build_segmap.py` → `matcher.py` → `write_md.py`. Helpers: `segdef.py` (curated boundaries), `region.py LO HI` (inspect a range).\n')
e = J['exe']; P('## 1. Summary\n')
P('* File: `HOCKEY.EXE`, %d bytes, sha1 `%s`' % (e['size'], e['sha1']))
P('* Toolchain: %s.' % J['toolchain']['compiler'])
P('* Extender: %s.' % J['toolchain']['extender'])
P('* Lineage (from user): 94 PC was ported from 93 Genesis (+ some 94G, new menus); 95 PC = 94 PC + 94G/95G additions. Name mapping therefore prefers 93G names, then 94G, then 95G; the front end is labelled PC-new.\n')
P('## 2. Whole-file layout (tiles 0..EOF: %s)\n' % J['verification']['file_regions_tile_exe'])
P('| file start | file end | size | region | group | contents | conf |'); P('|---|---|---|---|---|---|---|')
for r in J['file_regions']:
    P('| %X | %X | %X | %s | %s | %s | %s |' % (r['file_start'], r['file_end'], r['file_end'] - r['file_start'], r['module'], r['group'], r['desc'], r['conf']))
hd = J['le_header']
P('\n## 3. LE header (parsed by `tools/le_parse.py`)\n')
P('Bound Watcom MZ at file 0x%X, LE header at file 0x%X. Data pages at bound-MZ-relative 0x%X (absolute 0x%X). Page size 0x%X, %d pages, last page 0x%X bytes. Entry %s, stack %s. Fixups: %d (%s).\n' % (
    J['bound_mz_off'], J['le_off'], hd.get('data_pages_off', 0), J['objects'][0]['file_start'], hd.get('page_size', 0), hd.get('num_pages', 0), hd.get('last_page_size', 0),
    'obj%s:%08X (linear %X, Watcom `start`)' % (hd.get('eip_object'), hd.get('eip', 0), 0x10000 + hd.get('eip', 0)), 'obj%s:%08X' % (hd.get('esp_object'), hd.get('esp', 0)), J['fixups']['count'], J['fixups']['types']))
P('| obj | name | linear base | vsize | flags | pages (map idx) | file range | file bytes | mapping |'); P('|---|---|---|---|---|---|---|---|---|')
for o, nm in zip(J['objects'], ('cseg01', 'dseg02')):
    P('| %d | %s | %X | %X | %X | %d (%d) | %X-%X | %X | %s |' % (o['num'], nm, o['base'], o['virtual_size'], o['flags'], o['page_count_in_file'], o['page_map_index'], o['file_start'], o['file_end'], o['file_bytes'], o['lin_to_file']))
P('\nobj1: last 0x%X file bytes after vsize are page padding. obj2: initialised data ends at linear %X; BSS 0x%X bytes up to %X (stack top).\n' % (
    J['verification']['obj1']['file_pad_after_vsize'], J['objects'][1]['base'] + J['objects'][1]['file_bytes'], J['verification']['obj2']['bss_bytes'], J['objects'][1]['base'] + J['objects'][1]['virtual_size']))
def segtable(lst, title):
    P(title); P('| start-end | file range | size | funcs | module | group | lineage | contents | Genesis counterpart | conf |'); P('|---|---|---|---|---|---|---|---|---|---|')
    for s in lst:
        fr = '%X-%X' % (s['file_start'], s['file_end']) if s['file_bytes'] else '(BSS)'
        if s['file_bytes'] and s['file_bytes'] < s['size']: fr += ' +BSS'
        P('| %X-%X | %s | %X | %d | %s | %s | %s | %s | %s | %s |' % (s['start'], s['end'], fr, s['size'], s.get('n_funcs', 0), s['module'], s['group'], s.get('lineage', ''),
          s['desc'].replace('|', '/')[:160], (s.get('genesis') or '; '.join(s.get('nhl94_data', [])) or '').replace('|', '/')[:120], s['conf']))
segtable(J['cseg01'], '\n## 4. cseg01 segments (%d, tile %X-%X exactly)\n' % (len(J['cseg01']), J['objects'][0]['base'], J['objects'][0]['base'] + J['objects'][0]['virtual_size']))
P('\n### 4a. Boundary revision (2026-10-09)\n')
P('Rule used: Watcom wlink keeps each object file contiguous and a function (incl. its IDA "chunks") never spans objects, so boundaries were moved to function starts where call clusters, shared chunks, shared globals and string ownership change. Genesis source-file order is only a hint (the C port reorders routines).\n')
for t in [
 '**engine_skating 5E16D-5FB03 (new, split from engine_core + game_state_saveload)**: doplayeracc, skateto, skatetopuck, playeracc, 5F151, dostop, StopNA, goalieacc, noturn0 = the 93G logic93_5 movement block. 5F151 (called only by skateto/skatetopuck) owns chunk 5E7F7 inside this range, so 5F151 cannot start a different object; goalieacc/noturn0 (5F8B2/5F98A) were wrongly in game_state_saveload. High.',
 '**game_state_saveload now starts at 5FB03** (first function with "Error Saving Game"; 60612 has Saving/Loading). High.',
 '**updateplayers (5C40F) stays in engine_core**: it is 0x1D5E bytes before doplayeracc with updateanim, DoGameFrame helpers, bench/line resets and forcepldata in between; it is the per-frame dispatcher (93G hockey93_02), not part of the movement object.',
 '**burst (532BD)** confirmed in engine_physics_ai (was already there; first routines Sweepcheck/burst follow 53294).',
 '**engine_input 4FCE8-50AFE (new, split from engine_player_logic)**: input ring buffer g_inputBufferOffset1/2/3 (4FCE8/4FD47/4FD62, called from front-end 1149A), doinput_ispc 504DA and the helpers only it calls (4FD8E, 4FF0D, 503CD, 50434), pad latch 50A05/50A84 (pollMenuInputAndDispatch), mouse 50ADE. Medium.',
 '**engine_assign_faceoff 50AFE-53294 (new, split)**: assonetimer, asspassrec, puckfaceoff/puckfaceoff2, slots 39-41/44/45, check4bench. 50AFE belongs here (called by assonetimer/asspassrec/puckglue). Medium.',
 '**engine_sound_iface now 59493-59D9A** (was 59884-59DBB): 59493/594B2 are callbacks called from EACSNDF high level (8EE2F, 8EE4F, 8F13B, 8F98F) and 594CD-59863 are music start/stop wrappers into ea_sound_hl; SetSPA (59D9A, 54 engine callers, no sound calls) moved to engine_core. Medium.',
 '**scoring_penalty_text extended to 644A8** (engine_display used to start at 63475, splitting the penalty chain): Stop4Pen 63543 and 637B5-63BF8 call each other and 62EA2/62EE9 ("served by #%d"); 63D69-64439 call 62EE9/AddPenalty2. engine_display starts at the 644A8/6455F/64614 ticker cluster. Medium.',
 '**zonemgr starts at 6A033** (was 6A106): 6A033-6A0F6 are zone-flag/bitmap accessors on EA058/EA09C/EA074/EA0AC, globals otherwise used only by ZONEMGR (6A106-6B093); front end 3377C calls 6A033, 6A0F6, 6A106, 6A156 in sequence. Removed from game_frame. High.']:
    P('* ' + t)
P('\n## 5. Library boundary notes\n')
for t in [
 '**DOS/16M loader + DOS/4GW Professional kernel** (file 0-0x26654): own file regions; the kernel is a "BW" bound 4GWPRO.EXP (May 19 1994). Boundaries exact (header fields). High.',
 '**Watcom wstub + LE tables** (0x26654-0x5F254): bound MZ whose e_lfanew points at the LE header; LE loader/fixup/import tables up to the first data page. High.',
 '**DOS/4GW glue inside the objects**: `dos4gw_dpmi_glue_*` (Watcom clib routines that only exist for the DOS/4GW/Rational environment: DPMI heap `__FreeDPMIBlocks_`, `__ReAllocDPMIBlock_`, `RationalAlloc_`, `int386_`/`int386x_`, `segread_` ...) and `dos4gw_intr` (A1948-A1CA2, int-stub table used by int386x/_DoINTR). Kept separate from `watcom_clib_*`. Direct int 31h DPMI calls are also made from EA code (main_ 0x10167, initmemman 0x8DE08, sound drivers 0x9FCDA/0xA0006) - those stay in their owning segments. High for FLIRT-named, medium for unnamed stubs.',
 '**Watcom C runtime**: `watcom_begtext` (10000-10010), `watcom_clib_*` interleaved through the library zone (Watcom wlink pulls library modules on demand, so clib and EA lib objects alternate), `watcom_emu387`, `clib_spawn_system`, `watcom_stack` in dseg02. Boundaries = FLIRT collapsed-function extents plus helpers called only from clib. High.',
 '**EA PC library** (memman, vesa_init/EAVESA, timer, window, gfx/FNTM fonts, fileblock, debug, MVI, unpack/QFS-RefPack, unpackf, shapes .fsh/.qfs, SHPI loader A2000, snap, input, fileio, VGA/VESA blitters, zonemgr, CMV player, CDSTREAM): boundaries from string/xref clusters and call-graph cuts; medium unless noted in the table.',
 '**EACSNDF.LIB** (Jul 28 1994) high-level + core + 7 driver dispatch tables (dseg D4BA0..D4CA8): `snd_pcspeaker`, `snd_adlib`, `snd_soundblaster`, `snd_mt32_mpu401`, `snd_gus` and the low-level `snd_hw_*` / `snd_gus_sdk` (GF1PATCH110) ranges. Driver starts = first function referenced by each dispatch table (high); ends = next table target (medium). No PAS-specific driver found.',
 '**File formats**: SHPI (A2000, magic "SHPI"/"SHPM"), QFS/RefPack-like unpack (97300, "INVALID PACK CODE"), FORM/RIFF/VHDR IFF loader in ea_sound_hl (8F98F), MVIh/MVIe/MVIf in title_intro/asm_helpers callers, FNTM in ea_gfx, .VIV (XBRUCE2) referenced from the speech/announcer code. No BIGF magic present; no SHPS magic. PPV handled by name only (.PPV strings in gamesave_io/asset_loading).']:
    P('* ' + t)
segtable(J['dseg02'], '\n## 6. dseg02 segments (%d, tile %X-%X exactly; owner = majority group of referencing code)\n' % (len(J['dseg02']), J['objects'][1]['base'], J['objects'][1]['base'] + J['objects'][1]['virtual_size']))
P('\nData counterparts: ' + '; '.join('%s %s (%s)' % (d['addr'], d['name'], d['evidence']) for d in J['data_counterparts_94']) + '\n')
P('## 7. Name map (`name_map_94.csv`)\n')
c = collections.Counter((r['source_game'], r['confidence']) for r in rows)
P('Rows: %d. By source game / confidence:\n' % len(rows))
for k, v in sorted(c.items()): P('* %s / %s: %d' % (k[0], k[1], v))
P('\nColumns: pc_address, ida_name, proposed_name, source_game (93G/94G/95G/PC-new/library), source_file, 94_source_file, other_game_names, confidence, evidence, segment, method.\n')
# Optional local cross-check of FUNCTION_MAPPINGS95.md (not in the repo): written to FM95_CHECK.md (gitignored), never into this file.
if os.path.isfile('tools/fm95_check.json'):
    FC = json.load(open('tools/fm95_check.json')); Q = ['# FUNCTION_MAPPINGS95.md cross-check (local only)\n']
    Q.append('%d claims parsed. Confirmed: %d. Unverifiable: %d. Wrong: %d. Genesis-equivalent claims: %d, of which %d use names not in the 92/93/94/95 Genesis sources.\n' % (
        FC['fm95_rows'], FC['fm95_status'].get('confirmed', 0), FC['fm95_status'].get('unverified', 0), FC['fm95_status'].get('conflict', 0), FC['fm95_genesis_claims'], FC['fm95_genesis_claims_invalid_name']))
    Q += ['* `%s` → %s: %s' % (w[0], w[1], w[3]) for w in FC['wrong_examples']]
    open('FM95_CHECK.md', 'w').write('\n'.join(Q) + '\n')
# ---------------- deep semantic pass ----------------
P('\n### Deep semantic matching pass (tools/sem_features.py, fieldmap.py, data_tables.py, sem_match.py)\n')
P('Methods: (1) player-struct field correspondence learned by aligning 68k field-access sequences with x86 [reg+disp] sequences of content-verified anchors (tools/struct_fieldmap.csv); (2) global RAM/data correspondences by aligning global-access sequences plus byte-compared data tables (tools/global_map.csv, tools/data_matches.json); (3) tf-idf cosine over mapped fields, globals, named callees and distinctive immediates plus an LCS over the ordered field-access stream; (4) call-graph propagation by aligning callee sequences of matched pairs (votes across callers) and caller propagation; (5) control-flow/size shape gate. Matches are accepted only as mutual best with a margin; front-end functions need a shared call/global token as well as fields. Iterated to a fixed point.\n')
B = list(csv.DictReader(open('tools/name_map_94_before.csv')))
def _cnt(r): return collections.Counter((x['source_game'], x['confidence']) for x in r if x['source_game'] in ('93G', '94G', '95G'))
cb, ca = _cnt(B), _cnt(rows)
P('| source/conf | before | after |'); P('|---|---|---|')
for k in sorted(set(cb) | set(ca)): P('| %s / %s | %d | %d |' % (k[0], k[1], cb.get(k, 0), ca.get(k, 0)))
P('| total Genesis-named | %d | %d |' % (sum(cb.values()), sum(ca.values())))
ENG = [(0x47C31, 0x6A033), (0x8BEDB, 0x8C94C)]
eng = [a for a in _FEAT['pc'] if any(lo <= a < hi for lo, hi in ENG)]
eg = [a for a in eng if a in SM and SM[a]['src'] != 'PC-new']; ep = [a for a in eng if a in SM and SM[a]['src'] == 'PC-new']
P('\nEngine region (47C31-6A033, 8BEDB-8C94C): %d functions (IDA procs + recovered); %d named from Genesis (%.0f%%), %d labelled PC-new assignments, total labelled %.0f%%.\n' % (len(eng), len(eg), 100.0 * len(eg) / len(eng), len(ep), 100.0 * (len(eg) + len(ep)) / len(eng)))
P('Field map: %s.\n' % ', '.join('%s=%s' % (k, '/'.join(v)) for k, v in SEMJ['fieldmap'].items()))
P('Global map: %s.\n' % ', '.join('%s=%s' % (k, '/'.join(v)) for k, v in SEMJ['globalmap'].items()))
top = sorted([(a, v) for a, v in SM.items() if v['src'] != 'PC-new' and v['conf'] in ('high', 'medium')], key=lambda t: (t[1]['conf'] != 'high', -t[1].get('score', 0)))[:30]
P('Notable identifications:\n'); P('| pc | name | source | conf | method | key evidence |'); P('|---|---|---|---|---|---|')
for a, v in top: P('| %X | %s | %s | %s | %s | %s |' % (a, v['name'], GFILE.get(v['name'].replace('_body', ''), v['src']), v['conf'], v['method'], v['evidence'][:150].replace('|', '/')))
P('\nCorrections to the earlier name map: asstab slots $1D-$23 (previously 94G assgoaliectrl, puckshootout, puckpenshot, assgoaliebreakwait, chkpuckc, assbreakaway, assonetimer by position) fail the content check (rank 13-36 of 36) and are relabelled PC-own assignments; slots $14/$15 (93G assfight/assfwatch) are repurposed (see verdict); slots 1-12, $16, $18 upgraded to high/medium by content.\n')
P('Slot 20/21 verdict: NOT fight code. 49460 (slot $14) has none of 93G assfight\'s markers (Pencntdwn test, getpde energy, aggress byte, fight animations); it initialises temp5/temp2, picks a target from table CC9EA by team/position, skates until dist^2 < 900 then calls assexit. 495B8 (slot $15) selects players and formats "%s Star"/"EA Sports" with sprintf. Both are repurposed for the 3-stars-of-the-game presentation (PC-new, medium).\n')
P('Hard areas: engine_display (VGA rendering, 1 match), engine_sound_iface (EACSNDF wrappers), scoring_penalty_text and game_state_saveload (PC text/UI), the 18 PC-own assignment slots, and 93G stats/frames/video routines whose PC replacements are rewritten for VGA/PC data formats. Global map coverage is limited because Watcom keeps many C locals in static dseg temporaries (E03AC-E03C0), which dominate global access streams.\n')
P('\n## 8. Verification\n')
V = J['verification']
for k in ('obj1', 'obj2'):
    v = V[k]; P('* %s: %d segments, tiles exactly = %s; concatenated file slices == object pages = %s (%d bytes, sha1 %s); BSS %X; file padding after vsize %X.' % (k, v['segments'], v['tiles_exactly'], v['concat_equals_object_pages'], v['bytes_compared'], v['sha1'], v['bss_bytes'], v['file_pad_after_vsize']))
P('* File regions tile 0..EOF: %s. Stub signatures: %s.' % (V['file_regions_tile_exe'], V['stub_checks']))
P('* Listing string literals vs EXE bytes via lin→file mapping: %d matched, %d mismatched (mapping sanity check).' % (V['listing_strings_vs_exe']['matched'], V['listing_strings_vs_exe']['mismatched']))
P('\n## 9. Open questions\n')
for t in ['Front-end module boundaries (0x10010-0x47C31, 0x6B093-0x8BAAF) follow string/call clusters; a few may need to shift by one function once object-file order is confirmed (e.g. by matching __CHK frame sizes or align padding).',
          'asstab slots 1-35 beyond the trivial stubs are low confidence (order inherited from 93G/94G, bodies rewritten in C); slots 20/21 (93G assfight/assfwatch) look repurposed; slots 36-46 have no Genesis counterpart.',
          'Is 95 PC fighting present? 93G has real assfight code, 94G stubs it; PC slot 20 (49460) is 344 bytes.',
          'EA library sub-boundaries inside ea_gfx/ea_misc/ea_debug are medium; no EA .MAP file was available to confirm object names.',
          'Segment revision leftovers: assreplace/assinsert (11FF4/12011, logic93_5 roles) sit inside front-end gamesave_io between 11D09 and 12034, so their object is shared with front-end code (not moved); the input/assign split points 4FCE8 (vs 4F99B, shotdiradj = 94G input94) and 50AFE are medium; SetSPA could equally be the last routine of the sound-wrapper object; the 614C2-61D48 part of scoring_penalty_text and the 644A8-65CA8 start of engine_display are still cluster guesses; sroot B3D94 and trig B49C0-B4AA4 are EA math routines inside ea_fileio/video_bios_vga ranges (library sub-boundary not split).',
          'dseg02 ownership is by majority referencing group; shared tables near group boundaries (marked "also ...") are low confidence.',
          'The 239 FLIRT-collapsed functions have no body in the .lst; a bit-perfect rebuild needs them re-disassembled (or linked from the same Watcom 9.x/10.0 clib version).']:
    P('* ' + t)
P('\n## 10. Outputs\n')
for t in ['EXE_SEGMAP95PC.md (this file)', 'segmap95pc.json', 'name_map_94.csv', 'tools/*.py (le_parse, lst_parse, build_funcs, features, region, ref94_index, ref93_index, segdef, build_segmap, matcher, write_md)', 'tools/le.json, lst_index.pkl, funcs.pkl, features.pkl, ref93.pkl, ref94.pkl, segs.pkl, matcher_stats.json', 'ref/92, ref/93, ref/94, ref/95: read-only local copies of the Genesis sources used (not committed; clone them from the NHL9xGenesis repos)']:
    P('* ' + t)
open('EXE_SEGMAP95PC.md', 'w').write('\n'.join(L) + '\n')
print('wrote', len(L), 'lines')
