; calendar 33FFD-35FB9  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_33FFD progbits alloc exec nowrite align=1
extern __CHK, str_Boxr, str_Boxb, str_Bkgd7, str_02d9D, str_Home, str_Away, str_SDD2
extern str_Pal17, str_Calendar, str_Callogo, str_Iff9, str_Pointer8, str_Menubuff5, monthdays, monthfirstday_m1
extern monthfirstday, musicon, lgteam_17, gameopts, teamstatscb, fileoncd
extern skaterstatscb, goaliestatscb, standingscb, standingsmenucb, songdata, calcolx, calrowy
extern calendarshapes, musichandle, cddriveptr, fontcolor, mainfont, pointerspr, musicslot
extern calsel, calexit, calmonth, calselday, dword_DDD2C, calselmonth, ptrupdatefn, fputchar
extern jctime, crestnames, calnextslot, calprevslot, sprintf_, MakePath, FileOpenRead, leaguedbnames
extern FileClose, FileReadAt, ReadSchedGame, GameTeamStatsScreen, GameSkaterStatsScreen, GameGoalieStatsScreen, GameStandingsScreen, GameStandingsMenu
extern CalTeamStatsScreen, CalSkaterStatsScreen, CalGoalieStatsScreen, CalStandingsScreen, CalStandingsMenu, SetDialogColors, ShowLoadingScreen, FadeOutPalCycle
extern GetInputEvent, ClearInputQueue, DrawMenuBar, DrawMenuDropdown, DrawMenuItemSel, DrawMenuItemNorm, MenuHitTest, FadePalStep
extern SetCtlTeams, sub_8CCA8, sub_8D2F0, sub_8E83C, sub_8E9E8, sub_8EA00, sub_8EA18, sub_8F98F
extern sub_8FB8E, sub_8FC8A, sub_8FCDF, sub_8FFB0, sub_903F0, sub_9061C, sub_91370, sub_913D0
extern sub_91400, sub_91964, MouseSetPos, sub_B2DCA, sub_B30B4, sub_B392C, sub_B4BA8, sub_B4BC4
extern sub_B4DD4, sub_B4FAC, str_D8, str_W5, str_L7, str_T5, calmenubar, unk_DF014
global DrawCalendarDay, CalNextMonth, CalPrevMonth, CalReturn, ApplyShapePalette, SetGameSides, CalendarScreen
DrawCalendarDay:
push dword 0CCh	; 33FFD
call __CHK	; 34002
push esi	; 34007
push edi	; 34008
push ebp	; 34009
sub esp, 9Ch	; 3400A
push eax	; 34010
push edx	; 34011
push ecx	; 34012
mov esi, dword [dword esp+0C4h]	; 34013
push str_Boxr	; 3401A
push esi	; 3401F
call sub_B30B4	; 34020
add esp, byte 8	; 34025
mov dword [dword esp+084h], eax	; 34028
push str_Boxb	; 3402F
push esi	; 34034
call sub_B30B4	; 34035
add esp, byte 8	; 3403A
mov dword [dword esp+094h], eax	; 3403D
push str_Bkgd7	; 34044
push esi	; 34049
call sub_B30B4	; 3404A
add esp, byte 8	; 3404F
push eax	; 34052
call sub_9061C	; 34053
add esp, byte 4	; 34058
mov edx, dword [byte esp+08h]	; 3405B
cmp edx, byte 9	; 3405F
setl al	; 34062
and eax, 0FFh	; 34065
add eax, byte 3	; 3406A
push eax	; 3406D
lea eax, [byte edx+01h]	; 3406E
push eax	; 34071
push str_02d9D	; 34072
lea eax, [byte esp+058h]	; 34077
push eax	; 3407B
call sprintf_	; 3407C
add esp, byte 10h	; 34081
lea eax, [byte esp+04Ch]	; 34084
push eax	; 34088
push esi	; 34089
call sub_B30B4	; 3408A
add esp, byte 8	; 3408F
push eax	; 34092
call sub_9061C	; 34093
add esp, byte 4	; 34098
mov ecx, dword [dword esp+0BCh]	; 3409B
shl ecx, 2	; 340A2
mov ebx, dword [dword ecx+crestnames]	; 340A5
mov byte [byte esp+04Ch], 21h	; 340AB
mov al, byte [ebx]	; 340B0
mov byte [byte esp+04Dh], al	; 340B2
mov al, byte [byte ebx+01h]	; 340B6
mov byte [byte esp+04Eh], al	; 340B9
mov al, byte [byte ebx+02h]	; 340BD
mov byte [byte esp+04Fh], al	; 340C0
push byte 3Fh	; 340C4
push byte 26h	; 340C6
add ecx, dword [byte esp+0Ch]	; 340C8
mov esi, dword [ecx]	; 340CC
push esi	; 340CE
call sub_913D0	; 340CF
add esp, byte 0Ch	; 340D4
lea eax, [byte esp+0Ch]	; 340D7
push eax	; 340DB
call sub_8E9E8	; 340DC
add esp, byte 4	; 340E1
mov edi, dword [dword esp+0C0h]	; 340E4
push edi	; 340EB
call sub_8EA18	; 340EC
add esp, byte 4	; 340F1
mov dword [fontcolor], 0C0h	; 340F4
mov eax, dword [byte esp+08h]	; 340FE
cmp byte [dword eax+monthfirstday], 0	; 34102
je short .1	; 34109
mov esi, dword [calcolx]	; 3410B
add esi, byte 7	; 34111
mov edi, dword [calrowy]	; 34114
jmp short .2	; 3411A
.1:
mov esi, dword [calcolx+18h]	; 3411C
add esi, byte 7	; 34122
mov edi, dword [calrowy+14h]	; 34125
.2:
add edi, byte 5	; 3412B
mov dword [fontcolor], 0B6h	; 3412E
push edi	; 34138
push esi	; 34139
push str_Home	; 3413A
call sub_91964	; 3413F
add esp, byte 0Ch	; 34144
mov dword [fontcolor], 0B7h	; 34147
add edi, byte 0Ch	; 34151
push edi	; 34154
push esi	; 34155
push str_Away	; 34156
call sub_91964	; 3415B
add esp, byte 0Ch	; 34160
xor ebp, ebp	; 34163
jmp near .4	; 34165
.3:
xor ebx, ebx	; 3416A
mov eax, dword [byte esp+08h]	; 3416C
mov bl, byte [dword eax+monthfirstday]	; 34170
add ebx, ebp	; 34176
mov esi, 7	; 34178
mov eax, ebx	; 3417D
mov edx, ebx	; 3417F
sar edx, 1Fh	; 34181
idiv esi	; 34184
mov esi, edx	; 34186
mov ecx, 7	; 34188
mov eax, ebx	; 3418D
mov edx, ebx	; 3418F
sar edx, 1Fh	; 34191
idiv ecx	; 34194
mov esi, dword [nosplit esi*4+calcolx]	; 34196
add esi, byte 4	; 3419D
mov edi, dword [nosplit eax*4+calrowy]	; 341A0
inc edi	; 341A7
inc ebp	; 341A8
push ebp	; 341A9
push str_D8	; 341AA
lea eax, [byte esp+054h]	; 341AF
push eax	; 341B3
call sprintf_	; 341B4
add esp, byte 0Ch	; 341B9
mov dword [fontcolor], 0C0h	; 341BC
push edi	; 341C6
push esi	; 341C7
lea eax, [byte esp+054h]	; 341C8
push eax	; 341CC
call sub_91964	; 341CD
add esp, byte 0Ch	; 341D2
mov dword [fontcolor], 0FFh	; 341D5
dec edi	; 341DF
push edi	; 341E0
dec esi	; 341E1
push esi	; 341E2
lea eax, [byte esp+054h]	; 341E3
push eax	; 341E7
call sub_91964	; 341E8
add esp, byte 0Ch	; 341ED
.4:
xor eax, eax	; 341F0
mov ebx, dword [byte esp+08h]	; 341F2
mov al, byte [dword ebx+monthdays]	; 341F6
cmp ebp, eax	; 341FC
jl near DrawCalendarDay.3	; 341FE
mov dword [dword esp+098h], 0FFFFFFFFh	; 34204
xor ebp, ebp	; 3420F
jmp near .18	; 34211
.5:
mov ebx, ebp	; 34216
shl ebx, 2	; 34218
sub ebx, ebp	; 3421B
add ebx, ebx	; 3421D
add ebx, dword [esp]	; 3421F
xor ecx, ecx	; 34222
mov cl, byte [ebx]	; 34224
mov eax, dword [byte esp+08h]	; 34226
inc eax	; 3422A
cmp ecx, eax	; 3422B
jne near .17	; 3422D
xor ecx, eax	; 34233
mov cl, byte [byte ebx+01h]	; 34235
xor eax, eax	; 34238
mov esi, dword [byte esp+08h]	; 3423A
mov al, byte [dword esi+monthfirstday]	; 3423E
add eax, ecx	; 34244
lea esi, [byte eax-01h]	; 34246
mov ecx, 7	; 34249
mov eax, esi	; 3424E
mov edx, esi	; 34250
sar edx, 1Fh	; 34252
idiv ecx	; 34255
mov edi, edx	; 34257
mov eax, esi	; 34259
mov edx, esi	; 3425B
sar edx, 1Fh	; 3425D
idiv ecx	; 34260
mov esi, edi	; 34262
mov esi, dword [nosplit esi*4+calcolx]	; 34264
mov edi, dword [nosplit eax*4+calrowy]	; 3426B
xor eax, eax	; 34272
mov al, byte [byte ebx+02h]	; 34274
cmp eax, dword [dword esp+0BCh]	; 34277
jne short .10	; 3427E
mov eax, dword [dword esp+084h]	; 34280
mov dword [dword esp+09Ch], eax	; 34287
xor eax, eax	; 3428E
mov al, byte [byte ebx+03h]	; 34290
mov dword [dword esp+0A4h], eax	; 34293
mov al, byte [byte ebx+04h]	; 3429A
mov ch, byte [byte ebx+05h]	; 3429D
cmp al, ch	; 342A0
jbe short .7	; 342A2
xor eax, eax	; 342A4
mov al, ch	; 342A6
push eax	; 342A8
xor eax, eax	; 342A9
mov al, byte [byte ebx+04h]	; 342AB
.6:
push eax	; 342AE
push str_W5	; 342AF
jmp near .13	; 342B4
.7:
jae short .9	; 342B9
xor eax, eax	; 342BB
mov al, ch	; 342BD
push eax	; 342BF
xor eax, eax	; 342C0
mov al, byte [byte ebx+04h]	; 342C2
.8:
push eax	; 342C5
push str_L7	; 342C6
jmp short .13	; 342CB
.9:
xor eax, eax	; 342CD
mov al, ch	; 342CF
push eax	; 342D1
xor eax, eax	; 342D2
mov al, byte [byte ebx+04h]	; 342D4
push eax	; 342D7
push str_T5	; 342D8
jmp short .13	; 342DD
.10:
mov ecx, dword [dword esp+094h]	; 342DF
mov dword [dword esp+09Ch], ecx	; 342E6
mov dword [dword esp+0A4h], eax	; 342ED
mov al, byte [byte ebx+04h]	; 342F4
mov dh, byte [byte ebx+05h]	; 342F7
cmp al, dh	; 342FA
jbe short .11	; 342FC
xor eax, eax	; 342FE
mov al, byte [byte ebx+04h]	; 34300
push eax	; 34303
xor eax, eax	; 34304
mov al, dh	; 34306
jmp short DrawCalendarDay.8	; 34308
.11:
jae short .12	; 3430A
xor eax, eax	; 3430C
mov al, byte [byte ebx+04h]	; 3430E
push eax	; 34311
xor eax, eax	; 34312
mov al, dh	; 34314
jmp short DrawCalendarDay.6	; 34316
.12:
xor eax, eax	; 34318
mov al, dh	; 3431A
push eax	; 3431C
xor eax, eax	; 3431D
mov al, byte [byte ebx+04h]	; 3431F
push eax	; 34322
push str_T5	; 34323
.13:
push str_SDD2	; 34328
lea eax, [byte esp+07Ch]	; 3432D
push eax	; 34331
call sprintf_	; 34332
add esp, byte 14h	; 34337
mov ebx, ebp	; 3433A
shl ebx, 2	; 3433C
sub ebx, ebp	; 3433F
add ebx, ebx	; 34341
mov eax, dword [esp]	; 34343
add eax, ebx	; 34346
mov dword [dword esp+0A0h], eax	; 34348
cmp byte [byte eax+04h], 0FFh	; 3434F
je short .14	; 34353
cmp byte [byte eax+05h], 0FFh	; 34355
jne near .15	; 34359
.14:
push edi	; 3435F
push esi	; 34360
mov edx, dword [dword esp+0A4h]	; 34361
push edx	; 34368
call sub_91370	; 34369
add esp, byte 0Ch	; 3436E
push edi	; 34371
push esi	; 34372
mov eax, dword [dword esp+0ACh]	; 34373
shl eax, 2	; 3437A
add eax, dword [byte esp+0Ch]	; 3437D
mov ecx, dword [eax]	; 34381
push ecx	; 34383
call sub_91370	; 34384
add esp, byte 0Ch	; 34389
mov ebx, ebp	; 3438C
shl ebx, 2	; 3438E
sub ebx, ebp	; 34391
mov eax, dword [esp]	; 34393
mov al, byte [byte eax+ebx*2+01h]	; 34396
and eax, 0FFh	; 3439A
push eax	; 3439F
push str_D8	; 343A0
lea eax, [byte esp+054h]	; 343A5
push eax	; 343A9
call sprintf_	; 343AA
add esp, byte 0Ch	; 343AF
mov dword [fontcolor], 0FFh	; 343B2
lea eax, [byte edi+01h]	; 343BC
push eax	; 343BF
lea eax, [byte esi+04h]	; 343C0
push eax	; 343C3
lea eax, [byte esp+054h]	; 343C4
push eax	; 343C8
call sub_91964	; 343C9
add esp, byte 0Ch	; 343CE
mov dword [fontcolor], 0C0h	; 343D1
push edi	; 343DB
add esi, byte 3	; 343DC
push esi	; 343DF
lea eax, [byte esp+054h]	; 343E0
jmp near .16	; 343E4
.15:
push edi	; 343E9
push esi	; 343EA
mov eax, dword [dword esp+0ACh]	; 343EB
shl eax, 2	; 343F2
add eax, dword [byte esp+0Ch]	; 343F5
mov ecx, dword [eax]	; 343F9
push ecx	; 343FB
call sub_91370	; 343FC
add esp, byte 0Ch	; 34401
xor eax, eax	; 34404
mov ebx, dword [dword esp+0A0h]	; 34406
mov al, byte [byte ebx+01h]	; 3440D
push eax	; 34410
push str_D8	; 34411
lea eax, [byte esp+054h]	; 34416
push eax	; 3441A
call sprintf_	; 3441B
add esp, byte 0Ch	; 34420
mov dword [fontcolor], 0C0h	; 34423
lea eax, [byte edi+01h]	; 3442D
push eax	; 34430
lea eax, [byte esi+04h]	; 34431
push eax	; 34434
lea eax, [byte esp+054h]	; 34435
push eax	; 34439
call sub_91964	; 3443A
add esp, byte 0Ch	; 3443F
mov dword [fontcolor], 0FFh	; 34442
push edi	; 3444C
lea eax, [byte esi+03h]	; 3444D
push eax	; 34450
lea eax, [byte esp+054h]	; 34451
push eax	; 34455
call sub_91964	; 34456
add esp, byte 0Ch	; 3445B
push edi	; 3445E
push esi	; 3445F
mov ebx, dword [dword esp+0A4h]	; 34460
push ebx	; 34467
call sub_91370	; 34468
add esp, byte 0Ch	; 3446D
mov dword [fontcolor], 0FFh	; 34470
lea eax, [byte edi+031h]	; 3447A
push eax	; 3447D
lea eax, [byte esp+070h]	; 3447E
push eax	; 34482
call fputchar	; 34483
add esp, byte 4	; 34488
sar eax, 1	; 3448B
lea ebx, [byte esi+027h]	; 3448D
sub ebx, eax	; 34490
push ebx	; 34492
lea eax, [byte esp+074h]	; 34493
push eax	; 34497
call sub_91964	; 34498
add esp, byte 0Ch	; 3449D
mov dword [fontcolor], 0C0h	; 344A0
add edi, byte 30h	; 344AA
push edi	; 344AD
lea eax, [byte esp+070h]	; 344AE
push eax	; 344B2
call fputchar	; 344B3
add esp, byte 4	; 344B8
sar eax, 1	; 344BB
add esi, byte 26h	; 344BD
sub esi, eax	; 344C0
push esi	; 344C2
lea eax, [byte esp+074h]	; 344C3
.16:
push eax	; 344C7
call sub_91964	; 344C8
add esp, byte 0Ch	; 344CD
mov eax, ebp	; 344D0
mov ebx, ebp	; 344D2
shl ebx, 2	; 344D4
sub ebx, ebp	; 344D7
add ebx, ebx	; 344D9
add ebx, dword [esp]	; 344DB
xor eax, ebp	; 344DE
mov al, byte [ebx]	; 344E0
mov esi, dword [calselmonth]	; 344E2
cmp eax, esi	; 344E8
jne short .17	; 344EA
xor eax, esi	; 344EC
mov al, byte [byte ebx+01h]	; 344EE
cmp eax, dword [calselday]	; 344F1
jne short .17	; 344F7
mov dword [dword esp+098h], ebp	; 344F9
.17:
inc ebp	; 34500
.18:
cmp ebp, dword [dword esp+0B8h]	; 34501
jl near DrawCalendarDay.5	; 34508
mov ebx, dword [dword esp+098h]	; 3450E
test ebx, ebx	; 34515
jl near .19	; 34517
mov eax, ebx	; 3451D
shl eax, 2	; 3451F
sub eax, ebx	; 34522
add eax, eax	; 34524
add eax, dword [esp]	; 34526
mov al, byte [byte eax+01h]	; 34529
and eax, 0FFh	; 3452C
xor ebx, ebx	; 34531
mov ecx, dword [byte esp+08h]	; 34533
mov bl, byte [dword ecx+monthfirstday]	; 34537
add eax, ebx	; 3453D
lea ebx, [byte eax-01h]	; 3453F
mov ecx, 7	; 34542
mov eax, ebx	; 34547
mov edx, ebx	; 34549
sar edx, 1Fh	; 3454B
idiv ecx	; 3454E
mov esi, edx	; 34550
mov eax, ebx	; 34552
mov edx, ebx	; 34554
sar edx, 1Fh	; 34556
idiv ecx	; 34559
mov esi, dword [nosplit esi*4+calcolx]	; 3455B
mov edi, dword [nosplit eax*4+calrowy]	; 34562
lea eax, [byte esi+04Ch]	; 34569
mov dword [dword esp+090h], eax	; 3456C
lea ebp, [byte edi+03Eh]	; 34573
push dword 0BBh	; 34576
lea eax, [byte edi-01h]	; 3457B
mov dword [dword esp+080h], eax	; 3457E
push eax	; 34585
mov edx, dword [dword esp+098h]	; 34586
push edx	; 3458D
push eax	; 3458E
lea eax, [byte esi-01h]	; 3458F
mov dword [dword esp+090h], eax	; 34592
push eax	; 34599
call sub_B4FAC	; 3459A
add esp, byte 14h	; 3459F
push dword 0BBh	; 345A2
push edi	; 345A7
mov eax, dword [dword esp+098h]	; 345A8
dec eax	; 345AF
mov dword [dword esp+090h], eax	; 345B0
push eax	; 345B7
push edi	; 345B8
push esi	; 345B9
call sub_B4FAC	; 345BA
add esp, byte 14h	; 345BF
push dword 0BBh	; 345C2
push ebp	; 345C7
mov edx, dword [dword esp+088h]	; 345C8
push edx	; 345CF
mov ebx, dword [dword esp+088h]	; 345D0
push ebx	; 345D7
push edx	; 345D8
call sub_B4FAC	; 345D9
add esp, byte 14h	; 345DE
push dword 0BBh	; 345E1
lea eax, [byte ebp-01h]	; 345E6
mov dword [dword esp+090h], eax	; 345E9
push eax	; 345F0
push esi	; 345F1
push edi	; 345F2
push esi	; 345F3
call sub_B4FAC	; 345F4
add esp, byte 14h	; 345F9
push dword 0BBh	; 345FC
push ebp	; 34601
mov edx, dword [dword esp+098h]	; 34602
push edx	; 34609
mov ebx, dword [dword esp+088h]	; 3460A
push ebx	; 34611
push edx	; 34612
call sub_B4FAC	; 34613
add esp, byte 14h	; 34618
push dword 0BBh	; 3461B
mov eax, dword [dword esp+090h]	; 34620
push eax	; 34627
mov edx, dword [dword esp+090h]	; 34628
push edx	; 3462F
push edi	; 34630
push edx	; 34631
call sub_B4FAC	; 34632
add esp, byte 14h	; 34637
push dword 0BBh	; 3463A
push ebp	; 3463F
mov ecx, dword [dword esp+098h]	; 34640
push ecx	; 34647
push ebp	; 34648
mov edi, dword [dword esp+090h]	; 34649
push edi	; 34650
call sub_B4FAC	; 34651
add esp, byte 14h	; 34656
push dword 0BBh	; 34659
mov ebp, dword [dword esp+090h]	; 3465E
push ebp	; 34665
mov eax, dword [dword esp+090h]	; 34666
push eax	; 3466D
push ebp	; 3466E
push esi	; 3466F
call sub_B4FAC	; 34670
add esp, byte 14h	; 34675
.19:
lea eax, [byte esp+0Ch]	; 34678
push eax	; 3467C
call sub_8EA00	; 3467D
add esp, byte 4	; 34682
add esp, 0A8h	; 34685
pop ebp	; 3468B
pop edi	; 3468C
pop esi	; 3468D
ret 10h	; 3468E
CalNextMonth:
push dword 10h	; 34691
call __CHK	; 34696
push ebx	; 3469B
push ecx	; 3469C
push edi	; 3469D
mov dword [calnextslot], CalNextMonth	; 3469E
mov dword [calprevslot], CalPrevMonth	; 346A8
mov ecx, dword [calmonth]	; 346B2
inc ecx	; 346B8
mov dword [calmonth], ecx	; 346B9
cmp ecx, byte 0Ch	; 346BF
jne short .1	; 346C2
xor edi, edi	; 346C4
mov dword [calmonth], edi	; 346C6
.1:
cmp dword [calmonth], byte 6	; 346CC
jne short .2	; 346D3
mov dword [calmonth], 5	; 346D5
.2:
cmp dword [calmonth], byte 5	; 346DF
jne short .3	; 346E6
xor ebx, ebx	; 346E8
mov dword [calnextslot], ebx	; 346EA
.3:
mov dword [calsel], 0FFFFFFFFh	; 346F0
pop edi	; 346FA
pop ecx	; 346FB
pop ebx	; 346FC
ret	; 346FD
CalPrevMonth:
push dword 0Ch	; 346FE
call __CHK	; 34703
push ebx	; 34708
push ecx	; 34709
mov dword [calnextslot], CalNextMonth	; 3470A
mov dword [calprevslot], CalPrevMonth	; 34714
mov ecx, dword [calmonth]	; 3471E
dec ecx	; 34724
mov dword [calmonth], ecx	; 34725
cmp ecx, byte 0FFFFFFFFh	; 3472B
jne short .1	; 3472E
mov dword [calmonth], 0Bh	; 34730
.1:
cmp dword [calmonth], byte 8	; 3473A
jne short .2	; 34741
mov dword [calmonth], 9	; 34743
.2:
cmp dword [calmonth], byte 9	; 3474D
jne short .3	; 34754
xor ebx, ebx	; 34756
mov dword [calprevslot], ebx	; 34758
.3:
mov dword [calsel], 0FFFFFFFFh	; 3475E
pop ecx	; 34768
pop ebx	; 34769
ret	; 3476A
CalReturn:
push dword 8	; 3476B
call __CHK	; 34770
push edx	; 34775
mov edx, 0FFFFFFFFh	; 34776
mov dword [calexit], edx	; 3477B
mov dword [calsel], edx	; 34781
pop edx	; 34787
ret	; 34788
ApplyShapePalette:
push dword 18h	; 34789
call __CHK	; 3478E
push ebx	; 34793
push ecx	; 34794
push edx	; 34795
push str_Pal17	; 34796
push eax	; 3479B
call sub_B30B4	; 3479C
add esp, byte 8	; 347A1
lea edx, [byte eax+010h]	; 347A4
mov ebx, 10h	; 347A7
xor eax, eax	; 347AC
call FadePalStep	; 347AE
pop edx	; 347B3
pop ecx	; 347B4
pop ebx	; 347B5
ret	; 347B6
SetGameSides:
push dword 0Ch	; 347B7
call __CHK	; 347BC
push ecx	; 347C1
push esi	; 347C2
mov esi, eax	; 347C3
mov ecx, edx	; 347C5
mov edx, ebx	; 347C7
shl edx, 2	; 347C9
sub edx, ebx	; 347CC
add edx, edx	; 347CE
add edx, ecx	; 347D0
xor eax, eax	; 347D2
mov al, byte [byte edx+02h]	; 347D4
cmp esi, eax	; 347D7
jne short .1	; 347D9
mov dl, byte [byte edx+03h]	; 347DB
and edx, 0FFh	; 347DE
jmp short .2	; 347E4
.1:
movzx esi, byte [byte edx+03h]	; 347E6
mov edx, eax	; 347EA
.2:
mov eax, edx	; 347EC
shl eax, 4	; 347EE
sub eax, edx	; 347F1
cmp byte [nosplit eax*2+lgteam_17], 1	; 347F3
je short .3	; 347FB
mov edx, 0FFFFFFFFh	; 347FD
.3:
mov eax, ebx	; 34802
shl eax, 2	; 34804
sub eax, ebx	; 34807
add eax, eax	; 34809
add eax, ecx	; 3480B
xor ecx, ecx	; 3480D
mov cl, byte [byte eax+03h]	; 3480F
xor ebx, ebx	; 34812
mov bl, byte [byte eax+02h]	; 34814
mov eax, esi	; 34817
call SetCtlTeams	; 34819
pop esi	; 3481E
pop ecx	; 3481F
ret	; 34820
CalendarScreen:
push dword 7F8h	; 34821
call __CHK	; 34826
push ecx	; 3482B
push esi	; 3482C
push edi	; 3482D
push ebp	; 3482E
sub esp, 7D0h	; 3482F
push eax	; 34835
mov edi, edx	; 34836
mov ebp, ebx	; 34838
mov dword [dword esp+0780h], 0FFFFFFFFh	; 3483A
xor ebx, ebx	; 34845
mov dword [dword esp+07B0h], ebx	; 34847
mov dword [dword esp+079Ch], 0C0h	; 3484E
mov dword [dword esp+07A4h], 0Ch	; 34859
mov dword [dword esp+07A0h], 67h	; 34864
call sub_B4BA8	; 3486F
push byte 0	; 34874
call sub_B392C	; 34876
add esp, byte 4	; 3487B
cmp byte [musicon], 0	; 3487E
je short .1	; 34885
cmp dword [songdata], byte 0	; 34887
je short .1	; 3488E
mov eax, dword [musichandle]	; 34890
mov ebx, 64h	; 34895
mov edx, 3	; 3489A
call sub_8FCDF	; 3489F
.1:
push unk_DF014	; 348A4
push dword 100h	; 348A9
push byte 0	; 348AE
call sub_8FFB0	; 348B0
add esp, byte 0Ch	; 348B5
mov ebx, 10h	; 348B8
mov edx, unk_DF014	; 348BD
mov eax, 1	; 348C2
call FadePalStep	; 348C7
cmp byte [musicon], 0	; 348CC
je short .3	; 348D3
cmp dword [songdata], byte 0	; 348D5
je short .3	; 348DC
.2:
mov eax, dword [musicslot-3]	; 348DE
sar eax, 18h	; 348E3
mov edx, 3	; 348E6
call sub_8FC8A	; 348EB
test eax, eax	; 348F0
je short CalendarScreen.2	; 348F2
mov ecx, dword [songdata]	; 348F4
push ecx	; 348FA
call sub_8D2F0	; 348FB
add esp, byte 4	; 34900
xor esi, esi	; 34903
mov dword [songdata], esi	; 34905
.3:
call ShowLoadingScreen	; 3490B
mov dword [teamstatscb], CalTeamStatsScreen	; 34910
mov dword [skaterstatscb], CalSkaterStatsScreen	; 3491A
mov dword [goaliestatscb], CalGoalieStatsScreen	; 34924
mov dword [standingscb], CalStandingsScreen	; 3492E
mov dword [standingsmenucb], CalStandingsMenu	; 34938
push dword 0FFh	; 34942
mov ecx, 0C0h	; 34947
mov ebx, 67h	; 3494C
mov edx, ecx	; 34951
mov eax, 0Ch	; 34953
call SetDialogColors	; 34958
xor edx, edx	; 3495D
mov word [dword esp+07B8h], dx	; 3495F
mov dword [calsel], 0FFFFFFFFh	; 34967
xor edx, edx	; 34971
mov dword [calexit], edx	; 34973
mov dword [dword_DDD2C], edx	; 34979
mov eax, dword [mainfont]	; 3497F
mov dword [dword esp+07ACh], eax	; 34984
xor ecx, ecx	; 3498B
mov ebx, str_Calendar	; 3498D
cmp byte [fileoncd+01C1h], 1	; 34992
jne short .4	; 34999
mov edx, dword [cddriveptr]	; 3499B
jmp short .5	; 349A1
.4:
xor edx, edx	; 349A3
.5:
lea eax, [dword esp+06F8h]	; 349A5
call MakePath	; 349AC
push byte 20h	; 349B1
lea eax, [dword esp+06FCh]	; 349B3
push eax	; 349BA
call sub_8E83C	; 349BB
add esp, byte 8	; 349C0
mov dword [calendarshapes], eax	; 349C3
xor ecx, ecx	; 349C8
mov ebx, str_Callogo	; 349CA
cmp byte [fileoncd+01C2h], 1	; 349CF
jne short .6	; 349D6
mov edx, dword [cddriveptr]	; 349D8
jmp short .7	; 349DE
.6:
xor edx, edx	; 349E0
.7:
lea eax, [dword esp+06F8h]	; 349E2
call MakePath	; 349E9
push byte 20h	; 349EE
lea eax, [dword esp+06FCh]	; 349F0
push eax	; 349F7
call sub_8E83C	; 349F8
add esp, byte 8	; 349FD
mov dword [dword esp+078Ch], eax	; 34A00
xor ebx, ebx	; 34A07
mov word [dword esp+07CCh], bx	; 34A09
jmp short .9	; 34A11
.8:
mov eax, dword [dword esp+07CAh]	; 34A13
sar eax, 10h	; 34A1A
mov dl, byte [dword esp+07CCh]	; 34A1D
mov byte [byte esp+eax+04h], dl	; 34A24
mov eax, ecx	; 34A28
inc eax	; 34A2A
mov word [dword esp+07CCh], ax	; 34A2B
.9:
mov ecx, dword [dword esp+07CCh]	; 34A33
cmp cx, 100h	; 34A3A
jl short CalendarScreen.8	; 34A3F
lea eax, [byte esp+04h]	; 34A41
push eax	; 34A45
call sub_B4DD4	; 34A46
add esp, byte 4	; 34A4B
xor esi, esi	; 34A4E
mov word [dword esp+07CCh], si	; 34A50
jmp short .11	; 34A58
.10:
mov esi, dword [dword esp+07CAh]	; 34A5A
sar esi, 10h	; 34A61
mov eax, dword [nosplit esi*4+crestnames]	; 34A64
push eax	; 34A6B
mov edx, dword [dword esp+0790h]	; 34A6C
push edx	; 34A73
call sub_B30B4	; 34A74
add esp, byte 8	; 34A79
mov dword [dword esp+esi*4+0690h], eax	; 34A7C
inc word [dword esp+07CCh]	; 34A83
.11:
cmp word [dword esp+07CCh], byte 1Ah	; 34A8B
jl short CalendarScreen.10	; 34A94
mov ebx, dword [leaguedbnames+18h]	; 34A96
mov ecx, edi	; 34A9C
mov edx, dword [esp]	; 34A9E
lea eax, [dword esp+06F8h]	; 34AA1
call MakePath	; 34AA8
lea edx, [dword esp+0780h]	; 34AAD
lea eax, [dword esp+06F8h]	; 34AB4
call FileOpenRead	; 34ABB
mov esi, eax	; 34AC0
test ax, ax	; 34AC2
jne short .12	; 34AC5
mov ecx, 2	; 34AC7
xor ebx, ebx	; 34ACC
lea edx, [dword esp+07C0h]	; 34ACE
mov eax, dword [dword esp+0780h]	; 34AD5
call FileReadAt	; 34ADC
mov esi, eax	; 34AE1
.12:
test si, si	; 34AE3
jne near .22	; 34AE6
mov dword [calmonth], 0FFFFFFFFh	; 34AEC
mov edi, 5	; 34AF6
mov ebx, 0FFFFFFFFh	; 34AFB
mov dword [dword esp+07BCh], ebx	; 34B00
mov word [dword esp+07C4h], bx	; 34B07
mov word [dword esp+07CCh], si	; 34B0F
jmp near .20	; 34B17
.13:
mov ebx, dword [dword esp+07CAh]	; 34B1C
sar ebx, 10h	; 34B23
mov eax, dword [dword esp+07B6h]	; 34B26
sar eax, 10h	; 34B2D
mov ecx, eax	; 34B30
shl ecx, 2	; 34B32
sub ecx, eax	; 34B35
add ecx, ecx	; 34B37
lea edx, [dword esp+0304h]	; 34B39
add edx, ecx	; 34B40
mov eax, dword [dword esp+0780h]	; 34B42
call ReadSchedGame	; 34B49
mov esi, eax	; 34B4E
test ax, ax	; 34B50
jne near .19	; 34B53
mov eax, dword [dword esp+07CCh]	; 34B59
cmp ax, word [dword esp+07C0h]	; 34B60
jne near .16	; 34B68
cmp byte [dword esp+ecx+0306h], 0FFh	; 34B6E
je short .14	; 34B76
cmp byte [dword esp+ecx+0307h], 0FFh	; 34B78
je short .14	; 34B80
movzx di, byte [dword esp+ecx+0304h]	; 34B82
dec edi	; 34B8B
xor eax, eax	; 34B8C
mov al, byte [dword esp+ecx+0304h]	; 34B8E
mov dword [calselmonth], eax	; 34B95
xor eax, eax	; 34B9A
mov al, byte [dword esp+ecx+0305h]	; 34B9C
jmp short .15	; 34BA3
.14:
mov ebx, dword [dword esp+07B6h]	; 34BA5
sar ebx, 10h	; 34BAC
lea edx, [byte ebx-01h]	; 34BAF
mov eax, edx	; 34BB2
shl eax, 2	; 34BB4
sub eax, edx	; 34BB7
movzx di, byte [dword esp+eax*2+0304h]	; 34BB9
dec edi	; 34BC2
mov eax, ebx	; 34BC3
shl eax, 2	; 34BC5
sub eax, ebx	; 34BC8
xor edx, edx	; 34BCA
mov dl, byte [dword esp+eax*2+0304h]	; 34BCC
mov dword [calselmonth], edx	; 34BD3
mov al, byte [dword esp+eax*2+0305h]	; 34BD9
and eax, 0FFh	; 34BE0
.15:
mov dword [calselday], eax	; 34BE5
.16:
mov edx, dword [dword esp+07B6h]	; 34BEA
sar edx, 10h	; 34BF1
mov eax, edx	; 34BF4
shl eax, 2	; 34BF6
sub eax, edx	; 34BF9
add eax, eax	; 34BFB
xor edx, edx	; 34BFD
mov dl, byte [dword esp+eax+0306h]	; 34BFF
cmp edx, ebp	; 34C06
je short .17	; 34C08
mov al, byte [dword esp+eax+0307h]	; 34C0A
and eax, 0FFh	; 34C11
cmp eax, ebp	; 34C16
jne near .19	; 34C18
.17:
mov edx, dword [dword esp+07B6h]	; 34C1E
sar edx, 10h	; 34C25
mov eax, edx	; 34C28
shl eax, 2	; 34C2A
sub eax, edx	; 34C2D
add eax, eax	; 34C2F
mov dh, byte [dword esp+eax+0304h]	; 34C31
cmp dh, 0FFh	; 34C38
je near .19	; 34C3B
cmp byte [dword esp+eax+0305h], 0FFh	; 34C41
je short .19	; 34C49
mov bh, byte [dword esp+eax+0308h]	; 34C4B
cmp bh, 0FFh	; 34C52
jne short .18	; 34C55
cmp bh, byte [dword esp+eax+0309h]	; 34C57
jne short .18	; 34C5E
cmp dword [calmonth], byte 0	; 34C60
jge short .18	; 34C67
mov al, dh	; 34C69
and eax, 0FFh	; 34C6B
dec eax	; 34C70
mov dword [calmonth], eax	; 34C71
mov eax, dword [dword esp+07CCh]	; 34C76
mov dword [dword esp+07BCh], eax	; 34C7D
mov eax, dword [dword esp+07B8h]	; 34C84
mov word [dword esp+07C4h], ax	; 34C8B
.18:
mov eax, dword [dword esp+07B6h]	; 34C93
sar eax, 10h	; 34C9A
mov edx, dword [dword esp+07CCh]	; 34C9D
mov word [dword esp+eax*2+05ACh], dx	; 34CA4
inc word [dword esp+07B8h]	; 34CAC
.19:
inc word [dword esp+07CCh]	; 34CB4
.20:
cmp word [dword esp+07CCh], 4ADh	; 34CBC
jge short .21	; 34CC6
test si, si	; 34CC8
je near CalendarScreen.13	; 34CCB
.21:
cmp dword [calmonth], byte 0	; 34CD1
jge short .22	; 34CD8
movsx eax, di	; 34CDA
mov dword [calmonth], eax	; 34CDD
.22:
test si, si	; 34CE2
je short .23	; 34CE5
call FadeOutPalCycle	; 34CE7
.23:
lea eax, [dword esp+0780h]	; 34CEC
call FileClose	; 34CF3
cmp word [dword esp+07BCh], byte 0	; 34CF8
jl short .24	; 34D01
test si, si	; 34D03
jne short .24	; 34D06
mov ecx, dword [dword esp+07C2h]	; 34D08
sar ecx, 10h	; 34D0F
mov ebx, ecx	; 34D12
lea edx, [dword esp+0304h]	; 34D14
mov eax, ebp	; 34D1B
call SetGameSides	; 34D1D
mov edx, ecx	; 34D22
mov eax, ecx	; 34D24
shl eax, 2	; 34D26
sub eax, ecx	; 34D29
xor edx, ecx	; 34D2B
mov dl, byte [dword esp+eax*2+0304h]	; 34D2D
mov dword [calselmonth], edx	; 34D34
mov al, byte [dword esp+eax*2+0305h]	; 34D3A
and eax, 0FFh	; 34D41
mov dword [calselday], eax	; 34D46
mov eax, dword [dword esp+ecx*2+05AAh]	; 34D4B
sar eax, 10h	; 34D52
mov dword [calsel], eax	; 34D55
.24:
test si, si	; 34D5A
jne near .83	; 34D5D
cmp dword [calmonth], byte 5	; 34D63
jne short .25	; 34D6A
xor eax, eax	; 34D6C
mov dword [calnextslot], eax	; 34D6E
jmp short .26	; 34D73
.25:
mov dword [calnextslot], CalNextMonth	; 34D75
.26:
cmp dword [calmonth], byte 9	; 34D7F
jne short .27	; 34D86
xor ecx, ecx	; 34D88
mov dword [calprevslot], ecx	; 34D8A
jmp short .28	; 34D90
.27:
mov dword [calprevslot], CalPrevMonth	; 34D92
.28:
mov ax, word [calmonth]	; 34D9C
mov word [dword esp+07D0h], ax	; 34DA2
call sub_B4BA8	; 34DAA
mov esi, calmenubar	; 34DAF
mov dword [dword esp+0730h], esi	; 34DB4
mov edi, 3	; 34DBB
mov dword [dword esp+0748h], edi	; 34DC0
xor eax, eax	; 34DC7
mov dword [dword esp+0734h], eax	; 34DC9
mov dword [dword esp+073Ch], eax	; 34DD0
mov dword [dword esp+0740h], eax	; 34DD7
mov dword [dword esp+0754h], eax	; 34DDE
mov dword [dword esp+0758h], eax	; 34DE5
mov dword [dword esp+0718h], eax	; 34DEC
mov dword [dword esp+071Ch], eax	; 34DF3
call FadeOutPalCycle	; 34DFA
call sub_B4BA8	; 34DFF
mov edx, dword [dword esp+07A0h]	; 34E04
push edx	; 34E0B
mov ecx, dword [dword esp+07A8h]	; 34E0C
mov ebx, dword [dword esp+07A0h]	; 34E13
mov edx, edi	; 34E1A
mov eax, esi	; 34E1C
call DrawMenuBar	; 34E1E
mov ebx, dword [calendarshapes]	; 34E23
push ebx	; 34E29
mov ecx, dword [dword esp+07B0h]	; 34E2A
push ecx	; 34E31
push ebp	; 34E32
mov eax, dword [dword esp+07C2h]	; 34E33
sar eax, 10h	; 34E3A
push eax	; 34E3D
mov eax, dword [calmonth]	; 34E3E
lea ecx, [dword esp+0314h]	; 34E43
mov ebx, dword [dword esp+07B8h]	; 34E4A
lea edx, [dword esp+06A0h]	; 34E51
call DrawCalendarDay	; 34E58
cmp byte [musicon], 0	; 34E5D
je short .31	; 34E64
cmp dword [songdata], byte 0	; 34E66
jne short .31	; 34E6D
mov ecx, str_Iff9	; 34E6F
mov ebx, str_Calendar	; 34E74
cmp byte [fileoncd+01E2h], 1	; 34E79
jne short .29	; 34E80
mov edx, dword [cddriveptr]	; 34E82
jmp short .30	; 34E88
.29:
xor edx, edx	; 34E8A
.30:
lea eax, [dword esp+06F8h]	; 34E8C
call MakePath	; 34E93
lea eax, [dword esp+06F8h]	; 34E98
call sub_8F98F	; 34E9F
mov dword [songdata], eax	; 34EA4
test eax, eax	; 34EA9
je short .31	; 34EAB
test byte [gameopts], 40h	; 34EAD
je short .31	; 34EB4
mov edx, dword [musichandle]	; 34EB6
mov ecx, 4Ch	; 34EBC
mov ebx, 3	; 34EC1
call sub_8FB8E	; 34EC6
.31:
mov eax, dword [calendarshapes]	; 34ECB
call ApplyShapePalette	; 34ED0
mov eax, dword [pointerspr]	; 34ED5
mov edx, dword [byte eax+02h]	; 34EDA
sar edx, 10h	; 34EDD
shl edx, 2	; 34EE0
mov eax, dword [byte eax+04h]	; 34EE3
sar eax, 10h	; 34EE6
inc eax	; 34EE9
add edx, byte 4	; 34EEA
imul eax, edx	; 34EED
add eax, byte 11h	; 34EF0
push byte 20h	; 34EF3
push eax	; 34EF5
push str_Pointer8	; 34EF6
call sub_8CCA8	; 34EFB
mov dword [dword esp+0794h], eax	; 34F00
add esp, byte 0Ch	; 34F07
mov dword [dword esp+0794h], eax	; 34F0A
mov esi, dword [pointerspr]	; 34F11
mov edi, eax	; 34F17
movsd	; 34F19
movsd	; 34F1A
movsd	; 34F1B
movsd	; 34F1C
movsb	; 34F1D
mov eax, dword [pointerspr]	; 34F1E
mov ax, word [byte eax+04h]	; 34F23
inc eax	; 34F27
mov edx, dword [dword esp+0788h]	; 34F28
mov word [byte edx+04h], ax	; 34F2F
mov eax, dword [pointerspr]	; 34F33
mov ax, word [byte eax+06h]	; 34F38
inc eax	; 34F3C
mov word [byte edx+06h], ax	; 34F3D
lea eax, [dword esp+0774h]	; 34F41
push eax	; 34F48
lea eax, [dword esp+077Ch]	; 34F49
push eax	; 34F50
lea eax, [dword esp+0784h]	; 34F51
push eax	; 34F58
call sub_B2DCA	; 34F59
add esp, byte 0Ch	; 34F5E
mov eax, dword [dword esp+0778h]	; 34F61
mov dword [dword esp+0770h], eax	; 34F68
mov eax, dword [dword esp+0774h]	; 34F6F
mov dword [dword esp+076Ch], eax	; 34F76
push eax	; 34F7D
mov eax, dword [dword esp+077Ch]	; 34F7E
push eax	; 34F85
mov edx, dword [dword esp+0790h]	; 34F86
push edx	; 34F8D
call sub_91400	; 34F8E
add esp, byte 0Ch	; 34F93
mov ebx, dword [dword esp+0774h]	; 34F96
push ebx	; 34F9D
mov ecx, dword [dword esp+077Ch]	; 34F9E
push ecx	; 34FA5
mov esi, dword [pointerspr]	; 34FA6
push esi	; 34FAC
call sub_91370	; 34FAD
add esp, byte 0Ch	; 34FB2
call ClearInputQueue	; 34FB5
.32:
xor ecx, ecx	; 34FBA
.33:
call GetInputEvent	; 34FBC
mov esi, eax	; 34FC1
test eax, eax	; 34FC3
je short .34	; 34FC5
lea ebx, [dword esp+076Ch]	; 34FC7
lea edx, [dword esp+0770h]	; 34FCE
call dword [ptrupdatefn]	; 34FD5
mov ecx, eax	; 34FDB
.34:
test esi, esi	; 34FDD
je short .35	; 34FDF
test cl, 2	; 34FE1
je short CalendarScreen.33	; 34FE4
.35:
test cl, 2	; 34FE6
jne short .37	; 34FE9
mov eax, dword [dword esp+0770h]	; 34FEB
cmp eax, dword [dword esp+0778h]	; 34FF2
jne short .36	; 34FF9
mov eax, dword [dword esp+076Ch]	; 34FFB
cmp eax, dword [dword esp+0774h]	; 35002
je near .82	; 35009
.36:
mov ebx, dword [dword esp+0774h]	; 3500F
push ebx	; 35016
mov ecx, dword [dword esp+077Ch]	; 35017
push ecx	; 3501E
mov esi, dword [dword esp+079Ch]	; 3501F
push esi	; 35026
call sub_903F0	; 35027
add esp, byte 0Ch	; 3502C
mov edi, dword [dword esp+076Ch]	; 3502F
push edi	; 35036
mov eax, dword [dword esp+0774h]	; 35037
push eax	; 3503E
push esi	; 3503F
call sub_91400	; 35040
add esp, byte 0Ch	; 35045
mov ebx, dword [dword esp+076Ch]	; 35048
push ebx	; 3504F
mov ecx, dword [dword esp+0774h]	; 35050
push ecx	; 35057
mov esi, dword [pointerspr]	; 35058
push esi	; 3505E
jmp near .80	; 3505F
.37:
lea eax, [dword esp+0764h]	; 35064
push eax	; 3506B
lea eax, [dword esp+076Ch]	; 3506C
push eax	; 35073
lea eax, [dword esp+0720h]	; 35074
push eax	; 3507B
lea eax, [dword esp+0754h]	; 3507C
push eax	; 35083
mov ecx, dword [dword esp+07C0h]	; 35084
lea ebx, [dword esp+0740h]	; 3508B
mov edx, dword [dword esp+077Ch]	; 35092
mov eax, dword [dword esp+0780h]	; 35099
call MenuHitTest	; 350A0
test eax, eax	; 350A5
je near .65	; 350A7
mov edx, dword [dword esp+0768h]	; 350AD
shl edx, 2	; 350B4
mov eax, dword [dword esp+0764h]	; 350B7
shl eax, 5	; 350BE
mov ebx, dword [dword esp+edx+0730h]	; 350C1
add eax, ebx	; 350C8
cmp dword [byte eax+014h], byte 0	; 350CA
je near .50	; 350CE
mov eax, dword [dword esp+0764h]	; 350D4
cmp eax, dword [dword esp+edx+0754h]	; 350DB
jne near .45	; 350E2
mov ebx, dword [dword esp+0774h]	; 350E8
push ebx	; 350EF
mov ecx, dword [dword esp+077Ch]	; 350F0
push ecx	; 350F7
mov esi, dword [dword esp+079Ch]	; 350F8
push esi	; 350FF
call sub_903F0	; 35100
add esp, byte 0Ch	; 35105
mov eax, dword [dword esp+07B0h]	; 35108
mov word [dword esp+07CCh], ax	; 3510F
jmp short .40	; 35117
.38:
mov esi, dword [dword esp+07CAh]	; 35119
sar esi, 10h	; 35120
mov edi, esi	; 35123
shl edi, 2	; 35125
mov eax, dword [dword esp+edi+073Ch]	; 35128
test eax, eax	; 3512F
je short .39	; 35131
mov edx, dword [dword esp+esi*8+071Ch]	; 35133
push edx	; 3513A
mov ebx, dword [dword esp+esi*8+071Ch]	; 3513B
push ebx	; 35142
push eax	; 35143
call sub_903F0	; 35144
add esp, byte 0Ch	; 35149
xor eax, eax	; 3514C
mov dword [dword esp+esi*8+0718h], eax	; 3514E
mov dword [dword esp+esi*8+071Ch], eax	; 35155
mov ebx, dword [dword esp+edi+073Ch]	; 3515C
push ebx	; 35163
call jctime	; 35164
add esp, byte 4	; 35169
.39:
dec word [dword esp+07CCh]	; 3516C
.40:
cmp word [dword esp+07CCh], byte 0	; 35174
jge short CalendarScreen.38	; 3517D
xor esi, esi	; 3517F
mov dword [dword esp+07B0h], esi	; 35181
mov eax, dword [dword esp+0768h]	; 35188
mov edx, dword [dword esp+0764h]	; 3518F
shl edx, 5	; 35196
mov eax, dword [dword esp+eax*4+0730h]	; 35199
call dword [byte edx+eax+014h]	; 351A0
mov esi, eax	; 351A4
lea eax, [byte esp+04h]	; 351A6
push eax	; 351AA
call sub_B4DD4	; 351AB
add esp, byte 4	; 351B0
xor edi, edi	; 351B3
mov dword [dword esp+0734h], edi	; 351B5
mov dword [dword esp+073Ch], edi	; 351BC
mov dword [dword esp+0740h], edi	; 351C3
mov dword [dword esp+0758h], edi	; 351CA
mov dword [dword esp+074Ch], edi	; 351D1
cmp esi, byte 1	; 351D8
jne short .42	; 351DB
mov esi, dword [dword esp+0794h]	; 351DD
push esi	; 351E4
call jctime	; 351E5
add esp, byte 4	; 351EA
cmp byte [musicon], 0	; 351ED
je short .41	; 351F4
cmp dword [songdata], byte 0	; 351F6
je short .41	; 351FD
mov eax, dword [musichandle]	; 351FF
mov ebx, 64h	; 35204
mov edx, 3	; 35209
call sub_8FCDF	; 3520E
.41:
xor eax, eax	; 35213
jmp near .x	; 35215
.42:
mov esi, dword [dword esp+0774h]	; 3521A
push esi	; 35221
mov edi, dword [dword esp+077Ch]	; 35222
push edi	; 35229
call MouseSetPos	; 3522A
add esp, byte 8	; 3522F
mov eax, dword [dword esp+0778h]	; 35232
mov dword [dword esp+0770h], eax	; 35239
mov eax, dword [dword esp+0774h]	; 35240
mov dword [dword esp+076Ch], eax	; 35247
call ClearInputQueue	; 3524E
mov eax, dword [dword esp+07CEh]	; 35253
sar eax, 10h	; 3525A
cmp eax, dword [calmonth]	; 3525D
je short .43	; 35263
call sub_B4BA8	; 35265
mov ebx, dword [dword esp+07A0h]	; 3526A
push ebx	; 35271
mov ecx, dword [dword esp+07A8h]	; 35272
mov ebx, dword [dword esp+07A0h]	; 35279
mov edx, 3	; 35280
mov eax, calmenubar	; 35285
call DrawMenuBar	; 3528A
mov ecx, dword [calendarshapes]	; 3528F
push ecx	; 35295
mov esi, dword [dword esp+07B0h]	; 35296
push esi	; 3529D
push ebp	; 3529E
mov eax, dword [dword esp+07C2h]	; 3529F
sar eax, 10h	; 352A6
push eax	; 352A9
mov eax, dword [calmonth]	; 352AA
lea ecx, [dword esp+0314h]	; 352AF
mov ebx, dword [dword esp+07B8h]	; 352B6
lea edx, [dword esp+06A0h]	; 352BD
call DrawCalendarDay	; 352C4
.43:
cmp dword [dword_DDD2C], byte 0	; 352C9
je short .44	; 352D0
call sub_B4BA8	; 352D2
mov eax, dword [dword esp+07A0h]	; 352D7
push eax	; 352DE
mov ecx, dword [dword esp+07A8h]	; 352DF
mov ebx, dword [dword esp+07A0h]	; 352E6
mov edx, 3	; 352ED
mov eax, calmenubar	; 352F2
call DrawMenuBar	; 352F7
mov edx, dword [calendarshapes]	; 352FC
push edx	; 35302
mov ebx, dword [dword esp+07B0h]	; 35303
push ebx	; 3530A
push ebp	; 3530B
mov eax, dword [dword esp+07C2h]	; 3530C
sar eax, 10h	; 35313
push eax	; 35316
mov eax, dword [calmonth]	; 35317
lea ecx, [dword esp+0314h]	; 3531C
mov ebx, dword [dword esp+07B8h]	; 35323
lea edx, [dword esp+06A0h]	; 3532A
call DrawCalendarDay	; 35331
mov eax, dword [calendarshapes]	; 35336
call ApplyShapePalette	; 3533B
xor ecx, ecx	; 35340
mov dword [dword_DDD2C], ecx	; 35342
.44:
mov ax, word [calmonth]	; 35348
mov word [dword esp+07D0h], ax	; 3534E
jmp near .79	; 35356
.45:
mov ecx, dword [dword esp+0774h]	; 3535B
push ecx	; 35362
mov esi, dword [dword esp+077Ch]	; 35363
push esi	; 3536A
mov edi, dword [dword esp+079Ch]	; 3536B
push edi	; 35372
call sub_903F0	; 35373
add esp, byte 0Ch	; 35378
mov eax, dword [dword esp+07B0h]	; 3537B
cmp eax, dword [dword esp+0768h]	; 35382
je near .49	; 35389
mov eax, dword [dword esp+07B0h]	; 3538F
mov word [dword esp+07CCh], ax	; 35396
jmp short .48	; 3539E
.46:
mov esi, edi	; 353A0
shl esi, 2	; 353A2
xor ecx, ecx	; 353A5
mov dword [dword esp+esi+0754h], ecx	; 353A7
mov eax, dword [dword esp+esi+073Ch]	; 353AE
test eax, eax	; 353B5
je short .47	; 353B7
mov edx, dword [dword esp+edi*8+071Ch]	; 353B9
push edx	; 353C0
mov ebx, dword [dword esp+edi*8+071Ch]	; 353C1
push ebx	; 353C8
push eax	; 353C9
call sub_903F0	; 353CA
add esp, byte 0Ch	; 353CF
xor eax, eax	; 353D2
mov dword [dword esp+edi*8+071Ch], eax	; 353D4
mov dword [dword esp+edi*8+0718h], eax	; 353DB
mov edx, dword [dword esp+esi+073Ch]	; 353E2
push edx	; 353E9
call jctime	; 353EA
add esp, byte 4	; 353EF
xor ebx, ebx	; 353F2
mov dword [dword esp+esi+073Ch], ebx	; 353F4
mov dword [dword esp+esi+0730h], ebx	; 353FB
mov dword [dword esp+esi+0748h], ebx	; 35402
.47:
dec word [dword esp+07CCh]	; 35409
.48:
mov edi, dword [dword esp+07CAh]	; 35411
sar edi, 10h	; 35418
mov ebx, dword [dword esp+0768h]	; 3541B
cmp edi, ebx	; 35422
jg near CalendarScreen.46	; 35424
mov dword [dword esp+07B0h], ebx	; 3542A
.49:
mov eax, dword [dword esp+07A0h]	; 35431
push eax	; 35438
mov edx, dword [dword esp+07A8h]	; 35439
push edx	; 35440
mov eax, dword [dword esp+0770h]	; 35441
mov ebx, dword [dword esp+eax*8+0724h]	; 35448
mov edx, dword [dword esp+eax*8+0720h]	; 3544F
mov ecx, dword [dword esp+eax*4+075Ch]	; 35456
shl ecx, 5	; 3545D
mov eax, dword [dword esp+eax*4+0738h]	; 35460
add eax, ecx	; 35467
mov ecx, dword [dword esp+07A4h]	; 35469
call DrawMenuItemSel	; 35470
mov edx, dword [dword esp+0768h]	; 35475
mov eax, dword [dword esp+0764h]	; 3547C
mov dword [dword esp+edx*4+0754h], eax	; 35483
mov ebx, dword [dword esp+07A0h]	; 3548A
push ebx	; 35491
mov ecx, dword [dword esp+07A8h]	; 35492
push ecx	; 35499
mov ebx, dword [dword esp+edx*8+0724h]	; 3549A
mov eax, dword [dword esp+edx*8+0720h]	; 354A1
mov esi, dword [dword esp+edx*4+075Ch]	; 354A8
shl esi, 5	; 354AF
mov edx, dword [dword esp+edx*4+0738h]	; 354B2
add esi, edx	; 354B9
mov ecx, dword [dword esp+07A4h]	; 354BB
mov edx, eax	; 354C2
mov eax, esi	; 354C4
jmp near .64	; 354C6
.50:
cmp dword [byte eax+018h], byte 0	; 354CB
je near .59	; 354CF
mov ebx, dword [dword esp+0774h]	; 354D5
push ebx	; 354DC
mov ecx, dword [dword esp+077Ch]	; 354DD
push ecx	; 354E4
mov esi, dword [dword esp+079Ch]	; 354E5
push esi	; 354EC
call sub_903F0	; 354ED
add esp, byte 0Ch	; 354F2
mov eax, dword [dword esp+07B0h]	; 354F5
cmp eax, dword [dword esp+0768h]	; 354FC
je near .54	; 35503
mov eax, dword [dword esp+07B0h]	; 35509
mov word [dword esp+07CCh], ax	; 35510
jmp short .53	; 35518
.51:
mov esi, edi	; 3551A
shl esi, 2	; 3551C
xor ebx, ebx	; 3551F
mov dword [dword esp+esi+0754h], ebx	; 35521
mov ecx, dword [dword esp+esi+073Ch]	; 35528
test ecx, ecx	; 3552F
je short .52	; 35531
mov eax, dword [dword esp+edi*8+071Ch]	; 35533
push eax	; 3553A
mov edx, dword [dword esp+edi*8+071Ch]	; 3553B
push edx	; 35542
push ecx	; 35543
call sub_903F0	; 35544
add esp, byte 0Ch	; 35549
xor ecx, ecx	; 3554C
mov dword [dword esp+edi*8+0718h], ecx	; 3554E
mov dword [dword esp+edi*8+071Ch], ecx	; 35555
mov edx, dword [dword esp+esi+073Ch]	; 3555C
push edx	; 35563
call jctime	; 35564
add esp, byte 4	; 35569
xor ebx, ebx	; 3556C
mov dword [dword esp+esi+073Ch], ebx	; 3556E
mov dword [dword esp+esi+0730h], ebx	; 35575
mov dword [dword esp+esi+0748h], ebx	; 3557C
.52:
dec word [dword esp+07CCh]	; 35583
.53:
mov edi, dword [dword esp+07CAh]	; 3558B
sar edi, 10h	; 35592
mov edx, dword [dword esp+0768h]	; 35595
cmp edi, edx	; 3559C
jg near CalendarScreen.51	; 3559E
mov dword [dword esp+07B0h], edx	; 355A4
.54:
mov eax, dword [dword esp+07A0h]	; 355AB
push eax	; 355B2
mov edx, dword [dword esp+07A8h]	; 355B3
push edx	; 355BA
mov edi, dword [dword esp+07B8h]	; 355BB
mov ebx, dword [dword esp+edi*8+0724h]	; 355C2
mov edx, dword [dword esp+edi*8+0720h]	; 355C9
mov eax, dword [dword esp+edi*4+075Ch]	; 355D0
shl eax, 5	; 355D7
mov ecx, dword [dword esp+edi*4+0738h]	; 355DA
add eax, ecx	; 355E1
mov ecx, dword [dword esp+07A4h]	; 355E3
call DrawMenuItemSel	; 355EA
mov eax, dword [dword esp+0764h]	; 355EF
mov dword [dword esp+edi*4+0754h], eax	; 355F6
mov eax, dword [dword esp+07A0h]	; 355FD
push eax	; 35604
mov edx, dword [dword esp+07A8h]	; 35605
push edx	; 3560C
mov ebx, dword [dword esp+edi*8+0724h]	; 3560D
mov edx, dword [dword esp+edi*8+0720h]	; 35614
mov eax, dword [dword esp+076Ch]	; 3561B
shl eax, 5	; 35622
mov ecx, dword [dword esp+edi*4+0738h]	; 35625
add eax, ecx	; 3562C
mov ecx, dword [dword esp+07A4h]	; 3562E
call DrawMenuItemNorm	; 35635
mov eax, dword [dword esp+0768h]	; 3563A
mov ecx, dword [dword esp+0764h]	; 35641
shl ecx, 5	; 35648
mov ebx, dword [dword esp+eax*4+0730h]	; 3564B
lea esi, [byte edi+01h]	; 35652
mov dword [dword esp+07B0h], esi	; 35655
mov ebx, dword [byte ecx+ebx+018h]	; 3565C
mov dword [dword esp+esi*4+0730h], ebx	; 35660
mov eax, dword [dword esp+eax*4+0730h]	; 35667
add eax, ecx	; 3566E
mov ebx, dword [byte eax+01Ch]	; 35670
mov dword [dword esp+esi*4+0748h], ebx	; 35673
cmp esi, byte 1	; 3567A
je short .55	; 3567D
mov edx, dword [byte eax+08h]	; 3567F
jmp short .56	; 35682
.55:
mov edx, dword [eax]	; 35684
.56:
mov eax, dword [dword esp+07B0h]	; 35686
mov ebx, dword [dword esp+eax*8+0710h]	; 3568D
add edx, ebx	; 35694
mov dword [dword esp+eax*8+0718h], edx	; 35696
mov edx, dword [dword esp+0764h]	; 3569D
shl edx, 5	; 356A4
mov eax, dword [dword esp+0768h]	; 356A7
shl eax, 2	; 356AE
cmp dword [dword esp+07B0h], byte 1	; 356B1
je short .57	; 356B9
mov eax, dword [dword esp+eax+0730h]	; 356BB
mov eax, dword [byte edx+eax+04h]	; 356C2
jmp short .58	; 356C6
.57:
mov eax, dword [dword esp+eax+0730h]	; 356C8
mov eax, dword [byte edx+eax+0Ch]	; 356CF
.58:
mov edx, dword [dword esp+07B0h]	; 356D3
shl edx, 3	; 356DA
mov dword [dword esp+0790h], edx	; 356DD
mov esi, dword [dword esp+edx+0714h]	; 356E4
add eax, esi	; 356EB
mov dword [dword esp+edx+071Ch], eax	; 356ED
mov eax, dword [dword esp+07B0h]	; 356F4
shl eax, 2	; 356FB
mov dword [dword esp+0798h], eax	; 356FE
mov edx, dword [dword esp+eax+0748h]	; 35705
shl edx, 5	; 3570C
mov eax, dword [dword esp+eax+0730h]	; 3570F
mov ebx, dword [byte edx+eax-018h]	; 35716
sub ebx, dword [eax]	; 3571A
inc ebx	; 3571C
mov dword [dword esp+0760h], ebx	; 3571D
mov edx, dword [byte edx+eax-014h]	; 35724
sub edx, dword [byte eax+04h]	; 35728
inc edx	; 3572B
mov dword [dword esp+0784h], edx	; 3572C
push byte 20h	; 35733
mov eax, dword [dword esp+0764h]	; 35735
shl eax, 2	; 3573C
imul eax, edx	; 3573F
add eax, byte 11h	; 35742
push eax	; 35745
push str_Menubuff5	; 35746
call sub_8CCA8	; 3574B
add esp, byte 0Ch	; 35750
mov edx, dword [dword esp+0798h]	; 35753
mov dword [dword esp+edx+073Ch], eax	; 3575A
mov esi, dword [pointerspr]	; 35761
mov edi, eax	; 35767
movsd	; 35769
movsd	; 3576A
movsd	; 3576B
movsd	; 3576C
movsb	; 3576D
mov eax, dword [dword esp+edx+073Ch]	; 3576E
mov edx, dword [dword esp+0760h]	; 35775
mov word [byte eax+04h], dx	; 3577C
mov eax, dword [dword esp+0798h]	; 35780
mov eax, dword [dword esp+eax+073Ch]	; 35787
mov edx, dword [dword esp+0784h]	; 3578E
mov word [byte eax+06h], dx	; 35795
mov eax, dword [dword esp+0790h]	; 35799
mov esi, dword [dword esp+eax+071Ch]	; 357A0
push esi	; 357A7
mov edi, dword [dword esp+eax+071Ch]	; 357A8
push edi	; 357AF
mov eax, dword [dword esp+07A0h]	; 357B0
mov edx, dword [dword esp+eax+0744h]	; 357B7
push edx	; 357BE
call sub_91400	; 357BF
add esp, byte 0Ch	; 357C4
mov ebx, dword [dword esp+07A0h]	; 357C7
push ebx	; 357CE
mov ecx, dword [dword esp+07A8h]	; 357CF
push ecx	; 357D6
mov esi, dword [dword esp+07A4h]	; 357D7
push esi	; 357DE
mov ecx, dword [dword esp+079Ch]	; 357DF
mov ecx, dword [dword esp+ecx+0728h]	; 357E6
mov ebx, dword [dword esp+079Ch]	; 357ED
mov ebx, dword [dword esp+ebx+0724h]	; 357F4
mov edx, dword [dword esp+07A4h]	; 357FB
mov edx, dword [dword esp+edx+0754h]	; 35802
mov eax, dword [dword esp+07A4h]	; 35809
mov eax, dword [dword esp+eax+073Ch]	; 35810
call DrawMenuDropdown	; 35817
mov eax, dword [dword esp+0798h]	; 3581C
xor edi, edi	; 35823
mov dword [dword esp+eax+0754h], edi	; 35825
mov eax, dword [dword esp+07A0h]	; 3582C
push eax	; 35833
mov edx, dword [dword esp+07A8h]	; 35834
push edx	; 3583B
mov ebx, dword [dword esp+0798h]	; 3583C
mov ebx, dword [dword esp+ebx+0724h]	; 35843
mov edx, dword [dword esp+0798h]	; 3584A
mov edx, dword [dword esp+edx+0720h]	; 35851
mov eax, dword [dword esp+07A0h]	; 35858
mov eax, dword [dword esp+eax+0738h]	; 3585F
mov ecx, esi	; 35866
jmp near .64	; 35868
.59:
mov esi, dword [dword esp+0774h]	; 3586D
push esi	; 35874
mov edi, dword [dword esp+077Ch]	; 35875
push edi	; 3587C
mov eax, dword [dword esp+079Ch]	; 3587D
push eax	; 35884
call sub_903F0	; 35885
add esp, byte 0Ch	; 3588A
mov eax, dword [dword esp+07B0h]	; 3588D
cmp eax, dword [dword esp+0768h]	; 35894
je near .63	; 3589B
mov eax, dword [dword esp+07B0h]	; 358A1
mov word [dword esp+07CCh], ax	; 358A8
jmp short .62	; 358B0
.60:
mov esi, edi	; 358B2
shl esi, 2	; 358B4
xor edx, edx	; 358B7
mov dword [dword esp+esi+0754h], edx	; 358B9
mov ebx, dword [dword esp+esi+073Ch]	; 358C0
test ebx, ebx	; 358C7
je short .61	; 358C9
mov ecx, dword [dword esp+edi*8+071Ch]	; 358CB
push ecx	; 358D2
mov eax, dword [dword esp+edi*8+071Ch]	; 358D3
push eax	; 358DA
push ebx	; 358DB
call sub_903F0	; 358DC
add esp, byte 0Ch	; 358E1
xor ebx, ebx	; 358E4
mov dword [dword esp+edi*8+0718h], ebx	; 358E6
mov dword [dword esp+edi*8+071Ch], ebx	; 358ED
mov edi, dword [dword esp+esi+073Ch]	; 358F4
push edi	; 358FB
call jctime	; 358FC
add esp, byte 4	; 35901
xor eax, eax	; 35904
mov dword [dword esp+esi+073Ch], eax	; 35906
mov dword [dword esp+esi+0730h], eax	; 3590D
mov dword [dword esp+esi+0748h], eax	; 35914
.61:
dec word [dword esp+07CCh]	; 3591B
.62:
mov edi, dword [dword esp+07CAh]	; 35923
sar edi, 10h	; 3592A
mov eax, dword [dword esp+0768h]	; 3592D
cmp edi, eax	; 35934
jg near CalendarScreen.60	; 35936
mov dword [dword esp+07B0h], eax	; 3593C
.63:
mov ecx, dword [dword esp+07A0h]	; 35943
push ecx	; 3594A
mov esi, dword [dword esp+07A8h]	; 3594B
push esi	; 35952
mov eax, dword [dword esp+0770h]	; 35953
mov ebx, dword [dword esp+eax*8+0724h]	; 3595A
mov edx, dword [dword esp+eax*8+0720h]	; 35961
mov ecx, dword [dword esp+eax*4+075Ch]	; 35968
shl ecx, 5	; 3596F
mov eax, dword [dword esp+eax*4+0738h]	; 35972
add eax, ecx	; 35979
mov ecx, dword [dword esp+07A4h]	; 3597B
call DrawMenuItemSel	; 35982
mov edx, dword [dword esp+0768h]	; 35987
mov eax, dword [dword esp+0764h]	; 3598E
mov dword [dword esp+edx*4+0754h], eax	; 35995
mov edi, dword [dword esp+07A0h]	; 3599C
push edi	; 359A3
push esi	; 359A4
mov ebx, dword [dword esp+edx*8+0724h]	; 359A5
mov eax, dword [dword esp+edx*8+0720h]	; 359AC
mov esi, dword [dword esp+edx*4+075Ch]	; 359B3
shl esi, 5	; 359BA
mov edx, dword [dword esp+edx*4+0738h]	; 359BD
add esi, edx	; 359C4
mov ecx, dword [dword esp+07A4h]	; 359C6
mov edx, eax	; 359CD
mov eax, esi	; 359CF
.64:
call DrawMenuItemNorm	; 359D1
jmp near .79	; 359D6
.65:
mov edi, dword [dword esp+0774h]	; 359DB
push edi	; 359E2
mov eax, dword [dword esp+077Ch]	; 359E3
push eax	; 359EA
mov edx, dword [dword esp+079Ch]	; 359EB
push edx	; 359F2
call sub_903F0	; 359F3
add esp, byte 0Ch	; 359F8
cmp dword [dword esp+07B0h], byte 0	; 359FB
je near .69	; 35A03
mov eax, dword [dword esp+07B0h]	; 35A09
mov word [dword esp+07CCh], ax	; 35A10
jmp short .68	; 35A18
.66:
mov esi, dword [dword esp+07CAh]	; 35A1A
sar esi, 10h	; 35A21
mov edi, esi	; 35A24
shl edi, 2	; 35A26
mov eax, dword [dword esp+edi+073Ch]	; 35A29
test eax, eax	; 35A30
je short .67	; 35A32
mov edx, dword [dword esp+esi*8+071Ch]	; 35A34
push edx	; 35A3B
mov ebx, dword [dword esp+esi*8+071Ch]	; 35A3C
push ebx	; 35A43
push eax	; 35A44
call sub_903F0	; 35A45
add esp, byte 0Ch	; 35A4A
xor eax, eax	; 35A4D
mov dword [dword esp+esi*8+0718h], eax	; 35A4F
mov dword [dword esp+esi*8+071Ch], eax	; 35A56
mov ebx, dword [dword esp+edi+073Ch]	; 35A5D
push ebx	; 35A64
call jctime	; 35A65
add esp, byte 4	; 35A6A
.67:
dec word [dword esp+07CCh]	; 35A6D
.68:
cmp word [dword esp+07CCh], byte 0	; 35A75
jge short CalendarScreen.66	; 35A7E
xor eax, eax	; 35A80
mov dword [dword esp+07B0h], eax	; 35A82
mov dword [dword esp+0734h], eax	; 35A89
mov dword [dword esp+073Ch], eax	; 35A90
mov dword [dword esp+0740h], eax	; 35A97
mov dword [dword esp+0758h], eax	; 35A9E
mov dword [dword esp+074Ch], eax	; 35AA5
jmp near .79	; 35AAC
.69:
mov word [dword esp+07B4h], 0FFFFh	; 35AB1
mov ecx, dword [dword esp+0770h]	; 35ABB
cmp ecx, byte 52h	; 35AC2
jl near .78	; 35AC5
cmp ecx, 25Fh	; 35ACB
jge near .78	; 35AD1
mov edi, dword [dword esp+076Ch]	; 35AD7
cmp edi, byte 44h	; 35ADE
jl near .78	; 35AE1
cmp edi, 1B2h	; 35AE7
jge near .78	; 35AED
lea edx, [byte edi-044h]	; 35AF3
mov ebx, 3Dh	; 35AF6
mov eax, edx	; 35AFB
sar edx, 1Fh	; 35AFD
idiv ebx	; 35B00
mov esi, eax	; 35B02
shl esi, 3	; 35B04
sub esi, eax	; 35B07
lea edx, [byte ecx-052h]	; 35B09
mov ebx, 4Bh	; 35B0C
mov eax, edx	; 35B11
sar edx, 1Fh	; 35B13
idiv ebx	; 35B16
add esi, eax	; 35B18
mov ebx, dword [calmonth]	; 35B1A
xor edx, edx	; 35B20
mov dl, byte [dword ebx+monthfirstday]	; 35B22
mov ecx, 7	; 35B28
mov eax, edx	; 35B2D
sar edx, 1Fh	; 35B2F
idiv ecx	; 35B32
mov eax, esi	; 35B34
sub eax, edx	; 35B36
mov word [dword esp+07C8h], ax	; 35B38
test ax, ax	; 35B40
jl near .78	; 35B43
xor eax, eax	; 35B49
mov al, byte [dword ebx+monthdays]	; 35B4B
mov edx, dword [dword esp+07C6h]	; 35B51
sar edx, 10h	; 35B58
cmp edx, eax	; 35B5B
jge near .78	; 35B5D
xor ebx, ebx	; 35B63
mov word [dword esp+07CCh], bx	; 35B65
jmp near .77	; 35B6D
.70:
mov edx, dword [dword esp+07CAh]	; 35B72
sar edx, 10h	; 35B79
mov eax, edx	; 35B7C
shl eax, 2	; 35B7E
sub eax, edx	; 35B81
add eax, eax	; 35B83
xor ecx, ecx	; 35B85
mov cl, byte [dword esp+eax+0304h]	; 35B87
mov ebx, dword [calmonth]	; 35B8E
inc ebx	; 35B94
cmp ecx, ebx	; 35B95
jne near .76	; 35B97
xor ecx, ebx	; 35B9D
mov cl, byte [dword esp+eax+0305h]	; 35B9F
mov ebx, dword [dword esp+07C6h]	; 35BA6
sar ebx, 10h	; 35BAD
inc ebx	; 35BB0
cmp ecx, ebx	; 35BB1
jne near .76	; 35BB3
mov bl, byte [dword esp+eax+0308h]	; 35BB9
cmp bl, 0FFh	; 35BC0
jne near .76	; 35BC3
cmp bl, byte [dword esp+eax+0309h]	; 35BC9
jne near .76	; 35BD0
mov eax, dword [dword esp+edx*2+05AAh]	; 35BD6
sar eax, 10h	; 35BDD
cmp eax, dword [calsel]	; 35BE0
jne short .71	; 35BE6
mov dword [calexit], 0FFFFFFFFh	; 35BE8
.71:
cmp word [dword esp+07C0h], 444h	; 35BF2
jl short .72	; 35BFC
mov eax, dword [dword esp+07CAh]	; 35BFE
sar eax, 10h	; 35C05
mov ax, word [dword esp+eax*2+05ACh]	; 35C08
cmp ax, word [dword esp+07BCh]	; 35C10
jne short .73	; 35C18
.72:
mov eax, dword [dword esp+07CAh]	; 35C1A
sar eax, 10h	; 35C21
mov ax, word [dword esp+eax*2+05ACh]	; 35C24
mov word [dword esp+07B4h], ax	; 35C2C
mov eax, dword [dword esp+07CCh]	; 35C34
mov word [dword esp+07C4h], ax	; 35C3B
mov eax, dword [dword esp+07B8h]	; 35C43
mov word [dword esp+07CCh], ax	; 35C4A
.73:
mov esi, dword [calselmonth]	; 35C52
mov edi, dword [calselday]	; 35C58
mov ebx, dword [dword esp+07C2h]	; 35C5E
sar ebx, 10h	; 35C65
mov edx, ebx	; 35C68
mov eax, ebx	; 35C6A
shl eax, 2	; 35C6C
sub eax, ebx	; 35C6F
xor edx, ebx	; 35C71
mov dl, byte [dword esp+eax*2+0304h]	; 35C73
mov dword [calselmonth], edx	; 35C7A
mov al, byte [dword esp+eax*2+0305h]	; 35C80
and eax, 0FFh	; 35C87
mov dword [calselday], eax	; 35C8C
cmp dword [calexit], byte 0	; 35C91
jne short .74	; 35C98
lea edx, [dword esp+0304h]	; 35C9A
mov eax, ebp	; 35CA1
call SetGameSides	; 35CA3
.74:
call sub_B4BA8	; 35CA8
mov ebx, dword [dword esp+07A0h]	; 35CAD
push ebx	; 35CB4
mov ecx, dword [dword esp+07A8h]	; 35CB5
mov ebx, dword [dword esp+07A0h]	; 35CBC
mov edx, 3	; 35CC3
mov eax, calmenubar	; 35CC8
call DrawMenuBar	; 35CCD
mov ecx, dword [calselmonth]	; 35CD2
cmp esi, ecx	; 35CD8
jne near .75	; 35CDA
cmp edi, dword [calselday]	; 35CE0
je near .75	; 35CE6
movzx esi, byte [dword ecx+monthfirstday_m1]	; 35CEC
add esi, edi	; 35CF3
dec esi	; 35CF5
mov ebx, 7	; 35CF6
mov eax, esi	; 35CFB
mov edx, esi	; 35CFD
sar edx, 1Fh	; 35CFF
idiv ebx	; 35D02
mov ebx, edx	; 35D04
mov ecx, 7	; 35D06
mov eax, esi	; 35D0B
mov edx, esi	; 35D0D
sar edx, 1Fh	; 35D0F
idiv ecx	; 35D12
mov esi, ebx	; 35D14
shl esi, 2	; 35D16
mov ecx, dword [dword esi+calcolx]	; 35D19
sub ecx, byte 2	; 35D1F
mov ebx, dword [nosplit eax*4+calrowy]	; 35D22
sub ebx, byte 2	; 35D29
mov edx, dword [dword esi+calcolx]	; 35D2C
add edx, byte 4Dh	; 35D32
mov eax, dword [nosplit eax*4+calrowy]	; 35D35
add eax, byte 3Fh	; 35D3C
push eax	; 35D3F
push ebx	; 35D40
push edx	; 35D41
push ecx	; 35D42
call sub_B4BC4	; 35D43
add esp, byte 10h	; 35D48
mov edx, dword [calendarshapes]	; 35D4B
push edx	; 35D51
mov ebx, dword [dword esp+07B0h]	; 35D52
push ebx	; 35D59
push ebp	; 35D5A
mov eax, dword [dword esp+07C2h]	; 35D5B
sar eax, 10h	; 35D62
push eax	; 35D65
mov eax, dword [calmonth]	; 35D66
lea ecx, [dword esp+0314h]	; 35D6B
mov ebx, dword [dword esp+07B8h]	; 35D72
lea edx, [dword esp+06A0h]	; 35D79
call DrawCalendarDay	; 35D80
.75:
mov eax, dword [calselmonth]	; 35D85
movzx esi, byte [dword eax+monthfirstday_m1]	; 35D8A
add esi, dword [calselday]	; 35D91
dec esi	; 35D97
mov ebx, 7	; 35D98
mov eax, esi	; 35D9D
mov edx, esi	; 35D9F
sar edx, 1Fh	; 35DA1
idiv ebx	; 35DA4
mov ebx, edx	; 35DA6
mov ecx, 7	; 35DA8
mov eax, esi	; 35DAD
mov edx, esi	; 35DAF
sar edx, 1Fh	; 35DB1
idiv ecx	; 35DB4
mov esi, eax	; 35DB6
mov eax, ebx	; 35DB8
mov ebx, dword [nosplit eax*4+calcolx]	; 35DBA
sub ebx, byte 2	; 35DC1
mov edx, dword [nosplit esi*4+calrowy]	; 35DC4
sub edx, byte 2	; 35DCB
mov eax, dword [nosplit eax*4+calcolx]	; 35DCE
add eax, byte 4Dh	; 35DD5
mov ecx, dword [nosplit esi*4+calrowy]	; 35DD8
add ecx, byte 3Fh	; 35DDF
push ecx	; 35DE2
push edx	; 35DE3
push eax	; 35DE4
push ebx	; 35DE5
call sub_B4BC4	; 35DE6
add esp, byte 10h	; 35DEB
mov esi, dword [calendarshapes]	; 35DEE
push esi	; 35DF4
mov edi, dword [dword esp+07B0h]	; 35DF5
push edi	; 35DFC
push ebp	; 35DFD
mov eax, dword [dword esp+07C2h]	; 35DFE
sar eax, 10h	; 35E05
push eax	; 35E08
mov eax, dword [calmonth]	; 35E09
lea ecx, [dword esp+0314h]	; 35E0E
mov ebx, dword [dword esp+07B8h]	; 35E15
lea edx, [dword esp+06A0h]	; 35E1C
call DrawCalendarDay	; 35E23
push dword 1E0h	; 35E28
push byte 0	; 35E2D
push dword 280h	; 35E2F
push byte 0	; 35E34
call sub_B4BC4	; 35E36
add esp, byte 10h	; 35E3B
.76:
inc word [dword esp+07CCh]	; 35E3E
.77:
mov eax, dword [dword esp+07CCh]	; 35E46
cmp ax, word [dword esp+07B8h]	; 35E4D
jl near CalendarScreen.70	; 35E55
.78:
mov eax, dword [dword esp+07B2h]	; 35E5B
sar eax, 10h	; 35E62
mov dword [calsel], eax	; 35E65
.79:
mov ecx, dword [dword esp+0774h]	; 35E6A
push ecx	; 35E71
mov esi, dword [dword esp+077Ch]	; 35E72
push esi	; 35E79
mov edi, dword [dword esp+079Ch]	; 35E7A
push edi	; 35E81
call sub_91400	; 35E82
add esp, byte 0Ch	; 35E87
mov eax, dword [dword esp+0774h]	; 35E8A
push eax	; 35E91
mov edx, dword [dword esp+077Ch]	; 35E92
push edx	; 35E99
mov ebx, dword [dword esp+079Ch]	; 35E9A
push ebx	; 35EA1
call sub_903F0	; 35EA2
add esp, byte 0Ch	; 35EA7
mov ecx, dword [dword esp+076Ch]	; 35EAA
push ecx	; 35EB1
mov esi, dword [dword esp+0774h]	; 35EB2
push esi	; 35EB9
mov edi, dword [dword esp+079Ch]	; 35EBA
push edi	; 35EC1
call sub_91400	; 35EC2
add esp, byte 0Ch	; 35EC7
cmp dword [calexit], byte 0	; 35ECA
jne short .81	; 35ED1
mov edx, dword [dword esp+076Ch]	; 35ED3
push edx	; 35EDA
mov ebx, dword [dword esp+0774h]	; 35EDB
push ebx	; 35EE2
mov ecx, dword [pointerspr]	; 35EE3
push ecx	; 35EE9
.80:
call sub_91370	; 35EEA
add esp, byte 0Ch	; 35EEF
.81:
mov eax, dword [dword esp+0770h]	; 35EF2
mov dword [dword esp+0778h], eax	; 35EF9
mov eax, dword [dword esp+076Ch]	; 35F00
mov dword [dword esp+0774h], eax	; 35F07
.82:
cmp dword [calexit], byte 0	; 35F0E
je near CalendarScreen.32	; 35F15
.83:
mov edi, dword [dword esp+0794h]	; 35F1B
push edi	; 35F22
call jctime	; 35F23
add esp, byte 4	; 35F28
mov ebp, dword [dword esp+078Ch]	; 35F2B
push ebp	; 35F32
call jctime	; 35F33
add esp, byte 4	; 35F38
mov eax, dword [calendarshapes]	; 35F3B
push eax	; 35F40
call jctime	; 35F41
add esp, byte 4	; 35F46
xor edx, edx	; 35F49
mov dword [calendarshapes], edx	; 35F4B
mov dword [teamstatscb], GameTeamStatsScreen	; 35F51
mov dword [skaterstatscb], GameSkaterStatsScreen	; 35F5B
mov dword [goaliestatscb], GameGoalieStatsScreen	; 35F65
mov dword [standingscb], GameStandingsScreen	; 35F6F
mov dword [standingsmenucb], GameStandingsMenu	; 35F79
cmp byte [musicon], 0	; 35F83
je short .84	; 35F8A
cmp dword [songdata], byte 0	; 35F8C
je short .84	; 35F93
mov eax, dword [musichandle]	; 35F95
mov ebx, 64h	; 35F9A
mov edx, 3	; 35F9F
call sub_8FCDF	; 35FA4
.84:
mov eax, dword [calsel]	; 35FA9
.x:
add esp, 7D4h	; 35FAE
pop ebp	; 35FB4
pop edi	; 35FB5
pop esi	; 35FB6
pop ecx	; 35FB7
ret	; 35FB8
