; game_state_saveload 5FB03-614C2  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_5FB03 progbits alloc exec nowrite align=1
extern PBnum, StanleyCupTimer, __CHK, __STOSB, __STOSD, str_ErrLoadGame, str_ErrSaveGame, pad1dev
extern pad2dev, sflags, gmode2, byte_CCE00, hmroster, awroster, byte_DC264, byte_DC265
extern byte_DC266, byte_DC267, byte_DC268, byte_E024C, PlList, PenBuf, iflags, byte_E9AC8
extern byte_E9AD3, OOlist, collflag, postate, lgstate, gamemode, ctl1team, ctl2team
extern ctl1dev, ctl2dev, ctl1side, hudclockmin, hudclocksec, hudclockhund, dword_C5840, dword_C66D0
extern dword_C66D4, dword_C90B0, sflags3, cont2team, HomeTeam, dword_CBC3E, dword_CBECA, dword_CC0AC
extern lastsfx, photobankf, onetimerflag, dword_CC0F8, penshotplayer, dword_CC100, dword_CC104, dword_CC108
extern dword_CC110, dword_CC114, penshotmode, penshotstart, penshottimer, dword_CC124, penshotlive, dword_CC12C
extern dword_CC130, dword_CC134, dword_CC138, dword_CC13C, dword_CC140, dword_CC144, crowdsmooth, frameaccum
extern dword_D8C78, curperiod, photobanks, dword_DB088, dword_DC28C, dword_DF00C, dword_DF010, hmtmstruct
extern dword_DF6F2, dword_DF6F6, hmtmplstats, dword_DF6FE, hmtmroster, hmtmlines, hmtmptrF2, hmtmsort
extern awtmstruct, awtmlines, dword_DF7F2, dword_DF7F6, awtmplstats, dword_DF7FE, awtmroster, awtmptrF2
extern awtmsort, dword_E009C, dword_E0248, recbpr, dword_E9A9E, dword_E9AB6, dword_E9B2A, gmode
extern ltx, replaystart, off_CC01D, passspeed, LoadGameGfx, FileReadAt, FileWriteAt, LoadGameTeams
extern SaveModeState, LoadModeState, GetPeriodTime, SprSort, sub_61E99, sub_673C5, ReplayRecordReset, LoadRockMusic
extern FatalError, MouseSetPos, threat, exhstate, unk_C5423, unk_C542E, awlinetab, unk_DAC40
extern unk_DAC70, unk_DACA0, unk_DAE94, unk_DB218, hmteamrec, awteamrec, hmlinetab, unk_DC240
extern unk_DC252, unk_DF314, SortCords, hudpenhome, hudpenaway, camx, camy
extern lastplayer, passdir, word_C90A6, passplayer, xc1, yc1, word_C90B2, word_C90B4
extern fodir1, fodir2, c1playernum, c2playernum, cont1team, VisTeam, Pencntdwn, Penaltytimer
extern refsignal, RefStep, RefPen, word_C90D8, gsp, gameclock, clockticks, word_CBC44
extern exitgame, gameover, word_CBC52, word_CBC54, lcblink, word_CBC58, lcblinktime
extern lcsel, word_CBC60, lcline, word_CBC64, lctimer, word_CBC68, lcboxon, word_CBC6C
extern word_CBD64, word_CBD66, word_CBEC0, word_CBEC2, word_CBEC4, word_CBEC6, word_CBEC8, word_CBECC
extern word_CBECE, word_CC0B0, lldispodd, word_CC0DA, crowdlevel, word_CC10C, word_CCEF8, word_DEE94
extern word_DEE96, word_DEF84, word_DEF88, puckcross, word_E024E, lcrequest, word_E0306, lcreqchoice
extern word_E0382, word_E0390, OOlistpos, word_E9A9C, word_E9AA2, word_E9AA4, word_E9AA6, CwdExciteLvl
extern word_E9AAA, periodendtime, word_E9AAE, word_E9AB0, word_E9AB2, word_E9AB4, PerTimeTotal, lj2
extern lj1, lasttouch, word_E9AC4, word_E9B2C
global SaveGameState, SaveGameState_popx, LoadGameState
SaveGameState:
push dword 0B0h	; 5FB03
call __CHK	; 5FB08
push ebx	; 5FB0D
push ecx	; 5FB0E
push edx	; 5FB0F
push esi	; 5FB10
push edi	; 5FB11
push ebp	; 5FB12
sub esp, 8Ch	; 5FB13
push eax	; 5FB19
mov ecx, 4	; 5FB1A
mov ebx, 0FFFFFFFFh	; 5FB1F
mov edx, ctl1side	; 5FB24
call FileWriteAt	; 5FB29
test eax, eax	; 5FB2E
je short .1	; 5FB30
push str_ErrSaveGame	; 5FB32
call FatalError	; 5FB37
add esp, byte 4	; 5FB3C
.1:
xor ebp, ebp	; 5FB3F
.2:
mov edx, ebp	; 5FB41
shl edx, 7	; 5FB43
add edx, SortCords	; 5FB46
mov ecx, 66h	; 5FB4C
mov ebx, 0FFFFFFFFh	; 5FB51
mov eax, dword [esp]	; 5FB56
call FileWriteAt	; 5FB59
test eax, eax	; 5FB5E
je short .3	; 5FB60
push str_ErrSaveGame	; 5FB62
call FatalError	; 5FB67
add esp, byte 4	; 5FB6C
.3:
inc ebp	; 5FB6F
cmp ebp, byte 11h	; 5FB70
jl short SaveGameState.2	; 5FB73
xor ebp, ebp	; 5FB75
.4:
mov edx, ebp	; 5FB77
shl edx, 8	; 5FB79
add edx, hmtmstruct	; 5FB7C
mov ecx, 0D4h	; 5FB82
mov ebx, 0FFFFFFFFh	; 5FB87
mov eax, dword [esp]	; 5FB8C
call FileWriteAt	; 5FB8F
test eax, eax	; 5FB94
je short .5	; 5FB96
push str_ErrSaveGame	; 5FB98
call FatalError	; 5FB9D
add esp, byte 4	; 5FBA2
.5:
inc ebp	; 5FBA5
cmp ebp, byte 2	; 5FBA6
jl short SaveGameState.4	; 5FBA9
mov ecx, 30h	; 5FBAB
mov ebx, 0FFFFFFFFh	; 5FBB0
mov edx, hmlinetab	; 5FBB5
mov eax, dword [esp]	; 5FBBA
call FileWriteAt	; 5FBBD
test eax, eax	; 5FBC2
je short .6	; 5FBC4
push str_ErrSaveGame	; 5FBC6
call FatalError	; 5FBCB
add esp, byte 4	; 5FBD0
.6:
mov ecx, 30h	; 5FBD3
mov ebx, 0FFFFFFFFh	; 5FBD8
mov edx, awlinetab	; 5FBDD
mov eax, dword [esp]	; 5FBE2
call FileWriteAt	; 5FBE5
test eax, eax	; 5FBEA
je short .7	; 5FBEC
push str_ErrSaveGame	; 5FBEE
call FatalError	; 5FBF3
add esp, byte 4	; 5FBF8
.7:
mov ax, word [HomeTeam]	; 5FBFB
mov word [byte esp+04h], ax	; 5FC01
lea eax, [byte esp+04h]	; 5FC06
add eax, byte 2	; 5FC0A
mov dx, word [VisTeam]	; 5FC0D
mov word [eax], dx	; 5FC14
add eax, byte 2	; 5FC17
mov dx, word [camx]	; 5FC1A
mov word [eax], dx	; 5FC21
add eax, byte 2	; 5FC24
mov dx, word [camy]	; 5FC27
mov word [eax], dx	; 5FC2E
xor ebp, ebp	; 5FC31
add eax, byte 2	; 5FC33
.8:
mov dx, word [nosplit ebp*2+word_E0390]	; 5FC36
mov word [eax], dx	; 5FC3E
add eax, byte 2	; 5FC41
inc ebp	; 5FC44
cmp ebp, byte 6	; 5FC45
jl short SaveGameState.8	; 5FC48
mov dx, word [lastplayer]	; 5FC4A
mov word [eax], dx	; 5FC51
add eax, byte 2	; 5FC54
mov dx, word [passspeed]	; 5FC57
mov word [eax], dx	; 5FC5E
add eax, byte 2	; 5FC61
mov dx, word [passdir]	; 5FC64
mov word [eax], dx	; 5FC6B
add eax, byte 2	; 5FC6E
mov dx, word [word_C90A6]	; 5FC71
mov word [eax], dx	; 5FC78
add eax, byte 2	; 5FC7B
mov dx, word [passplayer]	; 5FC7E
mov word [eax], dx	; 5FC85
add eax, byte 2	; 5FC88
mov dx, word [threat]	; 5FC8B
mov word [eax], dx	; 5FC92
xor ebp, ebp	; 5FC95
add eax, byte 2	; 5FC97
.9:
mov dx, word [nosplit ebp*2+puckcross]	; 5FC9A
mov word [eax], dx	; 5FCA2
add eax, byte 2	; 5FCA5
inc ebp	; 5FCA8
cmp ebp, byte 4	; 5FCA9
jl short SaveGameState.9	; 5FCAC
mov dx, word [lj1]	; 5FCAE
mov word [eax], dx	; 5FCB5
add eax, byte 2	; 5FCB8
mov dx, word [lj2]	; 5FCBB
mov word [eax], dx	; 5FCC2
add eax, byte 2	; 5FCC5
mov dx, word [lasttouch]	; 5FCC8
mov word [eax], dx	; 5FCCF
add eax, byte 2	; 5FCD2
mov dx, word [ltx]	; 5FCD5
mov word [eax], dx	; 5FCDC
add eax, byte 2	; 5FCDF
mov dx, word [word_E9AC4]	; 5FCE2
mov word [eax], dx	; 5FCE9
add eax, byte 2	; 5FCEC
mov dx, word [xc1]	; 5FCEF
mov word [eax], dx	; 5FCF6
add eax, byte 2	; 5FCF9
mov dx, word [yc1]	; 5FCFC
mov word [eax], dx	; 5FD03
add eax, byte 2	; 5FD06
mov dx, word [dword_C90B0]	; 5FD09
mov word [eax], dx	; 5FD10
add eax, byte 2	; 5FD13
mov dx, word [word_C90B2]	; 5FD16
mov word [eax], dx	; 5FD1D
add eax, byte 2	; 5FD20
mov dx, word [word_C90B4]	; 5FD23
mov word [eax], dx	; 5FD2A
add eax, byte 2	; 5FD2D
mov dx, word [fodir1]	; 5FD30
mov word [eax], dx	; 5FD37
add eax, byte 2	; 5FD3A
mov dx, word [fodir2]	; 5FD3D
mov word [eax], dx	; 5FD44
add eax, byte 2	; 5FD47
mov dx, word [sflags]	; 5FD4A
mov word [eax], dx	; 5FD51
add eax, byte 2	; 5FD54
mov dx, word [gmode2]	; 5FD57
mov word [eax], dx	; 5FD5E
add eax, byte 2	; 5FD61
mov dx, word [sflags3]	; 5FD64
mov word [eax], dx	; 5FD6B
add eax, byte 2	; 5FD6E
mov dx, word [c1playernum]	; 5FD71
mov word [eax], dx	; 5FD78
add eax, byte 2	; 5FD7B
mov dx, word [c2playernum]	; 5FD7E
mov word [eax], dx	; 5FD85
add eax, byte 2	; 5FD88
mov dx, word [cont1team]	; 5FD8B
mov word [eax], dx	; 5FD92
add eax, byte 2	; 5FD95
mov dx, word [cont2team]	; 5FD98
mov word [eax], dx	; 5FD9F
add eax, byte 2	; 5FDA2
mov dx, word [Pencntdwn]	; 5FDA5
mov word [eax], dx	; 5FDAC
add eax, byte 2	; 5FDAF
mov dx, word [Penaltytimer]	; 5FDB2
mov word [eax], dx	; 5FDB9
add eax, byte 2	; 5FDBC
mov dx, word [refsignal]	; 5FDBF
mov word [eax], dx	; 5FDC6
add eax, byte 2	; 5FDC9
mov dx, word [RefStep]	; 5FDCC
mov word [eax], dx	; 5FDD3
add eax, byte 2	; 5FDD6
mov dx, word [RefPen]	; 5FDD9
mov word [eax], dx	; 5FDE0
add eax, byte 2	; 5FDE3
mov dx, word [word_C90D8]	; 5FDE6
mov word [eax], dx	; 5FDED
add eax, byte 2	; 5FDF0
mov dx, word [gsp]	; 5FDF3
mov word [eax], dx	; 5FDFA
add eax, byte 2	; 5FDFD
mov dx, word [gameclock]	; 5FE00
mov word [eax], dx	; 5FE07
add eax, byte 2	; 5FE0A
mov dx, word [clockticks]	; 5FE0D
mov word [eax], dx	; 5FE14
add eax, byte 2	; 5FE17
mov dx, word [dword_CBC3E]	; 5FE1A
mov word [eax], dx	; 5FE21
add eax, byte 2	; 5FE24
mov dx, word [word_CBC44]	; 5FE27
mov word [eax], dx	; 5FE2E
add eax, byte 2	; 5FE31
mov dx, word [exitgame]	; 5FE34
mov word [eax], dx	; 5FE3B
add eax, byte 2	; 5FE3E
mov dx, word [gameover]	; 5FE41
mov word [eax], dx	; 5FE48
add eax, byte 2	; 5FE4B
mov dx, word [word_CBEC0]	; 5FE4E
mov word [eax], dx	; 5FE55
add eax, byte 2	; 5FE58
mov dx, word [word_CBEC2]	; 5FE5B
mov word [eax], dx	; 5FE62
add eax, byte 2	; 5FE65
mov dx, word [word_CBEC4]	; 5FE68
mov word [eax], dx	; 5FE6F
add eax, byte 2	; 5FE72
mov dx, word [dword_C5840]	; 5FE75
mov word [eax], dx	; 5FE7C
add eax, byte 2	; 5FE7F
mov dx, word [word_CBEC6]	; 5FE82
mov word [eax], dx	; 5FE89
add eax, byte 2	; 5FE8C
mov dx, word [word_E9AB0]	; 5FE8F
mov word [eax], dx	; 5FE96
add eax, byte 2	; 5FE99
mov dx, word [word_CBEC8]	; 5FE9C
mov word [eax], dx	; 5FEA3
add eax, byte 2	; 5FEA6
mov dx, word [dword_CBECA]	; 5FEA9
mov word [eax], dx	; 5FEB0
add eax, byte 2	; 5FEB3
mov edx, dword [StanleyCupTimer]	; 5FEB6
mov dword [eax], edx	; 5FEBC
add eax, byte 4	; 5FEBE
mov dx, word [PBnum]	; 5FEC1
mov word [eax], dx	; 5FEC8
add eax, byte 2	; 5FECB
mov dx, word [iflags]	; 5FECE
mov word [eax], dx	; 5FED5
mov ecx, 80h	; 5FED8
mov ebx, 0FFFFFFFFh	; 5FEDD
lea edx, [byte esp+04h]	; 5FEE2
mov eax, dword [esp]	; 5FEE6
call FileWriteAt	; 5FEE9
test eax, eax	; 5FEEE
je short .10	; 5FEF0
push str_ErrSaveGame	; 5FEF2
call FatalError	; 5FEF7
add esp, byte 4	; 5FEFC
.10:
lea eax, [byte esp+04h]	; 5FEFF
xor ebp, ebp	; 5FF03
.11:
mov dx, word [nosplit ebp*2+PlList]	; 5FF05
mov word [eax], dx	; 5FF0D
add eax, byte 2	; 5FF10
inc ebp	; 5FF13
cmp ebp, byte 6	; 5FF14
jl short SaveGameState.11	; 5FF17
mov dl, byte [pad1dev]	; 5FF19
mov byte [eax], dl	; 5FF1F
mov dl, byte [pad2dev]	; 5FF21
mov byte [byte eax+01h], dl	; 5FF27
add eax, byte 2	; 5FF2A
mov dl, byte [collflag]	; 5FF2D
mov byte [eax], dl	; 5FF33
mov dl, byte [gmode]	; 5FF35
mov byte [byte eax+01h], dl	; 5FF3B
add eax, byte 2	; 5FF3E
mov dx, word [word_CBC52]	; 5FF41
mov word [eax], dx	; 5FF48
add eax, byte 2	; 5FF4B
mov dx, word [word_CBC54]	; 5FF4E
mov word [eax], dx	; 5FF55
add eax, byte 2	; 5FF58
mov dx, word [lcblink]	; 5FF5B
mov word [eax], dx	; 5FF62
add eax, byte 2	; 5FF65
mov dx, word [word_CBC58]	; 5FF68
mov word [eax], dx	; 5FF6F
add eax, byte 2	; 5FF72
mov dx, word [lcblinktime]	; 5FF75
mov word [eax], dx	; 5FF7C
add eax, byte 2	; 5FF7F
mov dx, word [lcblinktime+2]	; 5FF82
mov word [eax], dx	; 5FF89
add eax, byte 2	; 5FF8C
mov dx, word [lcsel]	; 5FF8F
mov word [eax], dx	; 5FF96
add eax, byte 2	; 5FF99
mov dx, word [word_CBC60]	; 5FF9C
mov word [eax], dx	; 5FFA3
add eax, byte 2	; 5FFA6
mov dx, word [lcline]	; 5FFA9
mov word [eax], dx	; 5FFB0
add eax, byte 2	; 5FFB3
mov dx, word [word_CBC64]	; 5FFB6
mov word [eax], dx	; 5FFBD
add eax, byte 2	; 5FFC0
mov dx, word [lctimer]	; 5FFC3
mov word [eax], dx	; 5FFCA
add eax, byte 2	; 5FFCD
mov dx, word [word_CBC68]	; 5FFD0
mov word [eax], dx	; 5FFD7
add eax, byte 2	; 5FFDA
mov dx, word [lcboxon]	; 5FFDD
mov word [eax], dx	; 5FFE4
add eax, byte 2	; 5FFE7
mov dx, word [word_CBC6C]	; 5FFEA
mov word [eax], dx	; 5FFF1
add eax, byte 2	; 5FFF4
mov dx, word [lcrequest]	; 5FFF7
mov word [eax], dx	; 5FFFE
add eax, byte 2	; 60001
mov dx, word [word_E0306]	; 60004
mov word [eax], dx	; 6000B
add eax, byte 2	; 6000E
mov dx, word [lcreqchoice]	; 60011
mov word [eax], dx	; 60018
add eax, byte 2	; 6001B
mov dx, word [word_E0382]	; 6001E
mov word [eax], dx	; 60025
add eax, byte 2	; 60028
mov dx, word [dword_DF00C]	; 6002B
mov word [eax], dx	; 60032
add eax, byte 2	; 60035
mov dx, word [dword_DF010]	; 60038
mov word [eax], dx	; 6003F
add eax, byte 2	; 60042
mov dx, word [word_DEF84]	; 60045
mov word [eax], dx	; 6004C
add eax, byte 2	; 6004F
mov dx, word [word_DEF88]	; 60052
mov word [eax], dx	; 60059
add eax, byte 2	; 6005C
mov dx, word [curperiod]	; 6005F
mov word [eax], dx	; 60066
add eax, byte 2	; 60069
mov dx, word [lldispodd]	; 6006C
mov word [eax], dx	; 60073
add eax, byte 2	; 60076
mov dx, word [dword_E9AB6]	; 60079
mov word [eax], dx	; 60080
add eax, byte 2	; 60083
mov dx, word [word_E9AAE]	; 60086
mov word [eax], dx	; 6008D
add eax, byte 2	; 60090
mov dx, word [periodendtime]	; 60093
mov word [eax], dx	; 6009A
add eax, byte 2	; 6009D
mov dx, word [dword_E9A9E]	; 600A0
mov word [eax], dx	; 600A7
add eax, byte 2	; 600AA
mov dx, word [word_CC0DA]	; 600AD
mov word [eax], dx	; 600B4
add eax, byte 2	; 600B7
mov dx, word [lastsfx]	; 600BA
mov word [eax], dx	; 600C1
add eax, byte 2	; 600C4
mov dx, word [word_E9A9C]	; 600C7
mov word [eax], dx	; 600CE
add eax, byte 2	; 600D1
mov dx, word [crowdlevel]	; 600D4
mov word [eax], dx	; 600DB
add eax, byte 2	; 600DE
mov dx, word [word_E9AAA]	; 600E1
mov word [eax], dx	; 600E8
add eax, byte 2	; 600EB
mov dx, word [word_E9AA2]	; 600EE
mov word [eax], dx	; 600F5
add eax, byte 2	; 600F8
mov dx, word [CwdExciteLvl]	; 600FB
mov word [eax], dx	; 60102
add eax, byte 2	; 60105
mov dx, word [word_E9AA4]	; 60108
mov word [eax], dx	; 6010F
add eax, byte 2	; 60112
mov dx, word [word_E9AA6]	; 60115
mov word [eax], dx	; 6011C
add eax, byte 2	; 6011F
mov dx, word [dword_E009C]	; 60122
mov word [eax], dx	; 60129
add eax, byte 2	; 6012C
mov dx, word [ctl1team]	; 6012F
mov word [eax], dx	; 60136
add eax, byte 2	; 60139
mov dx, word [ctl2team]	; 6013C
mov word [eax], dx	; 60143
add eax, byte 2	; 60146
mov dx, word [ctl1dev]	; 60149
mov word [eax], dx	; 60150
add eax, byte 2	; 60153
mov dx, word [ctl2dev]	; 60156
mov word [eax], dx	; 6015D
add eax, byte 2	; 60160
mov dx, word [hudclockmin]	; 60163
mov word [eax], dx	; 6016A
add eax, byte 2	; 6016D
mov dx, word [hudclocksec]	; 60170
mov word [eax], dx	; 60177
add eax, byte 2	; 6017A
mov dx, word [hudclockhund]	; 6017D
mov word [eax], dx	; 60184
add eax, byte 2	; 60187
mov dx, word [word_CC0B0]	; 6018A
mov word [eax], dx	; 60191
add eax, byte 2	; 60194
mov dx, word [dword_D8C78]	; 60197
mov word [eax], dx	; 6019E
add eax, byte 2	; 601A1
mov dx, word [frameaccum]	; 601A4
mov word [eax], dx	; 601AB
add eax, byte 2	; 601AE
mov dx, word [dword_CC0AC]	; 601B1
mov word [eax], dx	; 601B8
add eax, byte 2	; 601BB
mov dx, word [byte_E024C]	; 601BE
mov word [eax], dx	; 601C5
add eax, byte 2	; 601C8
mov dx, word [word_E024E]	; 601CB
mov word [eax], dx	; 601D2
add eax, byte 2	; 601D5
mov dx, word [gamemode]	; 601D8
mov word [eax], dx	; 601DF
add eax, byte 2	; 601E2
mov dl, byte [byte_DC268]	; 601E5
mov byte [eax], dl	; 601EB
mov dl, byte [byte_DC267]	; 601ED
mov byte [byte eax+01h], dl	; 601F3
add eax, byte 2	; 601F6
mov dl, byte [byte_DC264]	; 601F9
mov byte [eax], dl	; 601FF
mov dl, byte [byte_DC265]	; 60201
mov byte [byte eax+01h], dl	; 60207
add eax, byte 2	; 6020A
mov dl, byte [byte_DC266]	; 6020D
mov byte [eax], dl	; 60213
mov dl, byte [onetimerflag]	; 60215
mov byte [byte eax+01h], dl	; 6021B
mov ecx, 80h	; 6021E
mov ebx, 0FFFFFFFFh	; 60223
lea edx, [byte esp+04h]	; 60228
mov eax, dword [esp]	; 6022C
call FileWriteAt	; 6022F
test eax, eax	; 60234
je short .12	; 60236
push str_ErrSaveGame	; 60238
call FatalError	; 6023D
add esp, byte 4	; 60242
.12:
lea eax, [byte esp+04h]	; 60245
xor ebp, ebp	; 60249
.13:
mov ecx, ebp	; 6024B
shl ecx, 2	; 6024D
sub ecx, ebp	; 60250
mov dx, word [nosplit ecx*4+word_DEE94]	; 60252
mov word [eax], dx	; 6025A
add eax, byte 2	; 6025D
mov dx, word [nosplit ecx*4+word_DEE96]	; 60260
mov word [eax], dx	; 60268
add eax, byte 2	; 6026B
inc ebp	; 6026E
cmp ebp, byte 14h	; 6026F
jl short SaveGameState.13	; 60272
mov dx, word [word_CBECC]	; 60274
mov word [eax], dx	; 6027B
add eax, byte 2	; 6027E
mov dx, word [word_CBECE]	; 60281
mov word [eax], dx	; 60288
add eax, byte 2	; 6028B
mov dx, word [word_E9AB2]	; 6028E
mov word [eax], dx	; 60295
add eax, byte 2	; 60298
mov dx, word [word_E9AB4]	; 6029B
mov word [eax], dx	; 602A2
add eax, byte 2	; 602A5
mov dx, word [dword_CC0F8]	; 602A8
mov word [eax], dx	; 602AF
add eax, byte 2	; 602B2
mov dx, word [penshotplayer]	; 602B5
mov word [eax], dx	; 602BC
add eax, byte 2	; 602BF
mov dx, word [dword_CC100]	; 602C2
mov word [eax], dx	; 602C9
add eax, byte 2	; 602CC
mov dx, word [dword_CC104]	; 602CF
mov word [eax], dx	; 602D6
add eax, byte 2	; 602D9
mov dx, word [dword_CC108]	; 602DC
mov word [eax], dx	; 602E3
add eax, byte 2	; 602E6
mov dx, word [word_CC10C]	; 602E9
mov word [eax], dx	; 602F0
add eax, byte 2	; 602F3
mov dx, word [dword_CC110]	; 602F6
mov word [eax], dx	; 602FD
add eax, byte 2	; 60300
mov dx, word [dword_CC114]	; 60303
mov word [eax], dx	; 6030A
add eax, byte 2	; 6030D
mov dx, word [penshotmode]	; 60310
mov word [eax], dx	; 60317
add eax, byte 2	; 6031A
mov dx, word [penshotstart]	; 6031D
mov word [eax], dx	; 60324
add eax, byte 2	; 60327
mov dx, word [penshottimer]	; 6032A
mov word [eax], dx	; 60331
add eax, byte 2	; 60334
mov dx, word [dword_CC124]	; 60337
mov word [eax], dx	; 6033E
add eax, byte 2	; 60341
mov dx, word [penshotlive]	; 60344
mov word [eax], dx	; 6034B
add eax, byte 2	; 6034E
mov dx, word [dword_CC12C]	; 60351
mov word [eax], dx	; 60358
add eax, byte 2	; 6035B
mov dx, word [dword_CC130]	; 6035E
mov word [eax], dx	; 60365
add eax, byte 2	; 60368
mov dx, word [dword_CC134]	; 6036B
mov word [eax], dx	; 60372
add eax, byte 2	; 60375
mov dx, word [dword_CC138]	; 60378
mov word [eax], dx	; 6037F
add eax, byte 2	; 60382
mov dx, word [dword_CC13C]	; 60385
mov word [eax], dx	; 6038C
add eax, byte 2	; 6038F
mov dx, word [dword_CC140]	; 60392
mov word [eax], dx	; 60399
add eax, byte 2	; 6039C
mov dx, word [dword_CC144]	; 6039F
mov word [eax], dx	; 603A6
mov ecx, 80h	; 603A9
mov ebx, 0FFFFFFFFh	; 603AE
lea edx, [byte esp+04h]	; 603B3
mov eax, dword [esp]	; 603B7
call FileWriteAt	; 603BA
test eax, eax	; 603BF
je short .14	; 603C1
push str_ErrSaveGame	; 603C3
call FatalError	; 603C8
add esp, byte 4	; 603CD
.14:
mov ecx, 42h	; 603D0
mov ebx, 0FFFFFFFFh	; 603D5
mov edx, PenBuf	; 603DA
mov eax, dword [esp]	; 603DF
call FileWriteAt	; 603E2
test eax, eax	; 603E7
je short .15	; 603E9
push str_ErrSaveGame	; 603EB
call FatalError	; 603F0
add esp, byte 4	; 603F5
.15:
mov ecx, 0Bh	; 603F8
mov ebx, 0FFFFFFFFh	; 603FD
mov edx, byte_E9AC8	; 60402
mov eax, dword [esp]	; 60407
call FileWriteAt	; 6040A
test eax, eax	; 6040F
je short .16	; 60411
push str_ErrSaveGame	; 60413
call FatalError	; 60418
add esp, byte 4	; 6041D
.16:
mov ecx, 0Bh	; 60420
mov ebx, 0FFFFFFFFh	; 60425
mov edx, byte_E9AD3	; 6042A
mov eax, dword [esp]	; 6042F
call FileWriteAt	; 60432
test eax, eax	; 60437
je short .17	; 60439
push str_ErrSaveGame	; 6043B
call FatalError	; 60440
add esp, byte 4	; 60445
.17:
mov ecx, 0Bh	; 60448
mov ebx, 0FFFFFFFFh	; 6044D
mov edx, unk_C5423	; 60452
mov eax, dword [esp]	; 60457
call FileWriteAt	; 6045A
test eax, eax	; 6045F
je short .18	; 60461
push str_ErrSaveGame	; 60463
call FatalError	; 60468
add esp, byte 4	; 6046D
.18:
mov ecx, 0Bh	; 60470
mov ebx, 0FFFFFFFFh	; 60475
mov edx, unk_C542E	; 6047A
mov eax, dword [esp]	; 6047F
call FileWriteAt	; 60482
test eax, eax	; 60487
je short .19	; 60489
push str_ErrSaveGame	; 6048B
call FatalError	; 60490
add esp, byte 4	; 60495
.19:
mov ecx, 40h	; 60498
mov ebx, 0FFFFFFFFh	; 6049D
mov edx, hudpenhome	; 604A2
mov eax, dword [esp]	; 604A7
call FileWriteAt	; 604AA
test eax, eax	; 604AF
je short .20	; 604B1
push str_ErrSaveGame	; 604B3
call FatalError	; 604B8
add esp, byte 4	; 604BD
.20:
mov ecx, 40h	; 604C0
mov ebx, 0FFFFFFFFh	; 604C5
mov edx, hudpenaway	; 604CA
mov eax, dword [esp]	; 604CF
call FileWriteAt	; 604D2
test eax, eax	; 604D7
je short .21	; 604D9
push str_ErrSaveGame	; 604DB
call FatalError	; 604E0
add esp, byte 4	; 604E5
.21:
lea ebx, [byte esp+04h]	; 604E8
xor ecx, ecx	; 604EC
xor ebp, ebp	; 604EE
.22:
lea eax, [byte ecx+010h]	; 604F0
cmp eax, 80h	; 604F3
jbe short .24	; 604F8
mov ebx, 0FFFFFFFFh	; 604FA
lea edx, [byte esp+04h]	; 604FF
mov eax, dword [esp]	; 60503
call FileWriteAt	; 60506
test eax, eax	; 6050B
je short .23	; 6050D
push str_ErrSaveGame	; 6050F
call FatalError	; 60514
add esp, byte 4	; 60519
.23:
lea ebx, [byte esp+04h]	; 6051C
xor ecx, ecx	; 60520
.24:
mov esi, 19h	; 60522
mov eax, ebp	; 60527
mov edx, ebp	; 60529
sar edx, 1Fh	; 6052B
idiv esi	; 6052E
mov edi, eax	; 60530
shl edi, 2	; 60532
sub edi, eax	; 60535
shl edi, 3	; 60537
add edi, eax	; 6053A
shl edi, 4	; 6053C
mov eax, ebp	; 6053F
mov edx, ebp	; 60541
sar edx, 1Fh	; 60543
idiv esi	; 60546
shl edx, 4	; 60548
lea esi, [edi+edx]	; 6054B
mov edi, ebx	; 6054E
lea esi, [dword esi+dword_DB088]	; 60550
movsd	; 60556
movsd	; 60557
movsd	; 60558
movsd	; 60559
add ebx, byte 10h	; 6055A
add ecx, byte 10h	; 6055D
inc ebp	; 60560
cmp ebp, byte 32h	; 60561
jl short SaveGameState.22	; 60564
xor ebp, ebp	; 60566
.25:
lea eax, [byte ecx+06h]	; 60568
cmp eax, 80h	; 6056B
jbe short .27	; 60570
mov ebx, 0FFFFFFFFh	; 60572
lea edx, [byte esp+04h]	; 60577
mov eax, dword [esp]	; 6057B
call FileWriteAt	; 6057E
test eax, eax	; 60583
je short .26	; 60585
push str_ErrSaveGame	; 60587
call FatalError	; 6058C
add esp, byte 4	; 60591
.26:
lea ebx, [byte esp+04h]	; 60594
xor ecx, ecx	; 60598
.27:
mov esi, 3	; 6059A
mov eax, ebp	; 6059F
mov edx, ebp	; 605A1
sar edx, 1Fh	; 605A3
idiv esi	; 605A6
mov edi, eax	; 605A8
shl edi, 3	; 605AA
add edi, eax	; 605AD
add edi, edi	; 605AF
mov eax, ebp	; 605B1
mov edx, ebp	; 605B3
sar edx, 1Fh	; 605B5
idiv esi	; 605B8
mov eax, edx	; 605BA
shl eax, 2	; 605BC
sub eax, edx	; 605BF
add eax, eax	; 605C1
lea esi, [edi+eax]	; 605C3
mov edi, ebx	; 605C6
lea esi, [dword esi+unk_DC240]	; 605C8
movsd	; 605CE
movsw	; 605CF
add ebx, byte 6	; 605D1
add ecx, byte 6	; 605D4
inc ebp	; 605D7
cmp ebp, byte 6	; 605D8
jl short SaveGameState.25	; 605DB
test ecx, ecx	; 605DD
je short .28	; 605DF
mov ebx, 0FFFFFFFFh	; 605E1
lea edx, [byte esp+04h]	; 605E6
mov eax, dword [esp]	; 605EA
call FileWriteAt	; 605ED
test eax, eax	; 605F2
je short .28	; 605F4
push str_ErrSaveGame	; 605F6
call FatalError	; 605FB
add esp, byte 4	; 60600
.28:
xor eax, eax	; 60603
add esp, 90h	; 60605
SaveGameState_popx:
pop ebp	; 6060B
pop edi	; 6060C
pop esi	; 6060D
pop edx	; 6060E
pop ecx	; 6060F
pop ebx	; 60610
ret	; 60611
LoadGameState:
push dword 134h	; 60612
call __CHK	; 60617
push ebx	; 6061C
push ecx	; 6061D
push edx	; 6061E
push esi	; 6061F
push edi	; 60620
push ebp	; 60621
sub esp, 110h	; 60622
mov ebp, eax	; 60628
mov ecx, 4	; 6062A
mov ebx, 0FFFFFFFFh	; 6062F
mov edx, ctl1side	; 60634
call FileReadAt	; 60639
test eax, eax	; 6063E
je short .1	; 60640
push str_ErrSaveGame	; 60642
call FatalError	; 60647
add esp, byte 4	; 6064C
.1:
xor edx, edx	; 6064F
mov dword [dword esp+010Ch], edx	; 60651
.2:
mov edx, dword [dword esp+010Ch]	; 60658
shl edx, 7	; 6065F
add edx, SortCords	; 60662
mov ecx, 66h	; 60668
mov ebx, 0FFFFFFFFh	; 6066D
mov eax, ebp	; 60672
call FileReadAt	; 60674
test eax, eax	; 60679
je short .3	; 6067B
push str_ErrLoadGame	; 6067D
call FatalError	; 60682
add esp, byte 4	; 60687
.3:
mov ebx, dword [dword esp+010Ch]	; 6068A
inc ebx	; 60691
mov dword [dword esp+010Ch], ebx	; 60692
cmp ebx, byte 11h	; 60699
jl short LoadGameState.2	; 6069C
xor esi, esi	; 6069E
mov dword [dword esp+010Ch], esi	; 606A0
.4:
mov edx, dword [dword esp+010Ch]	; 606A7
shl edx, 8	; 606AE
add edx, hmtmstruct	; 606B1
mov ecx, 0D4h	; 606B7
mov ebx, 0FFFFFFFFh	; 606BC
mov eax, ebp	; 606C1
call FileReadAt	; 606C3
test eax, eax	; 606C8
je short .5	; 606CA
push str_ErrLoadGame	; 606CC
call FatalError	; 606D1
add esp, byte 4	; 606D6
.5:
mov edi, dword [dword esp+010Ch]	; 606D9
inc edi	; 606E0
mov dword [dword esp+010Ch], edi	; 606E1
cmp edi, byte 2	; 606E8
jl short LoadGameState.4	; 606EB
mov ecx, 30h	; 606ED
mov ebx, 0FFFFFFFFh	; 606F2
mov edx, hmlinetab	; 606F7
mov eax, ebp	; 606FC
call FileReadAt	; 606FE
test eax, eax	; 60703
je short .6	; 60705
push str_ErrLoadGame	; 60707
call FatalError	; 6070C
add esp, byte 4	; 60711
.6:
mov ecx, 30h	; 60714
mov ebx, 0FFFFFFFFh	; 60719
mov edx, awlinetab	; 6071E
mov eax, ebp	; 60723
call FileReadAt	; 60725
test eax, eax	; 6072A
je short .7	; 6072C
push str_ErrLoadGame	; 6072E
call FatalError	; 60733
add esp, byte 4	; 60738
.7:
mov ecx, 80h	; 6073B
mov ebx, 0FFFFFFFFh	; 60740
mov edx, esp	; 60745
mov eax, ebp	; 60747
call FileReadAt	; 60749
test eax, eax	; 6074E
je short .8	; 60750
push str_ErrLoadGame	; 60752
call FatalError	; 60757
add esp, byte 4	; 6075C
.8:
mov eax, dword [esp]	; 6075F
mov word [HomeTeam], ax	; 60762
mov ebx, esp	; 60768
add ebx, byte 2	; 6076A
mov ax, word [ebx]	; 6076D
mov word [VisTeam], ax	; 60770
add ebx, byte 2	; 60776
mov ax, word [ebx]	; 60779
mov word [camx], ax	; 6077C
add ebx, byte 2	; 60782
mov ax, word [ebx]	; 60785
mov word [camy], ax	; 60788
xor edx, edx	; 6078E
mov dword [dword esp+010Ch], edx	; 60790
add ebx, byte 2	; 60797
.9:
mov eax, dword [dword esp+010Ch]	; 6079A
mov dx, word [ebx]	; 607A1
mov word [nosplit eax*2+word_E0390], dx	; 607A4
add ebx, byte 2	; 607AC
lea ecx, [byte eax+01h]	; 607AF
mov dword [dword esp+010Ch], ecx	; 607B2
cmp ecx, byte 6	; 607B9
jl short LoadGameState.9	; 607BC
mov ax, word [ebx]	; 607BE
mov word [lastplayer], ax	; 607C1
add ebx, byte 2	; 607C7
mov ax, word [ebx]	; 607CA
mov word [passspeed], ax	; 607CD
add ebx, byte 2	; 607D3
mov ax, word [ebx]	; 607D6
mov word [passdir], ax	; 607D9
add ebx, byte 2	; 607DF
mov ax, word [ebx]	; 607E2
mov word [word_C90A6], ax	; 607E5
add ebx, byte 2	; 607EB
mov ax, word [ebx]	; 607EE
mov word [passplayer], ax	; 607F1
add ebx, byte 2	; 607F7
mov ax, word [ebx]	; 607FA
mov word [threat], ax	; 607FD
xor edi, edi	; 60803
mov dword [dword esp+010Ch], edi	; 60805
add ebx, byte 2	; 6080C
.10:
mov eax, dword [dword esp+010Ch]	; 6080F
mov dx, word [ebx]	; 60816
mov word [nosplit eax*2+puckcross], dx	; 60819
add ebx, byte 2	; 60821
inc eax	; 60824
mov dword [dword esp+010Ch], eax	; 60825
cmp eax, byte 4	; 6082C
jl short LoadGameState.10	; 6082F
mov ax, word [ebx]	; 60831
mov word [lj1], ax	; 60834
add ebx, byte 2	; 6083A
mov ax, word [ebx]	; 6083D
mov word [lj2], ax	; 60840
add ebx, byte 2	; 60846
mov ax, word [ebx]	; 60849
mov word [lasttouch], ax	; 6084C
add ebx, byte 2	; 60852
mov ax, word [ebx]	; 60855
mov word [ltx], ax	; 60858
add ebx, byte 2	; 6085E
mov ax, word [ebx]	; 60861
mov word [word_E9AC4], ax	; 60864
add ebx, byte 2	; 6086A
mov ax, word [ebx]	; 6086D
mov word [xc1], ax	; 60870
add ebx, byte 2	; 60876
mov ax, word [ebx]	; 60879
mov word [yc1], ax	; 6087C
add ebx, byte 2	; 60882
mov ax, word [ebx]	; 60885
mov word [dword_C90B0], ax	; 60888
add ebx, byte 2	; 6088E
mov ax, word [ebx]	; 60891
mov word [word_C90B2], ax	; 60894
add ebx, byte 2	; 6089A
mov ax, word [ebx]	; 6089D
mov word [word_C90B4], ax	; 608A0
add ebx, byte 2	; 608A6
mov ax, word [ebx]	; 608A9
mov word [fodir1], ax	; 608AC
add ebx, byte 2	; 608B2
mov ax, word [ebx]	; 608B5
mov word [fodir2], ax	; 608B8
add ebx, byte 2	; 608BE
mov ax, word [ebx]	; 608C1
mov word [sflags], ax	; 608C4
add ebx, byte 2	; 608CA
mov ax, word [ebx]	; 608CD
mov word [gmode2], ax	; 608D0
add ebx, byte 2	; 608D6
mov ax, word [ebx]	; 608D9
mov word [sflags3], ax	; 608DC
add ebx, byte 2	; 608E2
mov ax, word [ebx]	; 608E5
mov word [c1playernum], ax	; 608E8
add ebx, byte 2	; 608EE
mov ax, word [ebx]	; 608F1
mov word [c2playernum], ax	; 608F4
add ebx, byte 2	; 608FA
mov ax, word [ebx]	; 608FD
mov word [cont1team], ax	; 60900
add ebx, byte 2	; 60906
mov ax, word [ebx]	; 60909
mov word [cont2team], ax	; 6090C
add ebx, byte 2	; 60912
mov ax, word [ebx]	; 60915
mov word [Pencntdwn], ax	; 60918
add ebx, byte 2	; 6091E
mov ax, word [ebx]	; 60921
mov word [Penaltytimer], ax	; 60924
add ebx, byte 2	; 6092A
mov ax, word [ebx]	; 6092D
mov word [refsignal], ax	; 60930
add ebx, byte 2	; 60936
mov ax, word [ebx]	; 60939
mov word [RefStep], ax	; 6093C
add ebx, byte 2	; 60942
mov ax, word [ebx]	; 60945
mov word [RefPen], ax	; 60948
add ebx, byte 2	; 6094E
mov ax, word [ebx]	; 60951
mov word [word_C90D8], ax	; 60954
add ebx, byte 2	; 6095A
mov ax, word [ebx]	; 6095D
mov word [gsp], ax	; 60960
add ebx, byte 2	; 60966
mov ax, word [ebx]	; 60969
mov word [gameclock], ax	; 6096C
add ebx, byte 2	; 60972
mov ax, word [ebx]	; 60975
mov word [clockticks], ax	; 60978
add ebx, byte 2	; 6097E
movsx eax, word [ebx]	; 60981
mov dword [dword_CBC3E], eax	; 60984
add ebx, byte 2	; 60989
mov ax, word [ebx]	; 6098C
mov word [word_CBC44], ax	; 6098F
add ebx, byte 2	; 60995
mov ax, word [ebx]	; 60998
mov word [exitgame], ax	; 6099B
add ebx, byte 2	; 609A1
mov ax, word [ebx]	; 609A4
mov word [gameover], ax	; 609A7
add ebx, byte 2	; 609AD
mov ax, word [ebx]	; 609B0
mov word [word_CBEC0], ax	; 609B3
add ebx, byte 2	; 609B9
mov ax, word [ebx]	; 609BC
mov word [word_CBEC2], ax	; 609BF
add ebx, byte 2	; 609C5
mov ax, word [ebx]	; 609C8
mov word [word_CBEC4], ax	; 609CB
add ebx, byte 2	; 609D1
movsx eax, word [ebx]	; 609D4
mov dword [dword_C5840], eax	; 609D7
add ebx, byte 2	; 609DC
mov ax, word [ebx]	; 609DF
mov word [word_CBEC6], ax	; 609E2
add ebx, byte 2	; 609E8
mov ax, word [ebx]	; 609EB
mov word [word_E9AB0], ax	; 609EE
add ebx, byte 2	; 609F4
mov ax, word [ebx]	; 609F7
mov word [word_CBEC8], ax	; 609FA
add ebx, byte 2	; 60A00
mov ax, word [ebx]	; 60A03
mov word [dword_CBECA], ax	; 60A06
add ebx, byte 2	; 60A0C
mov eax, dword [ebx]	; 60A0F
mov dword [StanleyCupTimer], eax	; 60A11
add ebx, byte 4	; 60A16
mov ax, word [ebx]	; 60A19
mov word [PBnum], ax	; 60A1C
add ebx, byte 2	; 60A22
mov ax, word [ebx]	; 60A25
mov word [iflags], ax	; 60A28
mov ecx, 80h	; 60A2E
mov ebx, 0FFFFFFFFh	; 60A33
mov edx, esp	; 60A38
mov eax, ebp	; 60A3A
call FileReadAt	; 60A3C
test eax, eax	; 60A41
je short .11	; 60A43
push str_ErrLoadGame	; 60A45
call FatalError	; 60A4A
add esp, byte 4	; 60A4F
.11:
mov ebx, esp	; 60A52
xor ecx, ecx	; 60A54
mov dword [dword esp+010Ch], ecx	; 60A56
.12:
mov eax, dword [dword esp+010Ch]	; 60A5D
mov dx, word [ebx]	; 60A64
mov word [nosplit eax*2+PlList], dx	; 60A67
add ebx, byte 2	; 60A6F
lea esi, [byte eax+01h]	; 60A72
mov dword [dword esp+010Ch], esi	; 60A75
cmp esi, byte 6	; 60A7C
jl short LoadGameState.12	; 60A7F
mov al, byte [ebx]	; 60A81
mov byte [pad1dev], al	; 60A83
mov al, byte [byte ebx+01h]	; 60A88
mov byte [pad2dev], al	; 60A8B
add ebx, byte 2	; 60A90
mov al, byte [ebx]	; 60A93
mov byte [collflag], al	; 60A95
mov al, byte [byte ebx+01h]	; 60A9A
mov byte [gmode], al	; 60A9D
add ebx, byte 2	; 60AA2
mov ax, word [ebx]	; 60AA5
mov word [word_CBC52], ax	; 60AA8
add ebx, byte 2	; 60AAE
mov ax, word [ebx]	; 60AB1
mov word [word_CBC54], ax	; 60AB4
add ebx, byte 2	; 60ABA
mov ax, word [ebx]	; 60ABD
mov word [lcblink], ax	; 60AC0
add ebx, byte 2	; 60AC6
mov ax, word [ebx]	; 60AC9
mov word [word_CBC58], ax	; 60ACC
add ebx, byte 2	; 60AD2
mov ax, word [ebx]	; 60AD5
mov word [lcblinktime], ax	; 60AD8
add ebx, byte 2	; 60ADE
mov ax, word [ebx]	; 60AE1
mov word [lcblinktime+2], ax	; 60AE4
add ebx, byte 2	; 60AEA
mov ax, word [ebx]	; 60AED
mov word [lcsel], ax	; 60AF0
add ebx, byte 2	; 60AF6
mov ax, word [ebx]	; 60AF9
mov word [word_CBC60], ax	; 60AFC
add ebx, byte 2	; 60B02
mov ax, word [ebx]	; 60B05
mov word [lcline], ax	; 60B08
add ebx, byte 2	; 60B0E
mov ax, word [ebx]	; 60B11
mov word [word_CBC64], ax	; 60B14
add ebx, byte 2	; 60B1A
mov ax, word [ebx]	; 60B1D
mov word [lctimer], ax	; 60B20
add ebx, byte 2	; 60B26
mov ax, word [ebx]	; 60B29
mov word [word_CBC68], ax	; 60B2C
add ebx, byte 2	; 60B32
mov ax, word [ebx]	; 60B35
mov word [lcboxon], ax	; 60B38
add ebx, byte 2	; 60B3E
mov ax, word [ebx]	; 60B41
mov word [word_CBC6C], ax	; 60B44
add ebx, byte 2	; 60B4A
mov ax, word [ebx]	; 60B4D
mov word [lcrequest], ax	; 60B50
add ebx, byte 2	; 60B56
mov ax, word [ebx]	; 60B59
mov word [word_E0306], ax	; 60B5C
add ebx, byte 2	; 60B62
mov ax, word [ebx]	; 60B65
mov word [lcreqchoice], ax	; 60B68
add ebx, byte 2	; 60B6E
mov ax, word [ebx]	; 60B71
mov word [word_E0382], ax	; 60B74
add ebx, byte 2	; 60B7A
movsx eax, word [ebx]	; 60B7D
mov dword [dword_DF00C], eax	; 60B80
add ebx, byte 2	; 60B85
movsx eax, word [ebx]	; 60B88
mov dword [dword_DF010], eax	; 60B8B
add ebx, byte 2	; 60B90
movsx eax, word [ebx]	; 60B93
mov dword [word_DEF84], eax	; 60B96
add ebx, byte 2	; 60B9B
movsx eax, word [ebx]	; 60B9E
mov dword [word_DEF88], eax	; 60BA1
add ebx, byte 2	; 60BA6
movsx eax, word [ebx]	; 60BA9
mov dword [curperiod], eax	; 60BAC
add ebx, byte 2	; 60BB1
mov ax, word [ebx]	; 60BB4
mov word [lldispodd], ax	; 60BB7
add ebx, byte 2	; 60BBD
mov ax, word [ebx]	; 60BC0
mov word [dword_E9AB6], ax	; 60BC3
add ebx, byte 2	; 60BC9
mov ax, word [ebx]	; 60BCC
mov word [word_E9AAE], ax	; 60BCF
add ebx, byte 2	; 60BD5
mov ax, word [ebx]	; 60BD8
mov word [periodendtime], ax	; 60BDB
add ebx, byte 2	; 60BE1
mov ax, word [ebx]	; 60BE4
mov word [dword_E9A9E], ax	; 60BE7
add ebx, byte 2	; 60BED
mov ax, word [ebx]	; 60BF0
mov word [word_CC0DA], ax	; 60BF3
add ebx, byte 2	; 60BF9
mov ax, word [ebx]	; 60BFC
mov word [lastsfx], ax	; 60BFF
add ebx, byte 2	; 60C05
mov ax, word [ebx]	; 60C08
mov word [word_E9A9C], ax	; 60C0B
add ebx, byte 2	; 60C11
mov ax, word [ebx]	; 60C14
mov word [crowdlevel], ax	; 60C17
mov eax, dword [crowdlevel-2]	; 60C1D
sar eax, 10h	; 60C22
mov dword [crowdsmooth], eax	; 60C25
add ebx, byte 2	; 60C2A
mov ax, word [ebx]	; 60C2D
mov word [word_E9AAA], ax	; 60C30
add ebx, byte 2	; 60C36
mov ax, word [ebx]	; 60C39
mov word [word_E9AA2], ax	; 60C3C
add ebx, byte 2	; 60C42
mov ax, word [ebx]	; 60C45
mov word [CwdExciteLvl], ax	; 60C48
add ebx, byte 2	; 60C4E
mov ax, word [ebx]	; 60C51
mov word [word_E9AA4], ax	; 60C54
add ebx, byte 2	; 60C5A
mov ax, word [ebx]	; 60C5D
mov word [word_E9AA6], ax	; 60C60
add ebx, byte 2	; 60C66
movsx eax, word [ebx]	; 60C69
mov dword [dword_E009C], eax	; 60C6C
add ebx, byte 2	; 60C71
movsx eax, word [ebx]	; 60C74
mov dword [ctl1team], eax	; 60C77
add ebx, byte 2	; 60C7C
movsx eax, word [ebx]	; 60C7F
mov dword [ctl2team], eax	; 60C82
add ebx, byte 2	; 60C87
movsx eax, word [ebx]	; 60C8A
mov dword [ctl1dev], eax	; 60C8D
add ebx, byte 2	; 60C92
movsx eax, word [ebx]	; 60C95
mov dword [ctl2dev], eax	; 60C98
add ebx, byte 2	; 60C9D
movsx eax, word [ebx]	; 60CA0
mov dword [hudclockmin], eax	; 60CA3
add ebx, byte 2	; 60CA8
movsx eax, word [ebx]	; 60CAB
mov dword [hudclocksec], eax	; 60CAE
add ebx, byte 2	; 60CB3
movsx eax, word [ebx]	; 60CB6
mov dword [hudclockhund], eax	; 60CB9
add ebx, byte 2	; 60CBE
mov ax, word [ebx]	; 60CC1
mov word [word_CC0B0], ax	; 60CC4
add ebx, byte 2	; 60CCA
movsx eax, word [ebx]	; 60CCD
mov dword [dword_D8C78], eax	; 60CD0
add ebx, byte 2	; 60CD5
movsx eax, word [ebx]	; 60CD8
mov dword [frameaccum], eax	; 60CDB
add ebx, byte 2	; 60CE0
movsx eax, word [ebx]	; 60CE3
mov dword [dword_CC0AC], eax	; 60CE6
add ebx, byte 2	; 60CEB
mov ax, word [ebx]	; 60CEE
mov word [byte_E024C], ax	; 60CF1
add ebx, byte 2	; 60CF7
mov ax, word [ebx]	; 60CFA
mov word [word_E024E], ax	; 60CFD
add ebx, byte 2	; 60D03
movsx eax, word [ebx]	; 60D06
mov dword [gamemode], eax	; 60D09
add ebx, byte 2	; 60D0E
mov al, byte [ebx]	; 60D11
mov byte [byte_DC268], al	; 60D13
mov al, byte [byte ebx+01h]	; 60D18
mov byte [byte_DC267], al	; 60D1B
add ebx, byte 2	; 60D20
mov al, byte [ebx]	; 60D23
mov byte [byte_DC264], al	; 60D25
mov al, byte [byte ebx+01h]	; 60D2A
mov byte [byte_DC265], al	; 60D2D
add ebx, byte 2	; 60D32
mov al, byte [ebx]	; 60D35
mov byte [byte_DC266], al	; 60D37
movsx eax, byte [byte ebx+01h]	; 60D3C
mov dword [onetimerflag], eax	; 60D40
mov ecx, 80h	; 60D45
mov ebx, 0FFFFFFFFh	; 60D4A
mov edx, esp	; 60D4F
mov eax, ebp	; 60D51
call FileReadAt	; 60D53
test eax, eax	; 60D58
je short .13	; 60D5A
push str_ErrLoadGame	; 60D5C
call FatalError	; 60D61
add esp, byte 4	; 60D66
.13:
mov ebx, esp	; 60D69
mov ecx, 20h	; 60D6B
xor edx, edx	; 60D70
mov eax, word_E9B2C	; 60D72
call __STOSB	; 60D77
mov dword [dword esp+010Ch], 10h	; 60D7C
xor edx, edx	; 60D87
mov dword [dword esp+010Ch], edx	; 60D89
.14:
mov eax, dword [dword esp+010Ch]	; 60D90
mov esi, eax	; 60D97
shl esi, 2	; 60D99
sub esi, eax	; 60D9C
shl esi, 2	; 60D9E
add esi, word_DEE94	; 60DA1
mov ax, word [ebx]	; 60DA7
mov word [esi], ax	; 60DAA
movsx edi, ax	; 60DAD
mov eax, edi	; 60DB0
mov edx, edi	; 60DB2
sar edx, 1Fh	; 60DB4
shl edx, 4	; 60DB7
LD sbb, eax, edx	; 60DBA
sar eax, 4	; 60DBC
add eax, eax	; 60DBF
mov dword [dword esp+0100h], eax	; 60DC1
mov ecx, 10h	; 60DC8
mov eax, edi	; 60DCD
mov edx, edi	; 60DCF
sar edx, 1Fh	; 60DD1
idiv ecx	; 60DD4
mov cl, dl	; 60DD6
mov edx, 1	; 60DD8
shl edx, cl	; 60DDD
mov eax, dword [dword esp+0100h]	; 60DDF
mov eax, dword [dword eax+dword_E9B2A]	; 60DE6
sar eax, 10h	; 60DEC
or eax, edx	; 60DEF
mov edx, dword [dword esp+0100h]	; 60DF1
mov word [dword edx+word_E9B2C], ax	; 60DF8
add ebx, byte 2	; 60DFF
mov ax, word [ebx]	; 60E02
mov word [byte esi+02h], ax	; 60E05
add ebx, byte 2	; 60E09
test edi, edi	; 60E0C
jl short .15	; 60E0E
mov eax, edi	; 60E10
shl edi, 2	; 60E12
sub edi, eax	; 60E15
mov ax, word [nosplit edi*2+word_CCEF8]	; 60E17
mov word [byte esi+05h], ax	; 60E1F
inc edi	; 60E23
mov ax, word [nosplit edi*2+word_CCEF8]	; 60E24
mov word [byte esi+07h], ax	; 60E2C
inc edi	; 60E30
mov ax, word [nosplit edi*2+word_CCEF8]	; 60E31
mov word [byte esi+09h], ax	; 60E39
mov eax, dword [byte esi+07h]	; 60E3D
sar eax, 10h	; 60E40
mov al, byte [dword eax+byte_CCE00]	; 60E43
mov byte [byte esi+0Bh], al	; 60E49
mov eax, dword [byte esi+07h]	; 60E4C
sar eax, 10h	; 60E4F
mov edx, dword [esi]	; 60E52
sar edx, 18h	; 60E54
mov al, byte [dword edx+eax+byte_CCE00]	; 60E57
mov byte [byte esi+04h], al	; 60E5E
.15:
mov ecx, dword [dword esp+010Ch]	; 60E61
inc ecx	; 60E68
mov dword [dword esp+010Ch], ecx	; 60E69
cmp ecx, byte 14h	; 60E70
jl near LoadGameState.14	; 60E73
mov ax, word [ebx]	; 60E79
mov word [word_CBECC], ax	; 60E7C
add ebx, byte 2	; 60E82
mov ax, word [ebx]	; 60E85
mov word [word_CBECE], ax	; 60E88
add ebx, byte 2	; 60E8E
mov ax, word [ebx]	; 60E91
mov word [word_E9AB2], ax	; 60E94
add ebx, byte 2	; 60E9A
mov ax, word [ebx]	; 60E9D
mov word [word_E9AB4], ax	; 60EA0
add ebx, byte 2	; 60EA6
movsx eax, word [ebx]	; 60EA9
mov dword [dword_CC0F8], eax	; 60EAC
add ebx, byte 2	; 60EB1
movsx eax, word [ebx]	; 60EB4
mov dword [penshotplayer], eax	; 60EB7
add ebx, byte 2	; 60EBC
movsx eax, word [ebx]	; 60EBF
mov dword [dword_CC100], eax	; 60EC2
add ebx, byte 2	; 60EC7
movsx eax, word [ebx]	; 60ECA
mov dword [dword_CC104], eax	; 60ECD
add ebx, byte 2	; 60ED2
movsx eax, word [ebx]	; 60ED5
mov dword [dword_CC108], eax	; 60ED8
add ebx, byte 2	; 60EDD
movsx eax, word [ebx]	; 60EE0
mov dword [word_CC10C], eax	; 60EE3
add ebx, byte 2	; 60EE8
movsx eax, word [ebx]	; 60EEB
mov dword [dword_CC110], eax	; 60EEE
add ebx, byte 2	; 60EF3
movsx eax, word [ebx]	; 60EF6
mov dword [dword_CC114], eax	; 60EF9
add ebx, byte 2	; 60EFE
movsx eax, word [ebx]	; 60F01
mov dword [penshotmode], eax	; 60F04
add ebx, byte 2	; 60F09
movsx eax, word [ebx]	; 60F0C
mov dword [penshotstart], eax	; 60F0F
add ebx, byte 2	; 60F14
movsx eax, word [ebx]	; 60F17
mov dword [penshottimer], eax	; 60F1A
add ebx, byte 2	; 60F1F
movsx eax, word [ebx]	; 60F22
mov dword [dword_CC124], eax	; 60F25
add ebx, byte 2	; 60F2A
movsx eax, word [ebx]	; 60F2D
mov dword [penshotlive], eax	; 60F30
add ebx, byte 2	; 60F35
movsx eax, word [ebx]	; 60F38
mov dword [dword_CC12C], eax	; 60F3B
add ebx, byte 2	; 60F40
movsx eax, word [ebx]	; 60F43
mov dword [dword_CC130], eax	; 60F46
add ebx, byte 2	; 60F4B
movsx eax, word [ebx]	; 60F4E
mov dword [dword_CC134], eax	; 60F51
add ebx, byte 2	; 60F56
movsx eax, word [ebx]	; 60F59
mov dword [dword_CC138], eax	; 60F5C
add ebx, byte 2	; 60F61
movsx eax, word [ebx]	; 60F64
mov dword [dword_CC13C], eax	; 60F67
add ebx, byte 2	; 60F6C
movsx eax, word [ebx]	; 60F6F
mov dword [dword_CC140], eax	; 60F72
add ebx, byte 2	; 60F77
movsx eax, word [ebx]	; 60F7A
mov dword [dword_CC144], eax	; 60F7D
mov ecx, 42h	; 60F82
mov ebx, 0FFFFFFFFh	; 60F87
mov edx, PenBuf	; 60F8C
mov eax, ebp	; 60F91
call FileReadAt	; 60F93
test eax, eax	; 60F98
je short .16	; 60F9A
push str_ErrLoadGame	; 60F9C
call FatalError	; 60FA1
add esp, byte 4	; 60FA6
.16:
mov ecx, 0Bh	; 60FA9
mov ebx, 0FFFFFFFFh	; 60FAE
mov edx, byte_E9AC8	; 60FB3
mov eax, ebp	; 60FB8
call FileReadAt	; 60FBA
test eax, eax	; 60FBF
je short .17	; 60FC1
push str_ErrLoadGame	; 60FC3
call FatalError	; 60FC8
add esp, byte 4	; 60FCD
.17:
mov ecx, 0Bh	; 60FD0
mov ebx, 0FFFFFFFFh	; 60FD5
mov edx, byte_E9AD3	; 60FDA
mov eax, ebp	; 60FDF
call FileReadAt	; 60FE1
test eax, eax	; 60FE6
je short .18	; 60FE8
push str_ErrLoadGame	; 60FEA
call FatalError	; 60FEF
add esp, byte 4	; 60FF4
.18:
mov ecx, 0Bh	; 60FF7
mov ebx, 0FFFFFFFFh	; 60FFC
mov edx, unk_C5423	; 61001
mov eax, ebp	; 61006
call FileReadAt	; 61008
test eax, eax	; 6100D
je short .19	; 6100F
push str_ErrLoadGame	; 61011
call FatalError	; 61016
add esp, byte 4	; 6101B
.19:
mov ecx, 0Bh	; 6101E
mov ebx, 0FFFFFFFFh	; 61023
mov edx, unk_C542E	; 61028
mov eax, ebp	; 6102D
call FileReadAt	; 6102F
test eax, eax	; 61034
je short .20	; 61036
push str_ErrLoadGame	; 61038
call FatalError	; 6103D
add esp, byte 4	; 61042
.20:
mov ecx, 40h	; 61045
mov ebx, 0FFFFFFFFh	; 6104A
lea edx, [dword esp+0C0h]	; 6104F
mov eax, ebp	; 61056
call FileReadAt	; 61058
test eax, eax	; 6105D
je short .21	; 6105F
push str_ErrLoadGame	; 61061
call FatalError	; 61066
add esp, byte 4	; 6106B
.21:
mov ecx, 40h	; 6106E
mov ebx, 0FFFFFFFFh	; 61073
lea edx, [dword esp+080h]	; 61078
mov eax, ebp	; 6107F
call FileReadAt	; 61081
test eax, eax	; 61086
je short .22	; 61088
push str_ErrLoadGame	; 6108A
call FatalError	; 6108F
add esp, byte 4	; 61094
.22:
xor edi, edi	; 61097
mov dword [dword esp+0108h], edi	; 61099
mov dword [dword esp+010Ch], edi	; 610A0
.23:
cmp dword [dword esp+0108h], byte 0	; 610A7
jne short .26	; 610AF
mov dword [dword esp+0108h], 80h	; 610B1
cmp dword [dword esp+010Ch], byte 30h	; 610BC
jl short .24	; 610C4
mov dword [dword esp+0108h], 44h	; 610C6
.24:
mov ecx, dword [dword esp+0108h]	; 610D1
mov ebx, 0FFFFFFFFh	; 610D8
mov edx, esp	; 610DD
mov eax, ebp	; 610DF
call FileReadAt	; 610E1
test eax, eax	; 610E6
je short .25	; 610E8
push str_ErrLoadGame	; 610EA
call FatalError	; 610EF
add esp, byte 4	; 610F4
.25:
mov eax, esp	; 610F7
mov dword [dword esp+0104h], eax	; 610F9
.26:
mov ecx, dword [dword esp+0104h]	; 61100
mov ebx, 19h	; 61107
mov eax, dword [dword esp+010Ch]	; 6110C
mov edx, eax	; 61113
sar edx, 1Fh	; 61115
idiv ebx	; 61118
mov ebx, eax	; 6111A
shl ebx, 2	; 6111C
sub ebx, eax	; 6111F
shl ebx, 3	; 61121
lea esi, [eax+ebx]	; 61124
shl esi, 4	; 61127
mov ebx, 19h	; 6112A
mov eax, dword [dword esp+010Ch]	; 6112F
mov edx, eax	; 61136
sar edx, 1Fh	; 61138
idiv ebx	; 6113B
shl edx, 4	; 6113D
lea edi, [byte ecx+010h]	; 61140
mov dword [dword esp+0104h], edi	; 61143
lea edi, [dword edx+esi+dword_DB088]	; 6114A
mov esi, ecx	; 61151
movsd	; 61153
movsd	; 61154
movsd	; 61155
movsd	; 61156
sub dword [dword esp+0108h], byte 10h	; 61157
mov edx, dword [dword esp+010Ch]	; 6115F
inc edx	; 61166
mov dword [dword esp+010Ch], edx	; 61167
cmp edx, byte 32h	; 6116E
jl near LoadGameState.23	; 61171
mov ebp, dword [dword esp+0104h]	; 61177
xor ecx, ecx	; 6117E
mov dword [dword esp+010Ch], ecx	; 61180
.27:
mov esi, ebp	; 61187
mov ebx, 3	; 61189
mov eax, dword [dword esp+010Ch]	; 6118E
mov edx, eax	; 61195
sar edx, 1Fh	; 61197
idiv ebx	; 6119A
mov edi, eax	; 6119C
shl edi, 3	; 6119E
add edi, eax	; 611A1
add edi, edi	; 611A3
mov eax, dword [dword esp+010Ch]	; 611A5
mov edx, eax	; 611AC
sar edx, 1Fh	; 611AE
idiv ebx	; 611B1
mov ebx, edx	; 611B3
shl ebx, 2	; 611B5
sub ebx, edx	; 611B8
add ebp, byte 6	; 611BA
lea edi, [dword edi+ebx*2+unk_DC240]	; 611BD
movsd	; 611C4
movsw	; 611C5
mov esi, dword [dword esp+010Ch]	; 611C7
inc esi	; 611CE
mov dword [dword esp+010Ch], esi	; 611CF
cmp esi, byte 6	; 611D6
jl short LoadGameState.27	; 611D9
cmp byte [pad1dev], 1	; 611DB
je short .28	; 611E2
cmp byte [pad2dev], 1	; 611E4
jne short .29	; 611EB
.28:
push byte 64h	; 611ED
push dword 0A0h	; 611EF
call MouseSetPos	; 611F4
add esp, byte 8	; 611F9
.29:
mov eax, dword [gamemode]	; 611FC
cmp eax, byte 1	; 61201
jb short .30	; 61204
jbe short .31	; 61206
cmp eax, byte 2	; 61208
je short .32	; 6120B
jmp short .34	; 6120D
.30:
test eax, eax	; 6120F
jne short .34	; 61211
mov eax, exhstate	; 61213
call SaveModeState	; 61218
mov eax, exhstate	; 6121D
jmp short .33	; 61222
.31:
mov eax, postate	; 61224
call SaveModeState	; 61229
mov eax, postate	; 6122E
jmp short .33	; 61233
.32:
mov eax, lgstate	; 61235
call SaveModeState	; 6123A
mov eax, lgstate	; 6123F
.33:
call LoadModeState	; 61244
.34:
call GetPeriodTime	; 61249
mov word [PerTimeTotal], ax	; 6124E
mov eax, 1	; 61254
call LoadGameTeams	; 61259
mov edx, dword [HomeTeam]	; 6125E
sar edx, 10h	; 61264
mov eax, dword [cont2team]	; 61267
sar eax, 10h	; 6126C
mov ebx, unk_DF314	; 6126F
call sub_673C5	; 61274
mov ebp, 1	; 61279
mov dword [dword_C66D4], ebp	; 6127E
mov dword [dword_C66D0], ebp	; 61284
xor edx, edx	; 6128A
mov dword [dword_DC28C], edx	; 6128C
call LoadRockMusic	; 61292
mov ecx, 17h	; 61297
mov edx, 0FFFFFFFFh	; 6129C
mov eax, photobanks	; 612A1
call __STOSD	; 612A6
mov ebx, 0FFFFFFFFh	; 612AB
mov dword [photobankf], ebx	; 612B0
call LoadGameGfx	; 612B6
mov ecx, 17h	; 612BB
xor edx, edx	; 612C0
mov eax, photobanks	; 612C2
call __STOSD	; 612C7
xor ecx, ecx	; 612CC
mov dword [photobankf], ecx	; 612CE
mov eax, dword [dword_CBECA]	; 612D4
sar eax, 10h	; 612D9
cmp eax, ebx	; 612DC
je short .35	; 612DE
mov edx, dword [word_CBECC]	; 612E0
sar edx, 10h	; 612E6
cmp edx, ebx	; 612E9
je short .35	; 612EB
mov eax, dword [nosplit eax*4+off_CC01D]	; 612ED
mov dword [dword_E0248], eax	; 612F4
.35:
call sub_61E99	; 612F9
mov eax, dword [replaystart]	; 612FE
mov dword [recbpr], eax	; 61303
call ReplayRecordReset	; 61308
and byte [sflags], 0EFh	; 6130D
mov word [word_CBEC4], 1	; 61314
mov dword [hmtmsort], SortCords	; 6131D
mov dword [dword_DF6F2], unk_DACA0	; 61327
mov dword [dword_DF6F6], unk_DAC40	; 61331
mov dword [hmtmlines], hmlinetab	; 6133B
mov dword [hmtmplstats], dword_DB088	; 61345
mov dword [dword_DF6FE], unk_DC240	; 6134F
mov dword [hmtmroster], hmroster	; 61359
mov dword [hmtmptrF2], hmteamrec	; 61363
mov dword [awtmsort], SortCords+300h	; 6136D
mov dword [dword_DF7F2], unk_DAE94	; 61377
mov dword [dword_DF7F6], unk_DAC70	; 61381
mov dword [awtmlines], awlinetab	; 6138B
mov dword [awtmplstats], unk_DB218	; 61395
mov dword [dword_DF7FE], unk_DC252	; 6139F
mov dword [awtmroster], awroster	; 613A9
mov dword [awtmptrF2], awteamrec	; 613B3
mov ebx, SortCords	; 613BD
xor ebp, ebp	; 613C2
mov dword [dword esp+010Ch], ebp	; 613C4
.36:
mov eax, dword [dword esp+010Ch]	; 613CB
mov word [byte ebx+06Ah], ax	; 613D2
mov eax, dword [dword esp+010Ch]	; 613D6
mov esi, eax	; 613DD
shl esi, 3	; 613DF
add esi, eax	; 613E2
mov ax, word [nosplit esi*2+word_CBD64]	; 613E4
mov word [byte ebx+066h], ax	; 613EC
mov ax, word [nosplit esi*2+word_CBD66]	; 613F0
mov word [byte ebx+068h], ax	; 613F8
test byte [byte ebx+044h], 40h	; 613FC
je short .37	; 61400
mov eax, awtmstruct	; 61402
jmp short .38	; 61407
.37:
mov eax, hmtmstruct	; 61409
.38:
mov dword [byte ebx+06Ch], eax	; 6140E
test byte [byte ebx+044h], 40h	; 61411
jne short .39	; 61415
mov eax, awtmstruct	; 61417
jmp short .40	; 6141C
.39:
mov eax, hmtmstruct	; 6141E
.40:
mov dword [byte ebx+070h], eax	; 61423
mov eax, dword [ebx]	; 61426
mov dword [byte ebx+074h], eax	; 61428
mov eax, dword [byte ebx+04h]	; 6142B
mov dword [byte ebx+078h], eax	; 6142E
mov eax, dword [byte ebx+08h]	; 61431
mov dword [byte ebx+07Ch], eax	; 61434
mov eax, dword [dword esp+010Ch]	; 61437
mov dl, byte [dword esp+010Ch]	; 6143E
mov byte [dword eax+OOlist], dl	; 61445
mov edx, dword [dword esp+010Ch]	; 6144B
mov word [nosplit eax*2+OOlistpos], dx	; 61452
inc eax	; 6145A
mov dword [dword esp+010Ch], eax	; 6145B
add ebx, 80h	; 61462
cmp eax, byte 11h	; 61468
jl near LoadGameState.36	; 6146B
call SprSort	; 61471
xor ebx, ebx	; 61476
mov dword [dword esp+010Ch], ebx	; 61478
.41:
mov ebx, dword [dword esp+010Ch]	; 6147F
lea edi, [nosplit ebx*8+hudpenhome]	; 61486
lea esi, [dword esp+ebx*8+0C0h]	; 6148D
movsd	; 61494
movsd	; 61495
lea edi, [nosplit ebx*8+hudpenaway]	; 61496
lea esi, [dword esp+ebx*8+080h]	; 6149D
movsd	; 614A4
movsd	; 614A5
lea ecx, [byte ebx+01h]	; 614A6
mov dword [dword esp+010Ch], ecx	; 614A9
cmp ecx, byte 8	; 614B0
jl short LoadGameState.41	; 614B3
xor eax, eax	; 614B5
add esp, 110h	; 614B7
jmp near SaveGameState_popx	; 614BD
