; ea_memman_init 8DCF8-8DF70  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_8DCF8 progbits alloc exec nowrite align=1
extern _nmalloc_, asc_C3D88, dword_D2F5C, dword_D2F60, dword_D2F7C, dword_D2F80, dword_EDAA8, dword_EDAB0
extern dword_EDAB4, int386_, sub_8C990, sub_8CAF4, sub_8DAB8, sub_8DB4C, sub_8DCC0, sub_986B0
extern sub_986E4, FatalError, sub_B3F50, unk_EDF04, unknown_libname_22
global loc_8DD2F, loc_8DD58, loc_8DD71, loc_8DDF4, loc_8DEAD, loc_8DED0, loc_8DF06, sub_8DCF8
global sub_8DF28, sub_8DF3C, sub_8DF54
sub_8DCF8:
push esi	; 8DCF8
push edi	; 8DCF9
push ebp	; 8DCFA
sub esp, byte 40h	; 8DCFB
mov esi, dword [byte esp+054h]	; 8DCFE
mov edi, dword [byte esp+058h]	; 8DD02
call sub_986B0	; 8DD06
mov dword [dword_EDAB0], eax	; 8DD0B
push eax	; 8DD10
call unknown_libname_22	; 8DD11
add esp, byte 4	; 8DD16
call sub_B3F50	; 8DD19
call sub_8DCC0	; 8DD1E
mov edx, eax	; 8DD23
test esi, esi	; 8DD25
jle short loc_8DD2F	; 8DD27
cmp eax, esi	; 8DD29
jle short loc_8DD2F	; 8DD2B
mov edx, esi	; 8DD2D
loc_8DD2F:
and dl, 0F0h	; 8DD2F
mov eax, edx	; 8DD32
call _nmalloc_	; 8DD34
mov dword [dword_D2F80], eax	; 8DD39
add eax, edx	; 8DD3E
mov dword [dword_D2F7C], eax	; 8DD40
cmp dword [dword_D2F60], byte 0	; 8DD45
jne short loc_8DD58	; 8DD4C
mov dword [dword_D2F60], unk_EDF04	; 8DD4E
loc_8DD58:
cmp dword [dword_D2F5C], 0CCh	; 8DD58
jge short loc_8DD71	; 8DD62
push asc_C3D88	; 8DD64
call FatalError	; 8DD69
add esp, byte 4	; 8DD6E
loc_8DD71:
mov edx, dword [dword_D2F5C]	; 8DD71
shl edx, 2	; 8DD77
mov eax, dword [dword_D2F60]	; 8DD7A
lea ebx, [eax+edx]	; 8DD7F
mov dword [dword_EDAA8], ebx	; 8DD82
mov edx, dword [dword_D2F5C]	; 8DD88
sub edx, byte 2	; 8DD8E
mov dword [eax], edx	; 8DD91
mov dword [byte eax+04h], 0	; 8DD93
mov edx, dword [byte esp+050h]	; 8DD9A
lea eax, [nosplit edx*4+00h]	; 8DD9E
add eax, edx	; 8DDA5
shl eax, 3	; 8DDA7
mov dword [byte esp+03Ch], eax	; 8DDAA
push edx	; 8DDAE
mov edx, dword [dword_D2F80]	; 8DDAF
push edx	; 8DDB5
call sub_8DB4C	; 8DDB6
add esp, byte 8	; 8DDBB
push byte 0	; 8DDBE
push byte 8	; 8DDC0
push byte 8	; 8DDC2
mov ebx, dword [dword_D2F7C]	; 8DDC4
push ebx	; 8DDCA
mov eax, dword [dword_D2F80]	; 8DDCB
add eax, dword [byte esp+04Ch]	; 8DDD0
push eax	; 8DDD4
push byte 0	; 8DDD5
call sub_8C990	; 8DDD7
add esp, byte 18h	; 8DDDC
test esi, esi	; 8DDDF
jne near loc_8DF06	; 8DDE1
cmp edi, 3E80h	; 8DDE7
jge short loc_8DDF4	; 8DDED
mov edi, 3E80h	; 8DDEF
loc_8DDF4:
mov word [byte esp+01Ch], 100h	; 8DDF4
mov word [byte esp+020h], 0A000h	; 8DDFB
mov ebx, esp	; 8DE02
lea edx, [byte esp+01Ch]	; 8DE04
mov eax, 31h	; 8DE08
call int386_	; 8DE0D
mov ecx, 100h	; 8DE12
mov word [byte esp+01Ch], cx	; 8DE17
xor eax, eax	; 8DE1C
mov ax, word [byte esp+04h]	; 8DE1E
mov esi, eax	; 8DE23
shl esi, 4	; 8DE25
sub esi, edi	; 8DE28
test esi, esi	; 8DE2A
jle near loc_8DEAD	; 8DE2C
lea edx, [byte edi+0Fh]	; 8DE32
sar edx, 4	; 8DE35
sub eax, edx	; 8DE38
mov word [byte esp+020h], ax	; 8DE3A
mov ebx, esp	; 8DE3F
lea edx, [byte esp+01Ch]	; 8DE41
mov eax, 31h	; 8DE45
call int386_	; 8DE4A
xor eax, eax	; 8DE4F
mov ax, word [esp]	; 8DE51
mov ebp, eax	; 8DE55
shl ebp, 4	; 8DE57
xor esi, esi	; 8DE5A
mov si, word [byte esp+020h]	; 8DE5C
shl esi, 4	; 8DE61
test edi, edi	; 8DE64
je short loc_8DEAD	; 8DE66
mov word [byte esp+01Ch], cx	; 8DE68
mov word [byte esp+020h], 0A000h	; 8DE6D
mov ebx, esp	; 8DE74
lea edx, [byte esp+01Ch]	; 8DE76
mov eax, 31h	; 8DE7A
call int386_	; 8DE7F
mov word [byte esp+01Ch], cx	; 8DE84
mov eax, dword [byte esp+04h]	; 8DE89
mov word [byte esp+020h], ax	; 8DE8D
mov ebx, esp	; 8DE92
lea edx, [byte esp+01Ch]	; 8DE94
mov eax, 31h	; 8DE98
call int386_	; 8DE9D
xor eax, eax	; 8DEA2
mov ax, word [byte esp+0Ch]	; 8DEA4
mov dword [byte esp+038h], eax	; 8DEA9
loc_8DEAD:
call sub_8DCC0	; 8DEAD
mov edx, eax	; 8DEB2
cmp eax, 2710h	; 8DEB4
jl short loc_8DED0	; 8DEB9
call _nmalloc_	; 8DEBB
add edx, eax	; 8DEC0
push edx	; 8DEC2
push eax	; 8DEC3
push byte 0	; 8DEC4
call sub_8CAF4	; 8DEC6
add esp, byte 0Ch	; 8DECB
jmp short loc_8DEAD	; 8DECE
loc_8DED0:
test esi, esi	; 8DED0
jle short loc_8DF06	; 8DED2
add esi, ebp	; 8DED4
push esi	; 8DED6
push ebp	; 8DED7
push byte 0	; 8DED8
call sub_8CAF4	; 8DEDA
add esp, byte 0Ch	; 8DEDF
test edi, edi	; 8DEE2
je short loc_8DF06	; 8DEE4
mov word [byte esp+01Ch], 101h	; 8DEE6
mov eax, dword [byte esp+038h]	; 8DEED
mov word [byte esp+028h], ax	; 8DEF1
mov ebx, esp	; 8DEF6
lea edx, [byte esp+01Ch]	; 8DEF8
mov eax, 31h	; 8DEFC
call int386_	; 8DF01
loc_8DF06:
mov esi, dword [dword_EDAB0]	; 8DF06
push esi	; 8DF0C
call sub_986E4	; 8DF0D
add esp, byte 4	; 8DF12
call sub_8DAB8	; 8DF15
mov dword [dword_EDAB4], eax	; 8DF1A
add esp, byte 40h	; 8DF1F
pop ebp	; 8DF22
pop edi	; 8DF23
pop esi	; 8DF24
ret	; 8DF25
db 08Bh,0C0h
sub_8DF28:
push byte 0	; 8DF28
push byte 0	; 8DF2A
mov edx, dword [byte esp+0Ch]	; 8DF2C
push edx	; 8DF30
call sub_8DCF8	; 8DF31
add esp, byte 0Ch	; 8DF36
ret	; 8DF39
db 08Bh,0C0h
sub_8DF3C:
push byte 0	; 8DF3C
mov edx, dword [byte esp+0Ch]	; 8DF3E
push edx	; 8DF42
mov ebx, dword [byte esp+0Ch]	; 8DF43
push ebx	; 8DF47
call sub_8DCF8	; 8DF48
add esp, byte 0Ch	; 8DF4D
ret	; 8DF50
db 08Dh,040h,00h
sub_8DF54:
mov edx, dword [byte esp+08h]	; 8DF54
push edx	; 8DF58
push byte 0	; 8DF59
mov ebx, dword [byte esp+0Ch]	; 8DF5B
push ebx	; 8DF5F
call sub_8DCF8	; 8DF60
add esp, byte 0Ch	; 8DF65
ret	; 8DF68
db 00h,00h,00h,00h,00h,00h,00h
