; ea_gfx_02 90A40-90AC4  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_90A40 progbits alloc exec nowrite align=1
extern byte_D42C0, byte_D42C1, byte_D42C2, byte_D42C4, dword_D42C8, dword_D42D0
global loc_90A6C, loc_90A97, loc_90AA3, loc_90AAA, loc_90AB4, loc_90AB6, loc_90ABD, sub_90A40
sub_90A40:
push esi	; 90A40
push edi	; 90A41
push ebp	; 90A42
mov edx, dword [byte esp+010h]	; 90A43
mov ecx, dword [byte esp+014h]	; 90A47
xor eax, eax	; 90A4B
movzx esi, byte [byte_D42C1]	; 90A4D
xor ebx, ebx	; 90A54
mov bl, byte [byte_D42C0]	; 90A56
sub esi, ebx	; 90A5C
lea edi, [byte esi+01h]	; 90A5E
cmp byte [edx], 0	; 90A61
je short loc_90ABD	; 90A64
mov ebp, dword [dword_D42C8]	; 90A66
loc_90A6C:
test ecx, ecx	; 90A6C
je short loc_90ABD	; 90A6E
mov bl, byte [edx]	; 90A70
sub bl, byte [byte_D42C0]	; 90A72
and ebx, 0FFh	; 90A78
cmp ebx, edi	; 90A7E
jge short loc_90AB6	; 90A80
mov esi, dword [dword_D42D0]	; 90A82
test esi, esi	; 90A88
je short loc_90A97	; 90A8A
mov bl, byte [esi+ebx]	; 90A8C
and ebx, 0FFh	; 90A8F
jmp short loc_90AB4	; 90A95
loc_90A97:
test ebp, ebp	; 90A97
je short loc_90AA3	; 90A99
mov esi, ebp	; 90A9B
movzx esi, byte [esi+ebx]	; 90A9D
jmp short loc_90AAA	; 90AA1
loc_90AA3:
movzx esi, byte [byte_D42C2]	; 90AA3
loc_90AAA:
xor ebx, ebx	; 90AAA
mov bl, byte [byte_D42C4]	; 90AAC
add ebx, esi	; 90AB2
loc_90AB4:
add eax, ebx	; 90AB4
loc_90AB6:
inc edx	; 90AB6
dec ecx	; 90AB7
cmp byte [edx], 0	; 90AB8
jne short loc_90A6C	; 90ABB
loc_90ABD:
pop ebp	; 90ABD
pop edi	; 90ABE
pop esi	; 90ABF
ret	; 90AC0
db 08Dh,040h,00h
