; watcom_clib_22 96A58-96A60  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "x86enc.inc"
section s_96A58 progbits alloc exec nowrite align=1
global ios__failure__cause
ios__failure__cause:
mov eax, dword [byte esp+04h]	; 96A58
mov eax, dword [byte eax+04h]	; 96A5C
ret	; 96A5F
