; watcom_clib_28 98A81-98AC8  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_98A81 progbits alloc exec nowrite align=1
extern dword_D5444, sub_A1CF4
global loc_98AA0, loc_98AA4, loc_98AA8, loc_98ABE, spawnl_, strncmp_
spawnl_:
push ebx	; 98A81
push ecx	; 98A82
push edx	; 98A83
mov eax, dword [byte esp+010h]	; 98A84
mov edx, dword [byte esp+014h]	; 98A88
lea ebx, [byte esp+018h]	; 98A8C
mov ecx, dword [dword_D5444]	; 98A90
call sub_A1CF4	; 98A96
pop edx	; 98A9B
pop ecx	; 98A9C
pop ebx	; 98A9D
ret	; 98A9E
strncmp_:
push ecx	; 98A9F
loc_98AA0:
test ebx, ebx	; 98AA0
jne short loc_98AA8	; 98AA2
loc_98AA4:
xor eax, eax	; 98AA4
pop ecx	; 98AA6
ret	; 98AA7
loc_98AA8:
mov cl, byte [eax]	; 98AA8
mov ch, byte [edx]	; 98AAA
cmp cl, ch	; 98AAC
je short loc_98ABE	; 98AAE
xor ebx, ebx	; 98AB0
xor eax, eax	; 98AB2
mov bl, cl	; 98AB4
mov al, ch	; 98AB6
sub ebx, eax	; 98AB8
mov eax, ebx	; 98ABA
pop ecx	; 98ABC
ret	; 98ABD
loc_98ABE:
cmp byte [eax], 0	; 98ABE
je short loc_98AA4	; 98AC1
inc eax	; 98AC3
inc edx	; 98AC4
dec ebx	; 98AC5
jmp short loc_98AA0	; 98AC6
