; ea_unpack_helpers A2F40-A321C  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_A2F40 progbits alloc exec nowrite align=1
extern _FtoS_, byte_D42E4, dword_D30C8, dword_D43E4, forcedecpt_, sub_90354, sub_9035C, sub_90373
extern sub_903F0, sub_B01B0, sub_B026C, sub_B3ABC, sub_B763B
global loc_A2F61, loc_A3006, loc_A3015, loc_A3024, loc_A302C, loc_A308C, loc_A3092, loc_A30A1
global loc_A30AA, loc_A3105, loc_A312B, loc_A312C, loc_A313F, loc_A3172, loc_A317C, loc_A3189
global loc_A3196, loc_A3199, loc_A319E, loc_A31BF, loc_A31EE, loc_A31F2, loc_A31FA, loc_A3210
global sub_A2F40, sub_A2F84, sub_A2FD0, sub_A3050, sub_A30D0, sub_A30F8
sub_A2F40:
mov edx, dword [byte esp+04h]	; A2F40
mov ebx, dword [byte esp+08h]	; A2F44
mov eax, dword [byte esp+0Ch]	; A2F48
cmp dword [dword_D30C8], byte 0	; A2F4C
jne short loc_A2F61	; A2F53
push eax	; A2F55
push ebx	; A2F56
push edx	; A2F57
call sub_B763B	; A2F58
add esp, byte 0Ch	; A2F5D
ret	; A2F60
loc_A2F61:
mov dword [dword_D43E4], sub_B01B0	; A2F61
push eax	; A2F6B
push ebx	; A2F6C
push edx	; A2F6D
call sub_903F0	; A2F6E
add esp, byte 0Ch	; A2F73
mov dword [dword_D43E4], sub_B3ABC	; A2F76
ret	; A2F80
db 08Dh,040h,00h
sub_A2F84:
mov edx, dword [byte esp+04h]	; A2F84
mov eax, dword [byte edx+0Ch]	; A2F88
sar eax, 10h	; A2F8B
push eax	; A2F8E
mov eax, dword [byte edx+0Ah]	; A2F8F
sar eax, 10h	; A2F92
push eax	; A2F95
push edx	; A2F96
call sub_A2F40	; A2F97
add esp, byte 0Ch	; A2F9C
ret	; A2F9F
mov edx, dword [byte esp+04h]	; A2FA0
mov eax, dword [byte edx+08h]	; A2FA4
sar eax, 10h	; A2FA7
mov ebx, dword [byte esp+0Ch]	; A2FAA
sub ebx, eax	; A2FAE
push ebx	; A2FB0
mov eax, dword [byte edx+06h]	; A2FB1
sar eax, 10h	; A2FB4
mov ebx, dword [byte esp+0Ch]	; A2FB7
sub ebx, eax	; A2FBB
push ebx	; A2FBD
push edx	; A2FBE
call sub_A2F40	; A2FBF
add esp, byte 0Ch	; A2FC4
ret	; A2FC7
db 00h,00h,00h,00h,00h,00h,00h,00h
sub_A2FD0:
push esi	; A2FD0
push edi	; A2FD1
push ebp	; A2FD2
sub esp, byte 8	; A2FD3
mov eax, dword [byte esp+018h]	; A2FD6
mov eax, dword [byte eax+02h]	; A2FDA
sar eax, 10h	; A2FDD
mov dword [byte esp+04h], eax	; A2FE0
mov eax, dword [byte esp+018h]	; A2FE4
mov eax, dword [byte eax+04h]	; A2FE8
sar eax, 10h	; A2FEB
mov dword [esp], eax	; A2FEE
mov eax, dword [byte esp+018h]	; A2FF1
add eax, byte 10h	; A2FF5
xor edi, edi	; A2FF8
cmp dword [esp], byte 0	; A2FFA
jle short loc_A302C	; A2FFE
mov esi, dword [byte esp+04h]	; A3000
sar esi, 1	; A3004
loc_A3006:
mov ebp, dword [byte esp+04h]	; A3006
add ebp, eax	; A300A
lea edx, [byte ebp-01h]	; A300C
xor ebx, ebx	; A300F
test esi, esi	; A3011
jle short loc_A3024	; A3013
loc_A3015:
mov cl, byte [eax]	; A3015
mov ch, byte [edx]	; A3017
mov byte [eax], ch	; A3019
mov byte [edx], cl	; A301B
inc eax	; A301D
dec edx	; A301E
inc ebx	; A301F
cmp ebx, esi	; A3020
jl short loc_A3015	; A3022
loc_A3024:
mov eax, ebp	; A3024
inc edi	; A3026
cmp edi, dword [esp]	; A3027
jl short loc_A3006	; A302A
loc_A302C:
mov eax, dword [byte esp+04h]	; A302C
mov edx, dword [byte esp+018h]	; A3030
mov bx, word [byte edx+08h]	; A3034
sub eax, ebx	; A3038
mov word [byte edx+08h], ax	; A303A
add esp, byte 8	; A303E
pop ebp	; A3041
pop edi	; A3042
pop esi	; A3043
ret	; A3044
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
sub_A3050:
push esi	; A3050
push edi	; A3051
push ebp	; A3052
sub esp, byte 8	; A3053
mov esi, dword [byte esp+018h]	; A3056
mov esi, dword [byte esi+02h]	; A305A
sar esi, 10h	; A305D
mov eax, dword [byte esp+018h]	; A3060
mov eax, dword [byte eax+04h]	; A3064
sar eax, 10h	; A3067
mov dword [esp], eax	; A306A
mov edx, dword [byte esp+018h]	; A306D
add edx, byte 10h	; A3071
dec eax	; A3074
imul eax, esi	; A3075
add eax, edx	; A3078
xor edi, edi	; A307A
lea ebx, [esi+esi]	; A307C
mov dword [byte esp+04h], ebx	; A307F
mov ebp, dword [esp]	; A3083
sar ebp, 1	; A3086
test ebp, ebp	; A3088
jle short loc_A30AA	; A308A
loc_A308C:
xor ebx, ebx	; A308C
test esi, esi	; A308E
jle short loc_A30A1	; A3090
loc_A3092:
mov cl, byte [edx]	; A3092
mov ch, byte [eax]	; A3094
mov byte [edx], ch	; A3096
mov byte [eax], cl	; A3098
inc edx	; A309A
inc eax	; A309B
inc ebx	; A309C
cmp ebx, esi	; A309D
jl short loc_A3092	; A309F
loc_A30A1:
sub eax, dword [byte esp+04h]	; A30A1
inc edi	; A30A5
cmp edi, ebp	; A30A6
jl short loc_A308C	; A30A8
loc_A30AA:
mov eax, dword [esp]	; A30AA
mov edx, dword [byte esp+018h]	; A30AD
mov bx, word [byte edx+0Ah]	; A30B1
sub eax, ebx	; A30B5
mov word [byte edx+0Ah], ax	; A30B7
add esp, byte 8	; A30BB
pop ebp	; A30BE
pop edi	; A30BF
pop esi	; A30C0
ret	; A30C1
db 00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h,00h
sub_A30D0:
mov ebx, dword [byte esp+04h]	; A30D0
mov edx, dword [byte ebx+02h]	; A30D4
sar edx, 10h	; A30D7
mov eax, dword [byte ebx+04h]	; A30DA
sar eax, 10h	; A30DD
imul eax, edx	; A30E0
push eax	; A30E3
push byte_D42E4	; A30E4
lea eax, [byte ebx+010h]	; A30E9
push eax	; A30EC
call sub_B026C	; A30ED
add esp, byte 0Ch	; A30F2
ret	; A30F5
db 08Bh,0C0h
sub_A30F8:
push esi	; A30F8
push edi	; A30F9
sub esp, byte 8	; A30FA
mov edi, dword [byte esp+014h]	; A30FD
xor esi, esi	; A3101
jmp short loc_A312C	; A3103
loc_A3105:
mov eax, esp	; A3105
push eax	; A3107
push esi	; A3108
push edi	; A3109
call sub_90373	; A310A
add esp, byte 0Ch	; A310F
cmp byte [esp], 21h	; A3112
je short loc_A312B	; A3116
push esi	; A3118
push edi	; A3119
call sub_9035C	; A311A
add esp, byte 8	; A311F
push eax	; A3122
call sub_A30D0	; A3123
add esp, byte 4	; A3128
loc_A312B:
inc esi	; A312B
loc_A312C:
push edi	; A312C
call sub_90354	; A312D
add esp, byte 4	; A3132
cmp esi, eax	; A3135
jl short loc_A3105	; A3137
add esp, byte 8	; A3139
pop edi	; A313C
pop esi	; A313D
ret	; A313E
loc_A313F:
push ecx	; A313F
push esi	; A3140
push edi	; A3141
push ebp	; A3142
sub esp, byte 0Ch	; A3143
mov esi, eax	; A3146
mov edi, ebx	; A3148
mov dword [byte ebx+0Ch], 0	; A314A
mov word [byte esp+08h], ds	; A3151
mov cl, byte [byte edi+015h]	; A3155
xor ebx, ebx	; A3158
cmp cl, 47h	; A315A
jb short loc_A317C	; A315D
jbe short loc_A3189	; A315F
cmp cl, 66h	; A3161
jb short loc_A3172	; A3164
jbe short loc_A319E	; A3166
cmp cl, 67h	; A3168
je short loc_A3189	; A316B
jmp near loc_A3210	; A316D
loc_A3172:
cmp cl, 65h	; A3172
je short loc_A3199	; A3175
jmp near loc_A3210	; A3177
loc_A317C:
cmp cl, 45h	; A317C
jb near loc_A3210	; A317F
jbe short loc_A3199	; A3185
jmp short loc_A319E	; A3187
loc_A3189:
cmp dword [byte edi+08h], byte 0	; A3189
jne short loc_A3196	; A318D
mov dword [byte edi+08h], 1	; A318F
loc_A3196:
sub cl, 2	; A3196
loc_A3199:
mov ebx, 1	; A3199
loc_A319E:
mov ebp, dword [edx]	; A319E
add ebp, byte 8	; A31A0
mov dword [edx], ebp	; A31A3
mov eax, dword [byte ebp-08h]	; A31A5
mov dword [esp], eax	; A31A8
mov eax, dword [byte ebp-04h]	; A31AB
mov dword [byte esp+04h], eax	; A31AE
cmp dword [byte edi+08h], byte 0FFFFFFFFh	; A31B2
jne short loc_A31BF	; A31B6
mov dword [byte edi+08h], 6	; A31B8
loc_A31BF:
mov al, byte [byte edi+015h]	; A31BF
and al, 5Fh	; A31C2
and eax, 0FFh	; A31C4
push eax	; A31C9
xor eax, eax	; A31CA
mov al, cl	; A31CC
push eax	; A31CE
push byte 3	; A31CF
push ebx	; A31D1
lea edx, [byte esp+010h]	; A31D2
xor ecx, ecx	; A31D6
push byte 27h	; A31D8
mov eax, esi	; A31DA
mov ebx, dword [byte edi+08h]	; A31DC
call _FtoS_	; A31DF
mov ah, byte [esi]	; A31E4
cmp ah, 2Ah	; A31E6
jne short loc_A31EE	; A31E9
mov byte [byte edi+016h], ah	; A31EB
loc_A31EE:
mov byte [byte esi+027h], 0	; A31EE
loc_A31F2:
cmp byte [esi], 20h	; A31F2
jne short loc_A31FA	; A31F5
inc esi	; A31F7
jmp short loc_A31F2	; A31F8
loc_A31FA:
mov eax, esi	; A31FA
mov edx, edi	; A31FC
call forcedecpt_	; A31FE
mov word [byte esp+08h], ds	; A3203
mov eax, esi	; A3207
mov dword [byte edi+08h], 0FFFFFFFFh	; A3209
loc_A3210:
mov edx, dword [byte esp+08h]	; A3210
add esp, byte 0Ch	; A3214
pop ebp	; A3217
pop edi	; A3218
pop esi	; A3219
pop ecx	; A321A
ret	; A321B
