; input_keyboard_02 B29F0-B2D38  NHL 95 PC HOCKEY.EXE cseg01; generated by tools/gen_src.py, assembled by `make` (see docs/ASM_BUILD.md)
bits 32
%include "hockey.inc"
section s_B29F0 progbits alloc exec nowrite align=1
extern byte_D2C5C, byte_D2CD4, byte_D2CDC, byte_D2CF9, byte_D2D06, byte_D2D12, byte_D2D14, byte_D2D2F
extern byte_D2D7C, byte_D2DD7, byte_D2E32, byte_D2E8D, byte_D2EE8, dword_D2C84, dword_D2C8C, dword_D2CCC
extern dword_D2CD0, dword_D2CD8, dword_D2D5C, dword_D2D62, dword_D2D68, dword_D2F74, dword_D3024, dword_D41F0
extern sub_902A0, sub_93170, sub_9864C, sub_98664, sub_B3454, sub_B3A18, sub_B3E4A, sub_B3ED8
extern sub_B4BA8, word_D2D60, word_D2D66, word_D2D6C, word_D2D6E
global loc_B2A9A, loc_B2B09, loc_B2B3A, loc_B2B81, loc_B2B85, loc_B2BA5, loc_B2BA9, loc_B2BC0
global loc_B2BCE, loc_B2BD6, loc_B2BDC, loc_B2BDE, loc_B2BE5, loc_B2BED, loc_B2C3B, loc_B2C68
global loc_B2C6D, loc_B2C85, loc_B2CAC, loc_B2D01, loc_B2D11, sub_B29F0, sub_B2A9B, sub_B2B0A
global sub_B2C01, sub_B2C4A, sub_B2CBE, sub_B2CCD, sub_B2CD8, sub_B2D27, unk_B2C00
sub_B29F0:
cmp word [word_D2D6E], byte 0	; B29F0
jne near loc_B2A9A	; B29F8
o16 mov word [word_D2D6E], ds	; B29FE
in al, 21h	; B2A05
push eax	; B2A07
or al, 3	; B2A08
out 21h, al	; B2A0A
mov ebx, 9	; B2A0C
call sub_9864C	; B2A11
mov dword [dword_D2D5C], eax	; B2A16
mov word [word_D2D60], dx	; B2A1B
mov ebx, 16h	; B2A22
call sub_9864C	; B2A27
mov dword [dword_D2D62], eax	; B2A2C
mov word [word_D2D66], dx	; B2A31
mov ebx, 23h	; B2A38
call sub_9864C	; B2A3D
mov dword [dword_D2D68], eax	; B2A42
mov word [word_D2D6C], dx	; B2A47
mov dx, cs	; B2A4E
mov ebx, 9	; B2A51
mov eax, sub_B2B0A	; B2A56
call sub_98664	; B2A5B
mov dx, cs	; B2A60
mov ebx, 16h	; B2A63
mov eax, sub_B2C01	; B2A68
mov dx, cs	; B2A6D
mov ebx, 23h	; B2A70
mov eax, unk_B2C00	; B2A75
call sub_98664	; B2A7A
pop eax	; B2A7F
out 21h, al	; B2A80
mov ebx, sub_B2C4A	; B2A82
mov dword [dword_D2C84], ebx	; B2A87
push sub_B2A9B	; B2A8D
call sub_B3454	; B2A92
add esp, byte 4	; B2A97
loc_B2A9A:
ret	; B2A9A
sub_B2A9B:
cmp word [word_D2D6E], byte 0	; B2A9B
je short loc_B2B09	; B2AA3
mov word [word_D2D6E], 0	; B2AA5
pusha	; B2AAE
in al, 21h	; B2AAF
push eax	; B2AB1
or al, 3	; B2AB2
out 21h, al	; B2AB4
mov ebx, 9	; B2AB6
mov eax, dword [dword_D2D5C]	; B2ABB
mov dx, word [word_D2D60]	; B2AC0
call sub_98664	; B2AC7
mov ebx, 16h	; B2ACC
mov eax, dword [dword_D2D62]	; B2AD1
mov dx, word [word_D2D66]	; B2AD6
mov ebx, 23h	; B2ADD
mov eax, dword [dword_D2D68]	; B2AE2
mov dx, word [word_D2D6C]	; B2AE7
call sub_98664	; B2AEE
and byte [0417h], 0F0h	; B2AF3
pop eax	; B2AFA
out 21h, al	; B2AFB
mov ebx, sub_B2CCD	; B2AFD
mov dword [dword_D2C84], ebx	; B2B02
popa	; B2B08
loc_B2B09:
ret	; B2B09
sub_B2B0A:
push eax	; B2B0A
push ebx	; B2B0B
push ds	; B2B0C
in al, 61h	; B2B0D
LD mov, ah, al	; B2B0F
or al, 80h	; B2B11
out 61h, al	; B2B13
LD mov, al, ah	; B2B15
out 61h, al	; B2B17
LD xor, eax, eax	; B2B19
in al, 60h	; B2B1B
LD mov, ebx, eax	; B2B1D
db 066h,02Eh,08Eh,01Dh	; B2B1F o16 mov ds,[cs:12D6Eh]
dd word_D2D6E
LD or, bl, bl	; B2B27
jns short loc_B2B3A	; B2B29
mov byte [dword ebx+byte_D2C5C], 0	; B2B2B
mov al, 20h	; B2B32
out 20h, al	; B2B34
pop ds	; B2B36
pop ebx	; B2B37
pop eax	; B2B38
iret	; B2B39
loc_B2B3A:
mov byte [dword ebx+byte_D2CDC], 1	; B2B3A
mov al, 20h	; B2B41
out 20h, al	; B2B43
cmp ebx, byte 3Ah	; B2B45
je short loc_B2BA9	; B2B48
test byte [byte_D2D14], 1	; B2B4A
jne near loc_B2BDE	; B2B51
test byte [byte_D2CF9], 1	; B2B57
jne short loc_B2BD6	; B2B5E
test byte [byte_D2D06], 1	; B2B60
jne short loc_B2BCE	; B2B67
test byte [byte_D2D12], 1	; B2B69
jne short loc_B2BCE	; B2B70
test byte [byte_D2CD4], 1	; B2B72
jne short loc_B2BED	; B2B79
mov al, byte [dword ebx+byte_D2D7C]	; B2B7B
loc_B2B81:
cmp al, 80h	; B2B81
jae short loc_B2BC0	; B2B83
loc_B2B85:
LD or, eax, eax	; B2B85
je short loc_B2BA5	; B2B87
mov ebx, dword [dword_D2CCC]	; B2B89
mov dword [nosplit ebx*4+dword_D2C8C], eax	; B2B8F
add ebx, byte 1	; B2B96
and ebx, dword [dword_D2CD8]	; B2B99
mov dword [dword_D2CCC], ebx	; B2B9F
loc_B2BA5:
pop ds	; B2BA5
pop ebx	; B2BA6
pop eax	; B2BA7
iret	; B2BA8
loc_B2BA9:
xor dword [byte_D2CD4], byte 1	; B2BA9
mov al, 0EDh	; B2BB0
out 60h, al	; B2BB2
mov al, byte [byte_D2CD4]	; B2BB4
shl al, 2	; B2BB9
out 60h, al	; B2BBC
jmp short loc_B2BA5	; B2BBE
loc_B2BC0:
LD mov, ah, al	; B2BC0
LD xor, al, al	; B2BC2
cmp ah, 90h	; B2BC4
jb short loc_B2B85	; B2BC7
and ah, 7Fh	; B2BC9
jmp short loc_B2B85	; B2BCC
loc_B2BCE:
mov al, byte [dword ebx+byte_D2DD7]	; B2BCE
jmp short loc_B2B81	; B2BD4
loc_B2BD6:
mov al, byte [dword ebx+byte_D2E8D]	; B2BD6
loc_B2BDC:
jmp short loc_B2B81	; B2BDC
loc_B2BDE:
test byte [byte_D2CF9], 1	; B2BDE
loc_B2BE5:
mov al, byte [dword ebx+byte_D2EE8]	; B2BE5
jmp short loc_B2B81	; B2BEB
loc_B2BED:
mov al, byte [dword ebx+byte_D2E32]	; B2BED
jmp short loc_B2B81	; B2BF3
test byte [byte_D2D2F], 1	; B2BF5
je short loc_B2BE5	; B2BFC
jmp short loc_B2BDC	; B2BFE
unk_B2C00:
db 0CFh
sub_B2C01:
push ebx	; B2C01
push ecx	; B2C02
push edx	; B2C03
push esi	; B2C04
push edi	; B2C05
push ebp	; B2C06
push ds	; B2C07
push es	; B2C08
push fs	; B2C09
push gs	; B2C0B
LD mov, ebp, esp	; B2C0D
sub esp, byte 8	; B2C0F
cld	; B2C12
call sub_902A0	; B2C13
sti	; B2C18
call sub_B2C4A	; B2C19
pushf	; B2C1E
pop ebx	; B2C1F
and ebx, 4000h	; B2C20
jne short loc_B2C3B	; B2C26
LD mov, esp, ebp	; B2C28
pop gs	; B2C2A
pop fs	; B2C2C
pop es	; B2C2E
pop ds	; B2C2F
pop ebp	; B2C30
pop edi	; B2C31
pop esi	; B2C32
pop edx	; B2C33
pop ecx	; B2C34
pop ebx	; B2C35
LD or, eax, eax	; B2C36
retf 4	; B2C38
loc_B2C3B:
LD mov, esp, ebp	; B2C3B
pop gs	; B2C3D
pop fs	; B2C3F
pop es	; B2C41
pop ds	; B2C42
pop ebp	; B2C43
pop edi	; B2C44
pop esi	; B2C45
pop edx	; B2C46
pop ecx	; B2C47
pop ebx	; B2C48
iret	; B2C49
sub_B2C4A:
cmp ah, 0	; B2C4A
je short loc_B2C85	; B2C4D
cmp ah, 10h	; B2C4F
je short loc_B2C85	; B2C52
cmp ah, 1	; B2C54
je short loc_B2C6D	; B2C57
cmp ah, 11h	; B2C59
je short loc_B2C6D	; B2C5C
cmp ah, 2	; B2C5E
je short loc_B2CAC	; B2C61
cmp ah, 12h	; B2C63
je short loc_B2CAC	; B2C66
loc_B2C68:
LD xor, eax, eax	; B2C68
LD or, eax, eax	; B2C6A
ret	; B2C6C
loc_B2C6D:
mov ebx, dword [dword_D2CD0]	; B2C6D
cmp ebx, dword [dword_D2CCC]	; B2C73
je short loc_B2C68	; B2C79
mov eax, dword [nosplit ebx*4+dword_D2C8C]	; B2C7B
LD or, eax, eax	; B2C82
ret	; B2C84
loc_B2C85:
mov ebx, dword [dword_D2CD0]	; B2C85
cmp ebx, dword [dword_D2CCC]	; B2C8B
je short loc_B2C85	; B2C91
mov eax, dword [nosplit ebx*4+dword_D2C8C]	; B2C93
add ebx, byte 1	; B2C9A
and ebx, dword [dword_D2CD8]	; B2C9D
mov dword [dword_D2CD0], ebx	; B2CA3
LD or, eax, eax	; B2CA9
ret	; B2CAB
loc_B2CAC:
LD xor, eax, eax	; B2CAC
mov al, byte [byte_D2D06]	; B2CAE
or al, byte [byte_D2D12]	; B2CB3
and al, 1	; B2CB9
LD or, eax, eax	; B2CBB
ret	; B2CBD
sub_B2CBE:
push ebp	; B2CBE
LD mov, ebp, esp	; B2CBF
mov ebx, dword [byte ebp+08h]	; B2CC1
movzx eax, byte [dword ebx+byte_D2CDC]	; B2CC4
leave	; B2CCB
ret	; B2CCC
sub_B2CCD:
movzx eax, ax	; B2CCD
int 16h	; B2CD0
movzx eax, ax	; B2CD2
ret	; B2CD5
db 00h,00h
sub_B2CD8:
pop eax	; B2CD8
cmp dword [dword_D2F74], byte 0	; B2CD9
jne short loc_B2D11	; B2CE0
cmp dword [dword_D3024], byte 0	; B2CE2
je short loc_B2D01	; B2CE9
call sub_B4BA8	; B2CEB
push byte 0	; B2CF0
push byte 0	; B2CF2
call sub_93170	; B2CF4
add esp, byte 8	; B2CF9
call sub_B3A18	; B2CFC
loc_B2D01:
call sub_B3ED8	; B2D01
call sub_B3E4A	; B2D06
call dword [dword_D41F0]	; B2D0B
loc_B2D11:
push dword [dword_D2F74]	; B2D11
call sub_B3ED8	; B2D17
call sub_B3E4A	; B2D1C
call dword [dword_D41F0]	; B2D21
sub_B2D27:
ret	; B2D27
push ebp	; B2D28
LD mov, ebp, esp	; B2D29
mov eax, dword [byte ebp+08h]	; B2D2B
mov dword [dword_D2F74], eax	; B2D2E
leave	; B2D33
ret	; B2D34
db 00h,00h,00h
